import type { LifeEvent, WorldState } from '../types/game';
import type { BusinessEmployee, BusinessOpportunity, LogisticsBusiness, LogisticsContract, LogisticsKpiSnapshot, WarehouseFacility } from '../types/business';
import { SeededRng } from './rng';
import { deriveSeed } from './humanEngine';
import { ageAt } from './familyEngine';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.round(v*100)/100;
const addMonths=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,10);};
function playerChecking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open');}
function opportunitySet(world:WorldState):BusinessOpportunity[]{return[{id:`bizopp-contract-${world.date}`,type:'customer_contract',title:'Regional retail fulfillment contract',description:'A retailer needs monthly receiving, storage and outbound fulfillment with a demanding service target.',requiredCash:2500,expiresDate:addMonths(world.date,2),accepted:false},{id:`bizopp-facility-${world.date}`,type:'facility',title:'Larger warehouse lease',description:'A nearby facility could expand capacity but adds fixed monthly cost.',requiredCash:18000,expiresDate:addMonths(world.date,3),accepted:false}];}
export function initializeBusinessWorld(world:WorldState){world.businesses??=[];world.warehouseFacilities??=[];world.businessEmployees??=[];world.logisticsContracts??=[];world.logisticsKpis??=[];world.businessOpportunities??=[];if(world.businessOpportunities.length===0)world.businessOpportunities.push(...opportunitySet(world));return world;}
export function playerBusiness(world:WorldState){return world.businesses.find(b=>b.status==='active'&&b.ownerShares.some(o=>o.personId===world.character.id));}
function seedEmployee(businessId:string,index:number,role:BusinessEmployee['role'],rng:SeededRng):BusinessEmployee{const first=['Jordan','Taylor','Morgan','Casey','Avery','Cameron','Riley','Drew'][index%8],last=['Reed','Hayes','Miller','Torres','Brooks','Price'][Math.floor(rng.next()*6)];return{id:`bizemployee-${businessId}-${index}`,businessId,personId:null,name:`${first} ${last}`,role,annualPay:role==='manager'?62000:role==='supervisor'?49000:role==='lead'?41000:34000,productivity:55+rng.next()*28,reliability:58+rng.next()*32,morale:62+rng.next()*24,safety:68+rng.next()*25,active:true};}
export function startLogisticsBusiness(input:WorldState,name='Booker Logistics'):WorldState{const world=initializeBusinessWorld(structuredClone(input)),age=ageAt(world.character.birthDate,world.date),checking=playerChecking(world);if(age<18||playerBusiness(world)||!checking||checking.balance<5000)return world;const startup=5000,id=`business-logistics-${world.date}`;checking.balance=money(checking.balance-startup);world.character.cash=checking.balance;world.ledger.unshift({id:`business-start-${world.date}`,date:world.date,description:'Business startup capital',amount:-startup,category:'Business'});const business:LogisticsBusiness={id,name:name.trim()||'New Logistics Company',foundedDate:world.date,ownerShares:[{personId:world.character.id,share:100}],cash:startup,debt:0,reputation:48,valuation:startup,status:'active',facilityIds:[],employeeIds:[],contractIds:[],pricingIndex:1,staffingTarget:3},facility:WarehouseFacility={id:`facility-${id}-1`,businessId:id,location:world.character.location,squareFeet:4500,palletCapacity:420,monthlyRent:3200,condition:82,automationLevel:18,utilization:0};world.businesses.push(business);world.warehouseFacilities.push(facility);business.facilityIds.push(facility.id);const rng=new SeededRng(deriveSeed(world.seed,`business-start:${id}`));for(let i=0;i<2;i++){const employee=seedEmployee(id,i+1,i===0?'lead':'associate',rng);world.businessEmployees.push(employee);business.employeeIds.push(employee.id);}const pilot:LogisticsContract={id:`contract-${id}-pilot`,businessId:id,customerName:'Copper State Goods',monthlyUnits:3200,revenuePerUnit:4.3,serviceTarget:94,complexity:38,startDate:world.date,endDate:addMonths(world.date,12),status:'active'};world.logisticsContracts.push(pilot);business.contractIds.push(pilot.id);world.character.career=`Owner · ${business.name}`;world.events.unshift({id:`evt-business-start-${id}`,date:world.date,title:`You started ${business.name}`,body:'The company has its own cash, facility, employees, customer contract and operating risk. Personal and business finances remain separate.',type:'opportunity',priority:'major'});return world;}
export function hireBusinessEmployee(input:WorldState,role:BusinessEmployee['role']='associate'):WorldState{const world=structuredClone(input),business=playerBusiness(world);if(!business||business.cash<1500)return world;const rng=new SeededRng(deriveSeed(world.seed,`hire:${business.id}:${world.date}:${business.employeeIds.length}`)),employee=seedEmployee(business.id,business.employeeIds.length+1,role,rng);world.businessEmployees.push(employee);business.employeeIds.push(employee.id);business.cash-=800;return world;}
export function setStaffingTarget(input:WorldState,target:number):WorldState{const world=structuredClone(input),business=playerBusiness(world);if(business)business.staffingTarget=Math.round(clamp(target,1,100));return world;}
export function setBusinessPricing(input:WorldState,index:number):WorldState{const world=structuredClone(input),business=playerBusiness(world);if(business)business.pricingIndex=clamp(index,.75,1.4);return world;}
export function acceptBusinessOpportunity(input:WorldState,opportunityId:string):WorldState{const world=structuredClone(input),business=playerBusiness(world),op=world.businessOpportunities.find(o=>o.id===opportunityId&&!o.accepted&&o.expiresDate>=world.date);if(!business||!op||business.cash<op.requiredCash)return world;if(op.type==='customer_contract'){business.cash-=op.requiredCash;const contract:LogisticsContract={id:`contract-${business.id}-${world.date}-${business.contractIds.length+1}`,businessId:business.id,customerName:'Mesa Home & Market',monthlyUnits:5200,revenuePerUnit:4.65,serviceTarget:96,complexity:58,startDate:world.date,endDate:addMonths(world.date,18),status:'active'};world.logisticsContracts.push(contract);business.contractIds.push(contract.id);}else if(op.type==='facility'){business.cash-=op.requiredCash;const facility:WarehouseFacility={id:`facility-${business.id}-${business.facilityIds.length+1}`,businessId:business.id,location:world.character.location,squareFeet:18000,palletCapacity:1800,monthlyRent:11800,condition:92,automationLevel:34,utilization:0};world.warehouseFacilities.push(facility);business.facilityIds.push(facility.id);}op.accepted=true;return world;}
function monthKpis(world:WorldState,business:LogisticsBusiness,date:string,rng:SeededRng):LogisticsKpiSnapshot{const employees=business.employeeIds.map(id=>world.businessEmployees.find(e=>e.id===id)).filter((e):e is BusinessEmployee=>Boolean(e?.active)),facilities=business.facilityIds.map(id=>world.warehouseFacilities.find(f=>f.id===id)).filter((f):f is WarehouseFacility=>Boolean(f)),contracts=business.contractIds.map(id=>world.logisticsContracts.find(c=>c.id===id)).filter((c):c is LogisticsContract=>Boolean(c&&c.status==='active')),headcount=Math.max(1,employees.length),avgProductivity=employees.reduce((s,e)=>s+e.productivity,0)/headcount,avgReliability=employees.reduce((s,e)=>s+e.reliability,0)/headcount,avgSafety=employees.reduce((s,e)=>s+e.safety,0)/headcount,capacity=facilities.reduce((s,f)=>s+f.palletCapacity*12*(.75+f.automationLevel/250),0),requested=contracts.reduce((s,c)=>s+c.monthlyUnits,0),laborCapacity=headcount*1750*(avgProductivity/70),handled=Math.min(requested,capacity,laborCapacity),utilization=capacity?clamp(requested/capacity*100):100,staffingPressure=requested/Math.max(1,laborCapacity),productivity=clamp(avgProductivity*(staffingPressure>1?1/staffingPressure:1.02)+(rng.next()-.5)*4),inventoryAccuracy=clamp(94+(avgReliability-65)*.07-(utilization>90?(utilization-90)*.12:0)+(rng.next()-.5)*2),serviceLevel=requested?clamp(handled/requested*100-(business.pricingIndex>1.18?1.5:0)+(rng.next()-.5)*1.5):100,safety=clamp(avgSafety-(utilization>92?(utilization-92)*.18:0)+(rng.next()-.5)*2),revenue=contracts.reduce((s,c)=>{const share=requested?handled/requested:1;return s+c.monthlyUnits*share*c.revenuePerUnit*business.pricingIndex;},0),laborCost=employees.reduce((s,e)=>s+e.annualPay/12,0),rent=facilities.reduce((s,f)=>s+f.monthlyRent,0),overhead=2200+revenue*.06,operatingProfit=revenue-laborCost-rent-overhead;for(const f of facilities)f.utilization=utilization;return{id:`kpi-${business.id}-${date}`,businessId:business.id,date,productivity,inventoryAccuracy,serviceLevel,safety,laborCost:money(laborCost),facilityUtilization:utilization,revenue:money(revenue),operatingProfit:money(operatingProfit)};}
function applyBusinessMonth(world:WorldState,business:LogisticsBusiness,date:string,rng:SeededRng,events:LifeEvent[]){const kpi=monthKpis(world,business,date,rng);world.logisticsKpis.unshift(kpi);business.cash=money(business.cash+kpi.operatingProfit);const serviceGap=Math.max(0,94-kpi.serviceLevel),safetyGap=Math.max(0,85-kpi.safety);business.reputation=clamp(business.reputation+(kpi.serviceLevel>=96?.7:-serviceGap*.18)-(safetyGap*.1));if(business.cash<0){const needed=Math.abs(business.cash)+5000;if(business.debt<50000){business.debt=money(business.debt+needed);business.cash=5000;}else{business.status='bankrupt';events.push({id:`evt-business-bankrupt-${business.id}-${date}`,date,title:`${business.name} failed`,body:'Operating losses and debt exhausted the company’s ability to continue. The business closed, but its history remains part of your life.',type:'finance',priority:'major'});}}business.valuation=money(Math.max(0,business.cash-business.debt+Math.max(0,kpi.operatingProfit)*24+business.reputation*800));for(const e of world.businessEmployees.filter(e=>e.businessId===business.id&&e.active)){e.morale=clamp(e.morale+(kpi.serviceLevel>96?.5:-.4)+(employeesCount(world,business)>business.staffingTarget?-.2:.1));e.productivity=clamp(e.productivity+.08+(e.morale-50)/900);e.safety=clamp(e.safety+(kpi.safety>90?.1:-.08));}if(kpi.serviceLevel<88)events.push({id:`evt-business-service-${business.id}-${date}`,date,title:'A customer relationship is under pressure',body:`${business.name} missed service expectations. Contract loss becomes more likely if performance stays weak.`,type:'opportunity',priority:'medium'});}
function employeesCount(world:WorldState,business:LogisticsBusiness){return world.businessEmployees.filter(e=>e.businessId===business.id&&e.active).length;}
function refreshOpportunities(world:WorldState,date:string){const month=Number(date.slice(5,7)),day=Number(date.slice(-2));if(day!==15||![1,4,7,10].includes(month))return;const active=world.businessOpportunities.filter(o=>!o.accepted&&o.expiresDate>=date);if(active.length===0)world.businessOpportunities.push(...opportunitySet({...world,date}));}
export function simulateBusiness(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{initializeBusinessWorld(world);const events:LifeEvent[]=[];refreshOpportunities(world,date);for(const contract of world.logisticsContracts.filter(c=>c.status==='active'&&c.endDate<date))contract.status='ended';if(Number(date.slice(-2))===1)for(const business of world.businesses.filter(b=>b.status==='active'))applyBusinessMonth(world,business,date,new SeededRng(deriveSeed(world.seed,`business:${business.id}:${date}`)),events);void rng;return events;}
