import type { Employment, JobApplication, LifeEvent, WorldState } from '../types/game';
import { SeededRng } from './rng';
import { ageAt } from './familyEngine';
import { deriveSeed } from './humanEngine';
import { credentialRank, highestCredential, initializeProgression, skillLevel, syncPrimarySchedule } from './progressionSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const DAY=86_400_000;
const daysBetween=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/DAY);
function addEvent(world:WorldState,event:LifeEvent){world.events=[event,...world.events].slice(0,120);}
export function activeEmployment(world:WorldState,personId=world.character.id){return world.employments.find(e=>e.personId===personId&&e.status==='active');}
function applicationScore(world:WorldState,openingId:string){const opening=world.jobOpenings.find(o=>o.id===openingId);if(!opening)return 0;const credential=highestCredential(world,world.character.id),credentialGap=credentialRank[credential]-credentialRank[opening.requiredCredential];const skillAverage=opening.requiredSkills.length?opening.requiredSkills.reduce((sum,s)=>sum+skillLevel(world,world.character.id,s),0)/opening.requiredSkills.length:55;const t=world.character.traits;return clamp(skillAverage*.45+t.confidence*.14+t.ambition*.12+t.discipline*.12+world.laborMarket.demandIndex*.12+Math.max(-24,credentialGap*12));}
export function applyForJob(input:WorldState,openingId:string):WorldState{const world=initializeProgression(structuredClone(input)),opening=world.jobOpenings.find(o=>o.id===openingId&&o.status==='open');if(!opening||world.jobApplications.some(a=>a.openingId===openingId&&a.personId===world.character.id&&!['rejected','withdrawn'].includes(a.status)))return world;const score=applicationScore(world,openingId),application:JobApplication={id:`application-${openingId}-${world.date}`,personId:world.character.id,openingId,appliedDate:world.date,status:'submitted',score,offerSalary:null,lastUpdatedDate:world.date};world.jobApplications.unshift(application);const employer=world.employers.find(e=>e.id===opening.employerId);addEvent(world,{id:`evt-application-${application.id}`,date:world.date,title:`You applied for ${opening.title}`,body:`Your application is now with ${employer?.name??'the employer'}. Experience, credentials, skills and the labor market will influence what happens next.`,type:'opportunity',priority:'low'});return world;}
function createEmployment(world:WorldState,application:JobApplication):Employment|null{const opening=world.jobOpenings.find(o=>o.id===application.openingId);if(!opening||application.status!=='offer')return null;const existing=activeEmployment(world);if(existing){existing.status='ended';existing.endDate=world.date;}const employment:Employment={id:`employment-${world.character.id}-${opening.id}-${world.date}`,personId:world.character.id,employerId:opening.employerId,title:opening.title,level:opening.level,startDate:world.date,endDate:null,status:'active',salaryAnnual:application.offerSalary??opening.salaryAnnual,payFrequency:'biweekly',hoursPerWeek:opening.hoursPerWeek,schedule:opening.schedule,remote:opening.remote,benefits:{healthInsurance:true,retirementMatch:opening.level==='manager'||opening.level==='executive'?6:4,ptoDays:opening.level==='entry'?15:20},performance:55,satisfaction:62,managerId:null};world.employments.push(employment);application.status='accepted';application.lastUpdatedDate=world.date;opening.status='filled';world.character.career=opening.title;syncPrimarySchedule(world,world.character.id,opening.title,opening.schedule.days,opening.schedule.startHour,opening.schedule.endHour);return employment;}
export function acceptJobOffer(input:WorldState,applicationId:string):WorldState{const world=structuredClone(input),application=world.jobApplications.find(a=>a.id===applicationId&&a.personId===world.character.id&&a.status==='offer');if(!application)return world;const employment=createEmployment(world,application);if(!employment)return world;const employer=world.employers.find(e=>e.id===employment.employerId);world.memories.unshift({id:`mem-job-${employment.id}`,date:world.date,title:`Started ${employment.title}`,summary:`You joined ${employer?.name??'a new employer'} as ${employment.title}.`,significance:75});addEvent(world,{id:`evt-job-start-${employment.id}`,date:world.date,title:`You accepted the ${employment.title} role`,body:`Your pay, schedule, benefits and performance expectations at ${employer?.name??'your new employer'} are now part of your daily life.`,type:'opportunity',priority:'major'});return world;}
export function leaveJob(input:WorldState):WorldState{const world=structuredClone(input),employment=activeEmployment(world);if(!employment)return world;employment.status='ended';employment.endDate=world.date;world.character.career='Unemployed';world.character.human.needs.security=clamp(world.character.human.needs.security-10);addEvent(world,{id:`evt-job-left-${employment.id}-${world.date}`,date:world.date,title:'You left your job',body:'Income from this role has stopped. Your time opened up, but financial pressure may rise.',type:'finance',priority:'major'});return world;}
function payrollDue(e:Employment,date:string){const elapsed=daysBetween(e.startDate,date);if(elapsed<=0)return false;if(e.payFrequency==='weekly')return elapsed%7===0;if(e.payFrequency==='biweekly')return elapsed%14===0;if(e.payFrequency==='semimonthly'){const d=Number(date.slice(-2));return d===1||d===15;}return Number(date.slice(-2))===1;}
function payAmount(e:Employment){const divisor=e.payFrequency==='weekly'?52:e.payFrequency==='biweekly'?26:e.payFrequency==='semimonthly'?24:12;return Math.round(e.salaryAnnual/divisor);}
function processPayroll(world:WorldState,date:string){for(const employment of world.employments.filter(e=>e.status==='active'&&e.personId===world.character.id&&payrollDue(e,date))){const gross=payAmount(employment),estimatedTax=Math.round(gross*.19),net=gross-estimatedTax;world.character.cash+=net;world.character.human.needs.security=clamp(world.character.human.needs.security+1.6);world.ledger.unshift({id:`payroll-${employment.id}-${date}`,date,description:`Payroll · ${employment.title}`,amount:net,category:'Income'});}}
function processApplications(world:WorldState,date:string){const events:LifeEvent[]=[];for(const app of world.jobApplications.filter(a=>a.personId===world.character.id&&['submitted','interview'].includes(a.status))){const sinceUpdate=daysBetween(app.lastUpdatedDate,date),opening=world.jobOpenings.find(o=>o.id===app.openingId);if(!opening)continue;if(app.status==='submitted'&&sinceUpdate>=4){if(app.score>=48){app.status='interview';app.lastUpdatedDate=date;events.push({id:`evt-interview-${app.id}-${date}`,date,title:`Interview invitation · ${opening.title}`,body:'The employer wants to continue the process. An interview does not guarantee an offer.',type:'opportunity',priority:'medium'});}else{app.status='rejected';app.lastUpdatedDate=date;events.push({id:`evt-rejected-${app.id}-${date}`,date,title:`Application closed · ${opening.title}`,body:'The employer chose not to continue with your application this time.',type:'opportunity',priority:'low'});}}else if(app.status==='interview'&&sinceUpdate>=3){const rng=new SeededRng(deriveSeed(world.seed,`interview:${app.id}:${date}`)),interviewScore=app.score+world.character.traits.confidence*.12+world.character.traits.emotional*.08+(rng.next()-.5)*18;if(interviewScore>=61){app.status='offer';app.offerSalary=Math.round(opening.salaryAnnual*(.97+rng.next()*.08));app.lastUpdatedDate=date;events.push({id:`evt-offer-${app.id}-${date}`,date,title:`Job offer · ${opening.title}`,body:`The employer offered ${app.offerSalary.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})} per year. The choice is yours.`,type:'opportunity',priority:'major'});}else{app.status='rejected';app.lastUpdatedDate=date;events.push({id:`evt-post-interview-reject-${app.id}-${date}`,date,title:`No offer after the ${opening.title} interview`,body:'The process ended without an offer. Your application remains part of your career history.',type:'opportunity',priority:'medium'});}}}return events;}
function developSkills(world:WorldState,employment:Employment){const opening=world.jobOpenings.find(o=>o.title===employment.title&&o.employerId===employment.employerId);const names=opening?.requiredSkills??['Communication'];for(const name of names){const skill=world.skills.find(s=>s.personId===employment.personId&&s.name===name);if(!skill)continue;skill.experience+=1;skill.level=clamp(skill.level+.08+(employment.performance-50)/600);}}
function updatePerformance(world:WorldState,date:string){if(new Date(`${date}T12:00:00Z`).getUTCDay()!==1)return;for(const employment of world.employments.filter(e=>e.status==='active')){const person=employment.personId===world.character.id?world.character:world.npcs.find(n=>n.id===employment.personId);if(!person)continue;const energy=employment.personId===world.character.id?world.character.energy:65,stress=employment.personId===world.character.id?world.character.stress:person.human?.health.mentalLoad??35;const capability=(person.traits.discipline+person.traits.analytical+person.traits.confidence)/3,loadPenalty=Math.max(0,employment.hoursPerWeek-40)*.7;const observed=clamp(capability*.62+energy*.22+(100-stress)*.16-loadPenalty);employment.performance=clamp(employment.performance*.78+observed*.22);employment.satisfaction=clamp(employment.satisfaction+(person.traits.ambition>70&&employment.level==='entry'?-.35:.12)-(employment.hoursPerWeek>45?.25:0));developSkills(world,employment);if(employment.personId===world.character.id){world.character.stress=clamp(world.character.stress+Math.max(-.4,(employment.hoursPerWeek-40)/18));world.character.energy=clamp(world.character.energy-Math.max(0,(employment.hoursPerWeek-40)/25));}}}
function updateLaborMarket(world:WorldState,date:string,rng:SeededRng){if(Number(date.slice(-2))!==1)return;world.laborMarket.demandIndex=clamp(72-world.economy.unemploymentRate*3+(rng.next()-.5)*4,20,90);world.laborMarket.wageIndex=clamp(world.laborMarket.wageIndex*(1+world.economy.inflationRate/100/12*.45),.75,2);world.laborMarket.remoteShare=clamp(world.laborMarket.remoteShare+(rng.next()-.5)*.8,5,70);}
export function simulateCareer(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{initializeProgression(world);const events=processApplications(world,date);updatePerformance(world,date);processPayroll(world,date);updateLaborMarket(world,date,rng);const age=ageAt(world.character.birthDate,date);if(age>=18&&!activeEmployment(world)&&Number(date.slice(-2))===1){world.character.human.needs.security=clamp(world.character.human.needs.security-4);world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+2);events.push({id:`evt-unemployed-${date}`,date,title:'A month without employment passed',body:'Your schedule is more open, but income uncertainty is beginning to shape the rest of your life.',type:'finance',priority:'medium'});}return events;}
