import type { AthleticSet, Character, Household, Npc, Orientation, RelationshipState, RomanticProfile, Sex, TraitSet, WorldState } from '../types/game';
import { SeededRng } from './rng';
import { createHumanState, createNpcTraits } from './humanFactory';
import { initializeProgression } from './progressionSeed';

export interface CharacterDraft {
  firstName:string; lastName:string; age:number; sex:Sex; orientation?:Orientation; hometown:string;
  socioeconomicBackground:Character['socioeconomicBackground']; ambition:number; discipline:number; empathy:number; athleticism:number;
}
const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v)));
const rolePool=['Coworker','Neighbor','Classmate','Acquaintance','Community contact'] as const;
const femaleNames=['Avery','Elena','Imani','Leah','Maya','Riley','Sofia','Zoe','Nina'];
const maleNames=['Cameron','Darius','Jonah','Noah','Theo','Andre','Malik','Jordan'];
const lastNames=['Reed','Torres','Nguyen','Jackson','Patel','Miller','Brooks','Kim','Bennett','Flores','Hayes','Coleman','Price','Diaz','Foster','Wright'];
function datePartsNow(){const now=new Date();return{date:`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}-${String(now.getUTCDate()).padStart(2,'0')}`};}
function birthDateForAge(date:string,age:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()-age);return d.toISOString().slice(0,10);}
function romantic(traits:TraitSet,orientation:Orientation='straight'):RomanticProfile{return{orientation,relationshipStyle:'monogamous',wantsChildren:traits.familyOrientation>=72?'yes':traits.familyOrientation>=48?'maybe':'not_now'};}
function makeRelationship(fromId:string,toId:string,date:string,rng:SeededRng,closeness:number,attraction=0):RelationshipState{const centered=(spread:number)=>clamp(closeness+(rng.next()-.5)*spread);return{id:`rel-${fromId}-${toId}`,fromId,toId,affection:centered(18),respect:centered(16),attraction:clamp(attraction+(rng.next()-.5)*8),resentment:clamp(rng.next()*18*(1-closeness/120)),familiarity:centered(14),dependency:clamp(closeness*.32+rng.next()*12),trust:{emotional:centered(18),financial:centered(22),professional:centered(20),romantic:clamp(attraction*.4)},lastMeaningfulContactDate:date};}
function createNpc(id:string,name:string,role:string,age:number,sex:Sex,location:string,tier:1|2|3,date:string,rng:SeededRng,traitBias?:Partial<TraitSet>,orientation:Orientation='straight'):Npc{const traits=createNpcTraits(rng,traitBias);return{id,name,role,age,birthDate:birthDateForAge(date,age),sex,location,tier,traits,human:tier===3?null:createHumanState(id,traits,date,rng,{npc:true,fitness:clamp(45+rng.next()*30)}),romantic:romantic(traits,orientation),childDevelopment:null,currentFocus:tier===3?'background life':'settling into current priorities',lastSimulatedDate:date};}
function startingHousehold(character:Character,date:string,economy:WorldState['economy'],guardianId?:string):Household{const minor=ageAt(character.birthDate,date)<18,responsible=minor&&guardianId?guardianId:character.id,members=minor&&guardianId?[character.id,guardianId]:[character.id];return{id:`household-${character.id}-${date}`,name:`${character.lastName} household`,memberIds:members,location:character.location,homeType:'apartment',monthlyHousingCost:Math.round(1450*economy.housingIndex),responsibleAdultIds:[responsible],financeStyle:'separate',laborAssignments:[{id:`labor-meals-${responsible}`,task:'Meals',ownerId:responsible,cadence:'daily',burden:18},{id:`labor-cleaning-${responsible}`,task:'Cleaning',ownerId:responsible,cadence:'weekly',burden:16},{id:`labor-admin-${responsible}`,task:'Household admin',ownerId:responsible,cadence:'weekly',burden:14}],schedule:[{id:`schedule-${character.id}-weekday`,personId:character.id,label:minor?'School / study':'Work / primary responsibilities',dayOfWeek:1,startHour:minor?8:9,endHour:minor?15:17}],createdDate:date,endedDate:null};}
function ageAt(birthDate:string,date:string){const b=new Date(`${birthDate}T12:00:00Z`),d=new Date(`${date}T12:00:00Z`);let age=d.getUTCFullYear()-b.getUTCFullYear();const md=d.getUTCMonth()-b.getUTCMonth();if(md<0||(md===0&&d.getUTCDate()<b.getUTCDate()))age--;return age;}

export function createWorld(draft:CharacterDraft,seed=Math.floor(Math.random()*2_147_483_647)):WorldState{
  const{date}=datePartsNow(),rng=new SeededRng(seed),birthDate=birthDateForAge(date,draft.age);
  const traits:TraitSet={analytical:clamp(45+rng.next()*40),emotional:clamp(45+rng.next()*40),creativity:clamp(40+rng.next()*45),discipline:clamp(draft.discipline),ambition:clamp(draft.ambition),empathy:clamp(draft.empathy),confidence:clamp(45+rng.next()*40),patience:clamp(40+rng.next()*45),loyalty:clamp(50+rng.next()*40),impulsivity:clamp(25+rng.next()*50),riskTolerance:clamp(30+rng.next()*55),familyOrientation:clamp(45+rng.next()*45)};
  const a=clamp(draft.athleticism),athleticism:AthleticSet={speed:clamp(a+(rng.next()-.5)*18),strength:clamp(a+(rng.next()-.5)*18),endurance:clamp(a+(rng.next()-.5)*18),agility:clamp(a+(rng.next()-.5)*18),coordination:clamp(a+(rng.next()-.5)*18),reaction:clamp(a+(rng.next()-.5)*18)},startingCash={struggling:250,working:1800,stable:7500,affluent:35000,wealthy:150000}[draft.socioeconomicBackground];
  const human=createHumanState('player-1',traits,date,rng,{fitness:a,stress:25,energy:82});human.memories.push({id:'humanmem-player-beginning',ownerId:'player-1',date,kind:'identity',summary:`${draft.firstName.trim()} remembers this as the beginning of a new chapter in ${draft.hometown.trim()}.`,subjectIds:[],significance:92,emotionalValence:24,strength:100,confidence:100,privacy:'private'});
  const character:Character={id:'player-1',firstName:draft.firstName.trim(),lastName:draft.lastName.trim(),birthDate,sex:draft.sex,hometown:draft.hometown.trim(),socioeconomicBackground:draft.socioeconomicBackground,traits,athleticism,human,romantic:romantic(traits,draft.orientation??'straight'),cash:startingCash,career:draft.age<18?'Student':'Entry-level worker',location:draft.hometown.trim(),stress:25,energy:82};
  const opposite:Sex=draft.sex==='male'?'female':'male',friendName=opposite==='female'?'Maya Reed':'Marcus Reed';
  const npcs:Npc[]=[createNpc('npc-parent',`Jordan ${draft.lastName.trim()}`,'Parent',draft.age+27,draft.sex==='male'?'female':'male',draft.hometown.trim(),1,date,rng,{familyOrientation:86,loyalty:82,empathy:76}),createNpc('npc-friend',friendName,'Friend',Math.max(18,draft.age),opposite,draft.hometown.trim(),1,date,rng,{ambition:74,loyalty:70,empathy:65})];
  for(let i=0;i<6;i++){const sex:Sex=rng.chance(.5)?'female':'male',first=rng.pick(sex==='female'?femaleNames:maleNames);npcs.push(createNpc(`npc-active-${i+1}`,`${first} ${rng.pick(lastNames)}`,rng.pick(rolePool),Math.max(16,draft.age+Math.floor((rng.next()-.5)*14)),sex,draft.hometown.trim(),2,date,rng));}
  for(let i=0;i<24;i++){const sex:Sex=rng.chance(.5)?'female':'male',first=rng.pick(sex==='female'?femaleNames:maleNames);npcs.push(createNpc(`npc-background-${i+1}`,`${first} ${rng.pick(lastNames)}`,'Acquaintance',Math.max(16,draft.age+Math.floor((rng.next()-.5)*26)),sex,draft.hometown.trim(),3,date,rng));}
  const relationships:RelationshipState[]=[];for(const npc of npcs){const closeness=npc.role==='Parent'?82:npc.role==='Friend'?68:npc.tier===2?26+rng.next()*20:4+rng.next()*15,eligible=draft.age>=18&&npc.age>=18&&npc.sex!==character.sex&&character.romantic.orientation!=='gay'&&npc.romantic.orientation!=='gay',latent=eligible&&npc.role==='Friend'?42:0;relationships.push(makeRelationship(npc.id,character.id,date,rng,closeness,latent),makeRelationship(character.id,npc.id,date,rng,closeness-2+rng.next()*4,latent));}
  for(let i=2;i<Math.min(8,npcs.length-1);i+=2)relationships.push(makeRelationship(npcs[i]!.id,npcs[i+1]!.id,date,rng,38+rng.next()*18),makeRelationship(npcs[i+1]!.id,npcs[i]!.id,date,rng,36+rng.next()*18));
  const economy={unemploymentRate:4.4,inflationRate:2.7,baseInterestRate:4.5,housingIndex:1};const world:WorldState={version:4,seed,date,character,npcs,relationships,partnerships:[],households:[],pregnancies:[],familyLinks:[{id:`family-${npcs[0]!.id}-${character.id}-parent`,fromId:npcs[0]!.id,toId:character.id,relation:'biological_parent',establishedDate:date,endedDate:null},{id:`family-${character.id}-${npcs[0]!.id}-child`,fromId:character.id,toId:npcs[0]!.id,relation:'biological_child',establishedDate:date,endedDate:null}],custodyPlans:[],conversations:[],educationInstitutions:[],educationEnrollments:[],credentials:[],skills:[],employers:[],employments:[],jobOpenings:[],jobApplications:[],laborMarket:{wageIndex:1,demandIndex:64,remoteShare:28},knowledge:[{id:'know-parent-location',holderId:character.id,subjectId:'npc-parent',factKey:'location',summary:`Jordan lives in ${draft.hometown.trim()}.`,confidence:100,privacy:'personal',sourceId:'npc-parent',sourceType:'direct',acquiredDate:date,distortion:0},{id:'know-friend-career',holderId:character.id,subjectId:'npc-friend',factKey:'career-focus',summary:`${friendName.split(' ')[0]} has been focused on building a career.`,confidence:92,privacy:'personal',sourceId:'npc-friend',sourceType:'told',acquiredDate:date,distortion:0}],secrets:[],npcActivity:[],ledger:[],events:[{id:'evt-start',date,title:'A new life begins',body:'The world was generated from your starting circumstances. From here, it will continue moving whether or not events go your way.',type:'world',priority:'major'}],memories:[{id:'mem-start',date,title:'The beginning',summary:`At age ${draft.age}, ${draft.firstName} begins this chapter of life in ${draft.hometown}.`,significance:100}],economy};world.households.push(startingHousehold(character,date,economy,draft.age<18?npcs[0]!.id:undefined));const friend=npcs.find(n=>n.id==='npc-friend');if(friend)world.secrets.push({id:`secret-${friend.id}-career-move`,subjectId:friend.id,category:'career',summary:`${friend.name} has quietly been considering an opportunity that could eventually take them to another city.`,sensitivity:44,createdDate:date,knownBy:[{personId:friend.id,since:date,sourceId:friend.id}],status:'active'});return initializeProgression(world);
}
