import type { AthleticSet, Character, FamilyLink, Household, KnowledgeFact, Npc, Orientation, RelationshipState, RomanticProfile, Sex, TraitSet, WorldState } from '../types/game';
import type { AccessibilitySettings, GameMode, ScenarioId, SeriousContentSettings } from '../types/gameplay';
import { SeededRng } from './rng';
import { createHumanState, createNpcTraits } from './humanFactory';
import { initializeProgression } from './progressionSeed';
import { initializeFinance } from './financeSeed';
import { initializeSports } from './sportsSeed';
import { initializeBusinessWorld } from './businessEngine';
import { initializeHealth } from './healthSeed';
import { initializeNarration } from '../narration/narrationEngine';
import { emptyLifestyleState, initializeLifestyle } from './lifestyleSeed';
import { emptyLivingWorldState, initializeLivingWorld } from './livingWorldSeed';
import { configurationForMode } from './gameConfig';

export type StartingFamilyStructure='two_parent'|'single_parent'|'guardian'|'independent';
export interface CharacterDraft{
  firstName:string;lastName:string;age:number;sex:Sex;orientation?:Orientation;hometown:string;socioeconomicBackground:Character['socioeconomicBackground'];
  ambition:number;discipline:number;empathy:number;athleticism:number;
  analytical?:number;emotional?:number;creativity?:number;confidence?:number;patience?:number;loyalty?:number;impulsivity?:number;riskTolerance?:number;familyOrientation?:number;
  athleticSpeed?:number;athleticStrength?:number;athleticEndurance?:number;athleticAgility?:number;athleticCoordination?:number;athleticReaction?:number;
  familyStructure?:StartingFamilyStructure;siblingCount?:number;parentCloseness?:number;
  gameMode?:GameMode;scenarioId?:ScenarioId;accessibility?:AccessibilitySettings;seriousContent?:SeriousContentSettings;
}
const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v)));
const rolePool=['Coworker','Neighbor','Classmate','Acquaintance','Community contact'] as const;
const femaleNames=['Avery','Elena','Imani','Leah','Maya','Riley','Sofia','Zoe','Nina'];
const maleNames=['Cameron','Darius','Jonah','Noah','Theo','Andre','Malik','Jordan'];
const lastNames=['Reed','Torres','Nguyen','Jackson','Patel','Miller','Brooks','Kim','Bennett','Flores','Hayes','Coleman','Price','Diaz','Foster','Wright'];
function datePartsNow(){const now=new Date();return{date:`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}-${String(now.getUTCDate()).padStart(2,'0')}`};}
function birthDateForAge(date:string,age:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()-age);return d.toISOString().slice(0,10);}
function romantic(traits:TraitSet,orientation:Orientation='straight'):RomanticProfile{return{orientation,relationshipStyle:'monogamous',wantsChildren:traits.familyOrientation>=72?'yes':traits.familyOrientation>=48?'maybe':'not_now'};}
function makeRelationship(fromId:string,toId:string,date:string,rng:SeededRng,closeness:number,attraction=0):RelationshipState{const centered=(spread:number)=>clamp(closeness+(rng.next()-.5)*spread);return{id:`rel-${fromId}-${toId}`,fromId,toId,affection:centered(18),respect:centered(16),attraction:clamp(attraction+(rng.next()-.5)*8),resentment:clamp(rng.next()*18*(1-closeness/120)),familiarity:centered(14),dependency:clamp(closeness*.32+rng.next()*12),trust:{emotional:centered(18),financial:centered(22),professional:centered(20),romantic:clamp(attraction*.4)},lastMeaningfulContactDate:date};}
function createNpc(id:string,name:string,role:string,age:number,sex:Sex,location:string,tier:1|2|3,date:string,rng:SeededRng,traitBias?:Partial<TraitSet>,orientation:Orientation='straight'):Npc{const traits=createNpcTraits(rng,traitBias);return{id,name,role,age,birthDate:birthDateForAge(date,age),sex,location,tier,traits,human:tier===3?null:createHumanState(id,traits,date,rng,{npc:true,fitness:clamp(45+rng.next()*30)}),romantic:romantic(traits,orientation),childDevelopment:null,currentFocus:tier===3?'background life':'settling into current priorities',lastSimulatedDate:date};}
function ageAt(birthDate:string,date:string){const b=new Date(`${birthDate}T12:00:00Z`),d=new Date(`${date}T12:00:00Z`);let age=d.getUTCFullYear()-b.getUTCFullYear();const md=d.getUTCMonth()-b.getUTCMonth();if(md<0||(md===0&&d.getUTCDate()<b.getUTCDate()))age--;return age;}
function startingHousehold(character:Character,date:string,economy:WorldState['economy'],residentFamily:Npc[]):Household{const minor=ageAt(character.birthDate,date)<18,adults=residentFamily.filter(n=>n.age>=18),responsible=minor?(adults[0]?.id??character.id):character.id,members=minor?[character.id,...residentFamily.map(n=>n.id)]:[character.id];return{id:`household-${character.id}-${date}`,name:`${character.lastName} household`,memberIds:members,location:character.location,homeType:'apartment',monthlyHousingCost:Math.round(1450*economy.housingIndex),responsibleAdultIds:minor?adults.map(n=>n.id):[character.id],financeStyle:'separate',laborAssignments:[{id:`labor-meals-${responsible}`,task:'Meals',ownerId:responsible,cadence:'daily',burden:18},{id:`labor-cleaning-${responsible}`,task:'Cleaning',ownerId:responsible,cadence:'weekly',burden:16},{id:`labor-admin-${responsible}`,task:'Household admin',ownerId:responsible,cadence:'weekly',burden:14}],schedule:[{id:`schedule-${character.id}-weekday`,personId:character.id,label:minor?'School / study':'Work / primary responsibilities',dayOfWeek:1,startHour:minor?8:9,endHour:minor?15:17}],createdDate:date,endedDate:null};}
function familyLinksFor(characterId:string,family:Npc[],date:string):FamilyLink[]{const links:FamilyLink[]=[];for(const npc of family){if(npc.role==='Parent'||npc.role==='Guardian'){if(npc.role==='Parent')links.push({id:`family-${npc.id}-${characterId}-parent`,fromId:npc.id,toId:characterId,relation:'biological_parent',establishedDate:date,endedDate:null},{id:`family-${characterId}-${npc.id}-child`,fromId:characterId,toId:npc.id,relation:'biological_child',establishedDate:date,endedDate:null});}else if(npc.role==='Sibling')links.push({id:`family-${npc.id}-${characterId}-sibling`,fromId:npc.id,toId:characterId,relation:'sibling',establishedDate:date,endedDate:null},{id:`family-${characterId}-${npc.id}-sibling`,fromId:characterId,toId:npc.id,relation:'sibling',establishedDate:date,endedDate:null});}return links;}
function createStartingFamily(draft:CharacterDraft,date:string,rng:SeededRng):Npc[]{const structure=draft.familyStructure??'single_parent',family:Npc[]=[];if(structure!=='independent'){const role=structure==='guardian'?'Guardian':'Parent',sex:Sex=draft.sex==='male'?'female':'male';family.push(createNpc('npc-parent',`Jordan ${draft.lastName.trim()}`,role,draft.age+27,sex,draft.hometown.trim(),1,date,rng,{familyOrientation:86,loyalty:82,empathy:76}));if(structure==='two_parent')family.push(createNpc('npc-parent-2',`Taylor ${draft.lastName.trim()}`,'Parent',draft.age+29,draft.sex,draft.hometown.trim(),1,date,rng,{familyOrientation:78,loyalty:76,discipline:68}));}
  const siblings=Math.max(0,Math.min(4,Math.round(draft.siblingCount??0)));for(let i=0;i<siblings;i++){const sex:Sex=rng.chance(.5)?'female':'male',first=rng.pick(sex==='female'?femaleNames:maleNames),age=Math.max(1,draft.age+Math.round((rng.next()-.5)*10));family.push(createNpc(`npc-sibling-${i+1}`,`${first} ${draft.lastName.trim()}`,'Sibling',age,sex,draft.hometown.trim(),1,date,rng,{familyOrientation:70,loyalty:70}));}return family;}
function applyScenarioStart(world:WorldState){const cfg=world.gameConfiguration;if(cfg.mode==='scenario'&&cfg.scenarioId==='career_rebuild'){for(const e of world.employments.filter(e=>e.personId===world.character.id&&e.status==='active')){e.status='ended';e.endDate=world.date;}world.character.career='Unemployed';world.events.unshift({id:`evt-scenario-career-rebuild-${world.date}`,date:world.date,title:'A career chapter ended',body:'You begin this scenario between jobs. Your experience remains, but the next role is not guaranteed.',type:'world',priority:'major'});}if(cfg.mode==='legacy'||(cfg.mode==='scenario'&&cfg.scenarioId==='legacy_seed')){if(!world.character.human.goals.some(g=>g.title==='Build a lasting family legacy'))world.character.human.goals.push({id:`goal-${world.character.id}-legacy`,ownerId:world.character.id,domain:'family',title:'Build a lasting family legacy',priority:82,progress:0,status:'active',createdDate:world.date,lastEvaluatedDate:world.date,private:false});}return world;}

export function createWorld(draft:CharacterDraft,seed=Math.floor(Math.random()*2_147_483_647)):WorldState{
  const{date}=datePartsNow(),rng=new SeededRng(seed),birthDate=birthDateForAge(date,draft.age),gameConfiguration=configurationForMode(draft.gameMode??'life',draft.scenarioId??'none',draft.accessibility,draft.seriousContent);
  const traits:TraitSet={analytical:clamp(draft.analytical??45+rng.next()*40),emotional:clamp(draft.emotional??45+rng.next()*40),creativity:clamp(draft.creativity??40+rng.next()*45),discipline:clamp(draft.discipline),ambition:clamp(draft.ambition),empathy:clamp(draft.empathy),confidence:clamp(draft.confidence??45+rng.next()*40),patience:clamp(draft.patience??40+rng.next()*45),loyalty:clamp(draft.loyalty??50+rng.next()*40),impulsivity:clamp(draft.impulsivity??25+rng.next()*50),riskTolerance:clamp(draft.riskTolerance??30+rng.next()*55),familyOrientation:clamp(draft.familyOrientation??45+rng.next()*45)};
  const a=clamp(draft.athleticism),athleticism:AthleticSet={speed:clamp(draft.athleticSpeed??a+(rng.next()-.5)*18),strength:clamp(draft.athleticStrength??a+(rng.next()-.5)*18),endurance:clamp(draft.athleticEndurance??a+(rng.next()-.5)*18),agility:clamp(draft.athleticAgility??a+(rng.next()-.5)*18),coordination:clamp(draft.athleticCoordination??a+(rng.next()-.5)*18),reaction:clamp(draft.athleticReaction??a+(rng.next()-.5)*18)},baseStartingCash={struggling:250,working:1800,stable:7500,affluent:35000,wealthy:150000}[draft.socioeconomicBackground],startingCash=Math.round(baseStartingCash*gameConfiguration.rules.startingCashMultiplier);
  const human=createHumanState('player-1',traits,date,rng,{fitness:a,stress:25,energy:82});human.memories.push({id:'humanmem-player-beginning',ownerId:'player-1',date,kind:'identity',summary:`${draft.firstName.trim()} remembers this as the beginning of a new chapter in ${draft.hometown.trim()}.`,subjectIds:[],significance:92,emotionalValence:24,strength:100,confidence:100,privacy:'private'});
  const character:Character={id:'player-1',firstName:draft.firstName.trim(),lastName:draft.lastName.trim(),birthDate,sex:draft.sex,hometown:draft.hometown.trim(),socioeconomicBackground:draft.socioeconomicBackground,traits,athleticism,human,romantic:romantic(traits,draft.orientation??'straight'),cash:startingCash,career:draft.age<18?'Student':'Entry-level worker',location:draft.hometown.trim(),stress:25,energy:82};
  const family=createStartingFamily(draft,date,rng),opposite:Sex=draft.sex==='male'?'female':'male',friendName=opposite==='female'?'Maya Reed':'Marcus Reed',npcs:Npc[]=[...family,createNpc('npc-friend',friendName,'Friend',Math.max(18,draft.age),opposite,draft.hometown.trim(),1,date,rng,{ambition:74,loyalty:70,empathy:65})];
  for(let i=0;i<6;i++){const sex:Sex=rng.chance(.5)?'female':'male',first=rng.pick(sex==='female'?femaleNames:maleNames);npcs.push(createNpc(`npc-active-${i+1}`,`${first} ${rng.pick(lastNames)}`,rng.pick(rolePool),Math.max(16,draft.age+Math.floor((rng.next()-.5)*14)),sex,draft.hometown.trim(),2,date,rng));}
  for(let i=0;i<24;i++){const sex:Sex=rng.chance(.5)?'female':'male',first=rng.pick(sex==='female'?femaleNames:maleNames);npcs.push(createNpc(`npc-background-${i+1}`,`${first} ${rng.pick(lastNames)}`,'Acquaintance',Math.max(16,draft.age+Math.floor((rng.next()-.5)*26)),sex,draft.hometown.trim(),3,date,rng));}
  const relationships:RelationshipState[]=[];for(const npc of npcs){const parentLike=npc.role==='Parent'||npc.role==='Guardian',closeness=parentLike?clamp(draft.parentCloseness??82):npc.role==='Sibling'?62+rng.next()*18:npc.role==='Friend'?68:npc.tier===2?26+rng.next()*20:4+rng.next()*15,eligible=draft.age>=18&&npc.age>=18&&npc.sex!==character.sex&&character.romantic.orientation!=='gay'&&npc.romantic.orientation!=='gay',latent=eligible&&npc.role==='Friend'?42:0;relationships.push(makeRelationship(npc.id,character.id,date,rng,closeness,latent),makeRelationship(character.id,npc.id,date,rng,closeness-2+rng.next()*4,latent));}
  for(let i=Math.max(2,family.length+1);i<Math.min(family.length+8,npcs.length-1);i+=2)relationships.push(makeRelationship(npcs[i]!.id,npcs[i+1]!.id,date,rng,38+rng.next()*18),makeRelationship(npcs[i+1]!.id,npcs[i]!.id,date,rng,36+rng.next()*18));
  const economy={unemploymentRate:4.4,inflationRate:2.7,baseInterestRate:4.5,housingIndex:1};
  const knowledge:KnowledgeFact[]=[...family.filter(n=>n.role==='Parent'||n.role==='Guardian').slice(0,1).map(n=>({id:'know-parent-location',holderId:character.id,subjectId:n.id,factKey:'location',summary:`${n.name.split(' ')[0]} lives in ${draft.hometown.trim()}.`,confidence:100,privacy:'personal' as const,sourceId:n.id,sourceType:'direct' as const,acquiredDate:date,distortion:0})),{id:'know-friend-career',holderId:character.id,subjectId:'npc-friend',factKey:'career-focus',summary:`${friendName.split(' ')[0]} has been focused on building a career.`,confidence:92,privacy:'personal',sourceId:'npc-friend',sourceType:'told',acquiredDate:date,distortion:0}];
  const world:WorldState={version:12,seed,date,character,npcs,relationships,partnerships:[],households:[],pregnancies:[],familyLinks:familyLinksFor(character.id,family,date),custodyPlans:[],conversations:[],educationInstitutions:[],educationEnrollments:[],credentials:[],skills:[],employers:[],employments:[],jobOpenings:[],jobApplications:[],laborMarket:{wageIndex:1,demandIndex:64,remoteShare:28},knowledge,secrets:[],npcActivity:[],ledger:[],events:[{id:'evt-start',date,title:'A new life begins',body:`${gameConfiguration.mode==='hard'?'Hard Life rules are active. ':gameConfiguration.mode==='sandbox'?'Sandbox rules are active. ':gameConfiguration.mode==='legacy'?'Legacy Mode is active. ':''}The world was generated from your starting circumstances. From here, it will continue moving whether or not events go your way.`,type:'world',priority:'major'}],memories:[{id:'mem-start',date,title:'The beginning',summary:`At age ${draft.age}, ${draft.firstName} begins this chapter of life in ${draft.hometown}.`,significance:100}],economy,financialAccounts:[],recurringObligations:[],budgetRules:[],householdFinancePlans:[],creditProfiles:[],liabilities:[],insurancePolicies:[],properties:[],vehicles:[],investmentPositions:[],bankruptcyRecords:[],market:{usEquityIndex:100,internationalEquityIndex:100,bondIndex:100,volatility:18,regime:'neutral',lastUpdatedDate:date},sportsLeagues:[],sportsTeams:[],sportsParticipants:[],athleteProfiles:[],coachProfiles:[],sportsContracts:[],sportsFixtures:[],sportsSeasonStats:[],businesses:[],warehouseFacilities:[],businessEmployees:[],logisticsContracts:[],logisticsKpis:[],businessOpportunities:[],narrationSettings:{mode:'offline',preferredProvider:'evera-offline',allowRemoteNarration:false},annualLifeChapters:[],healthProfiles:[],medicalConditions:[],medicalEncounters:[],medicalBills:[],medications:[],deathRecords:[],funeralRecords:[],estatePlans:[],estateCases:[],ancestorArchives:[],controlTransitions:[],crimeIncidents:[],criminalCases:[],criminalRecords:[],incarcerationRecords:[],civilCases:[],...emptyLifestyleState(),...emptyLivingWorldState(),gameConfiguration};
  const residentFamily=draft.age<18?family:[];world.households.push(startingHousehold(character,date,economy,residentFamily));
  const friend=npcs.find(n=>n.id==='npc-friend');if(friend)world.secrets.push({id:`secret-${friend.id}-career-move`,subjectId:friend.id,category:'career',summary:`${friend.name} has quietly been considering an opportunity that could eventually take them to another city.`,sensitivity:44,createdDate:date,knownBy:[{personId:friend.id,since:date,sourceId:friend.id}],status:'active'});
  return applyScenarioStart(initializeLivingWorld(initializeLifestyle(initializeNarration(initializeHealth(initializeBusinessWorld(initializeSports(initializeFinance(initializeProgression(world)))))))));
}
