import type { Credential, EducationEnrollment, LifeEvent, WorldState } from '../types/game';
import { SeededRng } from './rng';
import { ageAt } from './familyEngine';
import { deriveSeed } from './humanEngine';
import { initializeProgression, syncPrimarySchedule } from './progressionSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addYears=(date:string,years:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString().slice(0,10);};
function personTraits(world:WorldState,id:string){return id===world.character.id?world.character.traits:world.npcs.find(n=>n.id===id)?.traits??null;}
function personEnergy(world:WorldState,id:string){if(id===world.character.id)return world.character.energy;return 65;}
function personStress(world:WorldState,id:string){if(id===world.character.id)return world.character.stress;return world.npcs.find(n=>n.id===id)?.human?.health.mentalLoad??35;}
function levelForInstitution(kind:WorldState['educationInstitutions'][number]['kind']){return kind==='university'?'bachelor' as const:kind==='trade_school'?'trade' as const:'secondary' as const;}
function creditsRequired(level:EducationEnrollment['level']){return level==='bachelor'?120:level==='trade'||level==='certificate'?36:level==='associate'?60:level==='graduate'?36:120;}
function yearsFor(level:EducationEnrollment['level']){return level==='bachelor'?4:level==='associate'?2:level==='trade'||level==='certificate'?1:level==='graduate'?2:4;}
function credentialFromEnrollment(e:EducationEnrollment):Credential['level']{if(e.level==='bachelor')return'bachelor';if(e.level==='associate')return'associate';if(e.level==='graduate')return'graduate';if(e.level==='trade'||e.level==='certificate')return'certificate';return'high_school';}
function addEvent(world:WorldState,event:LifeEvent){world.events=[event,...world.events].slice(0,120);}
export function activeEnrollment(world:WorldState,personId=world.character.id){return world.educationEnrollments.find(e=>e.personId===personId&&e.status==='active');}
export function startEducation(input:WorldState,institutionId:string,program:string):WorldState{const world=initializeProgression(structuredClone(input)),institution=world.educationInstitutions.find(i=>i.id===institutionId);if(!institution||!institution.programs.includes(program)||activeEnrollment(world))return world;const player=world.character,age=ageAt(player.birthDate,world.date);if(age<16&&institution.kind!=='public_school'&&institution.kind!=='charter_school'&&institution.kind!=='private_school')return world;const traits=player.traits,admission=clamp(traits.analytical*.34+traits.discipline*.32+traits.ambition*.18+traits.confidence*.16);const rng=new SeededRng(deriveSeed(world.seed,`admission:${institutionId}:${program}:${world.date}`));const accepted=institution.selectivity===0||admission+rng.next()*24>=institution.selectivity;if(!accepted){addEvent(world,{id:`evt-admission-reject-${institutionId}-${world.date}`,date:world.date,title:`${institution.name} did not admit you`,body:'Your application was considered, but this attempt did not result in admission.',type:'opportunity',priority:'medium'});return world;}const level=levelForInstitution(institution.kind),needScholarship=player.socioeconomicBackground==='struggling'||player.socioeconomicBackground==='working',merit=traits.analytical+traits.discipline>=145;const aidRate=needScholarship ? 0.45 : merit ? 0.25 : 0;const scholarshipAnnual=Math.round(institution.tuitionAnnual*aidRate);const enrollment:EducationEnrollment={id:`enrollment-${player.id}-${institution.id}-${world.date}`,personId:player.id,institutionId:institution.id,program,level,status:'active',startDate:world.date,expectedEndDate:addYears(world.date,yearsFor(level)),gpa:3,attendance:95,creditsEarned:0,creditsRequired:creditsRequired(level),scholarshipAnnual,studentDebt:0};world.educationEnrollments.push(enrollment);syncPrimarySchedule(world,player.id,`${institution.name} · ${program}`,[1,2,3,4,5],level==='trade'?8:9,level==='trade'?15:16);addEvent(world,{id:`evt-enrolled-${enrollment.id}`,date:world.date,title:`You enrolled at ${institution.name}`,body:`You started ${program}. Tuition, time, academic performance and work now compete for the same finite resources.`,type:'opportunity',priority:'major'});return world;}
export function withdrawEducation(input:WorldState,enrollmentId:string):WorldState{const world=structuredClone(input),enrollment=world.educationEnrollments.find(e=>e.id===enrollmentId&&e.personId===world.character.id&&e.status==='active');if(!enrollment)return world;enrollment.status='withdrawn';addEvent(world,{id:`evt-withdraw-${enrollment.id}-${world.date}`,date:world.date,title:'You left your program',body:'The credits and debt already accumulated remain part of your history, even though the enrollment ended.',type:'opportunity',priority:'medium'});return world;}
function graduate(world:WorldState,enrollment:EducationEnrollment,date:string):LifeEvent{enrollment.status='graduated';const institution=world.educationInstitutions.find(i=>i.id===enrollment.institutionId)!;const credential:Credential={id:`credential-${enrollment.id}`,personId:enrollment.personId,institutionId:institution.id,name:enrollment.level==='secondary'?'High School Diploma':`${enrollment.program} ${enrollment.level==='trade'?'Certificate':enrollment.level.charAt(0).toUpperCase()+enrollment.level.slice(1)}`,field:enrollment.program,level:credentialFromEnrollment(enrollment),dateEarned:date};if(!world.credentials.some(c=>c.id===credential.id))world.credentials.push(credential);if(enrollment.personId===world.character.id)world.memories.unshift({id:`mem-graduation-${credential.id}`,date,title:`Completed ${enrollment.program}`,summary:`You completed your program at ${institution.name}.`,significance:90});return{id:`evt-graduation-${credential.id}`,date,title:`${enrollment.personId===world.character.id?'You':'Someone'} completed a program`,body:`${institution.name} awarded a ${credential.name}.`,type:'opportunity',priority:'major'};}
export function simulateEducation(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{const events:LifeEvent[]=[];initializeProgression(world);for(const child of world.npcs.filter(n=>n.role==='Child'&&n.age>=5&&n.age<18)){if(!world.educationEnrollments.some(e=>e.personId===child.id&&e.status==='active')&&!world.credentials.some(c=>c.personId===child.id&&c.level==='high_school'))world.educationEnrollments.push({id:`enrollment-${child.id}-school-${date}`,personId:child.id,institutionId:'edu-public',program:'General Studies',level:child.age<14?'primary':'secondary',status:'active',startDate:date,expectedEndDate:addYears(date,18-child.age),gpa:3,attendance:94,creditsEarned:Math.max(0,(child.age-14)*30),creditsRequired:120,scholarshipAnnual:0,studentDebt:0});}if(Number(date.slice(-2))!==1)return events;for(const enrollment of world.educationEnrollments.filter(e=>e.status==='active')){const traits=personTraits(world,enrollment.personId);if(!traits)continue;const energy=personEnergy(world,enrollment.personId),stress=personStress(world,enrollment.personId),performance=clamp(traits.analytical*.32+traits.discipline*.34+energy*.2+(100-stress)*.14);const noise=(rng.next()-.5)*.22;enrollment.gpa=clamp(enrollment.gpa*.7+(performance/25)*.3+noise,0,4);enrollment.attendance=clamp(enrollment.attendance+(traits.discipline-50)/35+(rng.next()-.5)*3);const monthlyCredits=enrollment.level==='primary'?2.5:enrollment.level==='secondary'?2.8:2.5+(performance/100)*1.2;enrollment.creditsEarned=Math.min(enrollment.creditsRequired,enrollment.creditsEarned+monthlyCredits);if(enrollment.personId===world.character.id){const institution=world.educationInstitutions.find(i=>i.id===enrollment.institutionId);if(institution&&institution.tuitionAnnual>0){const netAnnual=Math.max(0,institution.tuitionAnnual-enrollment.scholarshipAnnual),monthly=Math.round(netAnnual/12);if(monthly>0){const cashPayment=Math.min(monthly,Math.max(0,Math.round(world.character.cash*.08)));if(cashPayment>0){world.character.cash-=cashPayment;world.ledger.unshift({id:`tuition-${enrollment.id}-${date}`,date,description:`Tuition · ${institution.name}`,amount:-cashPayment,category:'Education'});}enrollment.studentDebt+=monthly-cashPayment;}}world.character.human.needs.purpose=clamp(world.character.human.needs.purpose+.4);const academicLoad=(enrollment.level==='bachelor'||enrollment.level==='graduate') ? 0.45 : 0.2;world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+academicLoad);}if(enrollment.creditsEarned>=enrollment.creditsRequired)events.push(graduate(world,enrollment,date));}return events;}
