import type { ChildDevelopmentState, FamilyLink, LifeEvent, Npc, Partnership, RelationshipState, Sex, TraitSet, WorldState } from '../types/game';
import { SeededRng } from './rng';
import { createHumanState } from './humanFactory';
import { deriveSeed } from './humanEngine';
import { activeHouseholdForPerson } from './householdEngine';

const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const addDays=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const daysBetween=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/86_400_000);
export const ageAt=(birthDate:string,date:string)=>{const b=new Date(`${birthDate}T12:00:00Z`),d=new Date(`${date}T12:00:00Z`);let age=d.getUTCFullYear()-b.getUTCFullYear();const md=d.getUTCMonth()-b.getUTCMonth();if(md<0||(md===0&&d.getUTCDate()<b.getUTCDate()))age--;return age;};
function person(world:WorldState,id:string){return id===world.character.id?world.character:world.npcs.find(n=>n.id===id)??null;}
function traits(world:WorldState,id:string){return person(world,id)?.traits??null;}
function sex(world:WorldState,id:string){return person(world,id)?.sex??null;}
function birthDate(world:WorldState,id:string){return person(world,id)?.birthDate??null;}
function activePartnerships(world:WorldState){return world.partnerships.filter(p=>!['ended','divorced','separated'].includes(p.status));}
function hasOngoingPregnancy(world:WorldState,p:Partnership){return world.pregnancies.some(x=>x.status==='ongoing'&&p.personIds.includes(x.pregnantPersonId)&&(x.partnerId?p.personIds.includes(x.partnerId):true));}
function childStage(age:number):ChildDevelopmentState['stage']{if(age<2)return'infant';if(age<5)return'toddler';if(age<10)return'child';if(age<13)return'preteen';if(age<18)return'teen';return'young_adult';}
function makeChildDevelopment():ChildDevelopmentState{return{stage:'infant',attachmentSecurity:68,independence:6,schoolEngagement:50,confidence:55,behaviorRegulation:35,lastParentingDate:null};}
function inherit(a:TraitSet,b:TraitSet,rng:SeededRng):TraitSet{const mix=(x:number,y:number)=>clamp((x+y)/2+(rng.next()-.5)*24);return{analytical:mix(a.analytical,b.analytical),emotional:mix(a.emotional,b.emotional),creativity:mix(a.creativity,b.creativity),discipline:mix(a.discipline,b.discipline),ambition:mix(a.ambition,b.ambition),empathy:mix(a.empathy,b.empathy),confidence:mix(a.confidence,b.confidence),patience:mix(a.patience,b.patience),loyalty:mix(a.loyalty,b.loyalty),impulsivity:mix(a.impulsivity,b.impulsivity),riskTolerance:mix(a.riskTolerance,b.riskTolerance),familyOrientation:mix(a.familyOrientation,b.familyOrientation)};}
function addRelationship(world:WorldState,from:string,to:string,date:string,parentToChild:boolean){if(world.relationships.some(r=>r.fromId===from&&r.toId===to))return;const rel:RelationshipState={id:`rel-${from}-${to}`,fromId:from,toId:to,affection:parentToChild?82:72,respect:parentToChild?70:64,attraction:0,resentment:0,familiarity:parentToChild?62:54,dependency:parentToChild?42:82,trust:{emotional:78,financial:50,professional:50,romantic:0},lastMeaningfulContactDate:date};world.relationships.push(rel);}
function addFamilyLink(world:WorldState,link:FamilyLink){if(!world.familyLinks.some(f=>f.fromId===link.fromId&&f.toId===link.toId&&f.relation===link.relation&&!f.endedDate))world.familyLinks.push(link);}
function newbornName(world:WorldState,childSex:Sex,rng:SeededRng){const girls=['Ari','Mila','Nora','Lena','Ivy','Maya','Zoe','Elena'];const boys=['Eli','Miles','Noah','Theo','Kai','Leo','Jonah','Andre'];return`${rng.pick(childSex==='female'?girls:boys)} ${world.character.lastName}`;}
function createBirth(world:WorldState,pregnancyId:string,date:string,rng:SeededRng):LifeEvent|null{const pregnancy=world.pregnancies.find(p=>p.id===pregnancyId&&p.status==='ongoing');if(!pregnancy)return null;const other=pregnancy.partnerId;const a=traits(world,pregnancy.pregnantPersonId),b=other?traits(world,other):a;if(!a||!b)return null;const childSex:Sex=rng.chance(.5)?'female':'male',childTraits=inherit(a,b,rng),id=`npc-child-${date}-${world.npcs.filter(n=>n.role==='Child').length+1}`;const child:Npc={id,name:newbornName(world,childSex,rng),role:'Child',age:0,birthDate:date,sex:childSex,location:person(world,pregnancy.pregnantPersonId)?.location??world.character.location,tier:1,traits:childTraits,human:createHumanState(id,childTraits,date,rng,{npc:true,fitness:55,stress:4,energy:70}),romantic:{orientation:'straight',relationshipStyle:'monogamous',wantsChildren:'not_now'},childDevelopment:makeChildDevelopment(),currentFocus:'early development',lastSimulatedDate:date};world.npcs.push(child);pregnancy.status='birth';pregnancy.outcomeDate=date;pregnancy.childIds.push(id);const parents=[pregnancy.pregnantPersonId,...(other?[other]:[])];for(const parentId of parents){addFamilyLink(world,{id:`family-${parentId}-${id}-parent-${date}`,fromId:parentId,toId:id,relation:'biological_parent',establishedDate:date,endedDate:null});addFamilyLink(world,{id:`family-${id}-${parentId}-child-${date}`,fromId:id,toId:parentId,relation:'biological_child',establishedDate:date,endedDate:null});addRelationship(world,parentId,id,date,true);addRelationship(world,id,parentId,date,false);}const home=activeHouseholdForPerson(world,pregnancy.pregnantPersonId)??(other?activeHouseholdForPerson(world,other):undefined);if(home&&!home.memberIds.includes(id)){home.memberIds.push(id);home.schedule.push({id:`schedule-${id}-care`,personId:id,label:'Care / home routine',dayOfWeek:1,startHour:7,endHour:19});}const partnership=other?world.partnerships.find(p=>p.personIds.includes(pregnancy.pregnantPersonId)&&p.personIds.includes(other)&&!['ended','divorced'].includes(p.status)):undefined;if(partnership)partnership.history.push({id:`hist-${partnership.id}-child-${date}`,date,kind:'child_born',summary:`${child.name} was born.`});world.memories.unshift({id:`mem-birth-${id}`,date,title:`${child.name} was born`,summary:'A new child joined the family.',significance:100});return{id:`evt-birth-${id}`,date,title:`${child.name} was born`,body:'The birth permanently changes the household, finances, schedules and family network.',type:'relationship',priority:'major'};}
function maybePregnancyLoss(world:WorldState,date:string):LifeEvent[]{if(world.gameConfiguration?.seriousContent.allowPregnancyLoss===false)return[];if(new Date(`${date}T12:00:00Z`).getUTCDay()!==0)return[];const events:LifeEvent[]=[];for(const pregnancy of world.pregnancies.filter(p=>p.status==='ongoing'&&p.dueDate>date)){const gestationDays=daysBetween(pregnancy.conceptionDate,date);if(gestationDays<7||gestationDays>140)continue;const pregnant=person(world,pregnancy.pregnantPersonId),age=pregnant?ageAt(pregnant.birthDate,date):30,base=gestationDays<=84?.012:.003,ageFactor=age>=40?1.7:age>=35?1.35:1,lossRng=new SeededRng(deriveSeed(world.seed,`pregnancy-loss:${pregnancy.id}:${date}`));if(!lossRng.chance(base*ageFactor))continue;pregnancy.status='loss';pregnancy.outcomeDate=date;const involved=pregnancy.pregnantPersonId===world.character.id||pregnancy.partnerId===world.character.id,title='A pregnancy ended',body='The pregnancy ended before birth. The experience may affect stress, relationships and future family plans.';if(involved){world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+12);world.character.stress=clamp(world.character.stress+9);world.memories.unshift({id:`mem-pregnancy-loss-${pregnancy.id}`,date,title,summary:body,significance:92});}events.push({id:`evt-pregnancy-loss-${pregnancy.id}-${date}`,date,title,body,type:'relationship',priority:'major'});}return events;}
function conceptionCandidate(world:WorldState,p:Partnership){if(!['exclusive','engaged','married'].includes(p.status)||!['trying','open'].includes(p.familyPlan)||hasOngoingPregnancy(world,p))return null;const[a,b]=p.personIds,sa=sex(world,a),sb=sex(world,b);if(sa===sb||!sa||!sb)return null;const pregnant=sa==='female'?a:b,partner=pregnant===a?b:a,bd=birthDate(world,pregnant);if(!bd)return null;const age=ageAt(bd,world.date);return age<18||age>45?null:{pregnant,partner};}
function updateChild(world:WorldState,child:Npc,date:string){if(!child.childDevelopment)return;const age=ageAt(child.birthDate,date);child.age=age;const stage=childStage(age);if(child.childDevelopment.stage!==stage){child.childDevelopment.stage=stage;const home=activeHouseholdForPerson(world,child.id);if(home){home.schedule=home.schedule.filter(s=>s.personId!==child.id);home.schedule.push({id:`schedule-${child.id}-${stage}`,personId:child.id,label:age<5?'Childcare / home routine':age<18?'School / activities':'Work / education',dayOfWeek:1,startHour:age<5?7:8,endHour:age<5?18:age<18?15:17});}}if(age>=18)child.childDevelopment.independence=clamp(child.childDevelopment.independence+.25);}
export function simulateFamily(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{const events:LifeEvent[]=[];for(const pregnancy of world.pregnancies.filter(p=>p.status==='ongoing'&&p.dueDate<=date)){const evt=createBirth(world,pregnancy.id,date,new SeededRng(deriveSeed(world.seed,`birth:${pregnancy.id}:${date}`)));if(evt)events.push(evt);}events.push(...maybePregnancyLoss(world,date));if(new Date(`${date}T12:00:00Z`).getUTCDay()===0){for(const p of activePartnerships(world)){const candidate=conceptionCandidate(world,p);if(!candidate)continue;const chance=p.familyPlan==='trying'?.07:.015;if(!rng.chance(chance))continue;world.pregnancies.push({id:`pregnancy-${candidate.pregnant}-${date}`,pregnantPersonId:candidate.pregnant,partnerId:candidate.partner,conceptionDate:date,dueDate:addDays(date,280),status:'ongoing',planned:p.familyPlan==='trying',childIds:[],outcomeDate:null});events.push({id:`evt-pregnancy-${candidate.pregnant}-${date}`,date,title:candidate.pregnant===world.character.id?'You learned you are pregnant':'A pregnancy changed your household plans',body:`A pregnancy has begun. The expected due date is ${addDays(date,280)}.`,type:'relationship',priority:'major'});break;}}if(Number(date.slice(-2))===1)for(const child of world.npcs.filter(n=>n.role==='Child'&&n.childDevelopment))updateChild(world,child,date);return events;}
export type ParentingAction='quality_time'|'support'|'structure';
export function applyParentingAction(input:WorldState,childId:string,action:ParentingAction):WorldState{const world=structuredClone(input),child=world.npcs.find(n=>n.id===childId&&n.childDevelopment);if(!child||!child.childDevelopment)return world;const linked=world.familyLinks.some(f=>f.fromId===world.character.id&&f.toId===childId&&!f.endedDate&&['biological_parent','adoptive_parent','step_parent'].includes(f.relation));if(!linked)return world;const dev=child.childDevelopment;if(action==='quality_time'){dev.attachmentSecurity=clamp(dev.attachmentSecurity+3);dev.confidence=clamp(dev.confidence+1.5);}else if(action==='support'){dev.confidence=clamp(dev.confidence+2.5);dev.schoolEngagement=clamp(dev.schoolEngagement+1.5);}else{dev.behaviorRegulation=clamp(dev.behaviorRegulation+2.5);dev.independence=clamp(dev.independence+1);}dev.lastParentingDate=world.date;const pc=world.relationships.find(r=>r.fromId===world.character.id&&r.toId===childId),cp=world.relationships.find(r=>r.fromId===childId&&r.toId===world.character.id);for(const r of[pc,cp])if(r){r.affection=clamp(r.affection+1.5);r.familiarity=clamp(r.familiarity+2);r.trust.emotional=clamp(r.trust.emotional+1.5);r.lastMeaningfulContactDate=world.date;}world.events.unshift({id:`evt-parenting-${childId}-${world.date}-${action}`,date:world.date,title:`You invested in ${child.name.split(' ')[0]}`,body:action==='quality_time'?'You made meaningful time to be together.':action==='support'?'You offered encouragement and support.':'You provided clear structure and expectations.',type:'relationship',priority:'low'});return world;}
export function childrenOf(world:WorldState,parentId:string){const ids=world.familyLinks.filter(f=>f.fromId===parentId&&!f.endedDate&&['biological_parent','adoptive_parent','step_parent'].includes(f.relation)).map(f=>f.toId);return ids.map(id=>world.npcs.find(n=>n.id===id)).filter((n):n is Npc=>Boolean(n));}
