import type { WorldState } from '../types/game';
import type { BudgetRule, CreditProfile, FinancialAccount, HouseholdFinancePlan, InsurancePolicy, RecurringObligation } from '../types/finance';
import { ageAt } from './familyEngine';

const addMonths=(date:string,months:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+months);return d.toISOString().slice(0,10);};
const dueDate=(date:string,day:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(day);if(d.toISOString().slice(0,10)<date)d.setUTCMonth(d.getUTCMonth()+1);return d.toISOString().slice(0,10);};
function playerHousehold(world:WorldState){return world.households.find(h=>!h.endedDate&&h.memberIds.includes(world.character.id));}
function foodMultiplier(world:WorldState){const strategy=world.lifestyleProfiles?.find(p=>p.personId===world.character.id)?.foodStrategy??'standard';return{budget:.78,standard:1,healthy:1.12,premium:1.42,convenience:1.28}[strategy];}
function account(id:string,ownerId:string,name:string,type:FinancialAccount['type'],balance:number,apy:number,date:string):FinancialAccount{return{id,ownerIds:[ownerId],institution:'Evera Community Bank',name,type,balance:Math.round(balance*100)/100,apy,status:'open',openedDate:date};}
function startingCredit(world:WorldState):CreditProfile{const age=ageAt(world.character.birthDate,world.date),base={struggling:610,working:635,stable:680,affluent:715,wealthy:740}[world.character.socioeconomicBackground];return{personId:world.character.id,score:Math.max(age<18?0:300,age<18?0:Math.min(790,base+Math.min(30,(age-18)*2))),paymentHistory:age<18?0:96,utilization:0,averageAgeMonths:Math.max(0,(age-18)*12),inquiries:0,derogatoryMarks:0,lastUpdatedDate:world.date};}
function recurring(world:WorldState):RecurringObligation[]{const home=playerHousehold(world);if(!home||!home.responsibleAdultIds.includes(world.character.id))return[];const householdId=home.id;return[
{id:`obligation-housing-${householdId}`,ownerId:world.character.id,householdId,name:'Housing',category:'Housing',amount:home.monthlyHousingCost,frequency:'monthly',dueDay:1,autopay:true,essential:true,active:true,nextDueDate:dueDate(world.date,1),pastDueAmount:0,missedPayments:0},
{id:`obligation-utilities-${householdId}`,ownerId:world.character.id,householdId,name:'Utilities',category:'Utilities',amount:185,frequency:'monthly',dueDay:8,autopay:true,essential:true,active:true,nextDueDate:dueDate(world.date,8),pastDueAmount:0,missedPayments:0},
{id:`obligation-groceries-${householdId}`,ownerId:world.character.id,householdId,name:'Household groceries',category:'Groceries',amount:Math.round(135*foodMultiplier(world)),frequency:'weekly',dueDay:6,autopay:true,essential:true,active:true,nextDueDate:world.date,pastDueAmount:0,missedPayments:0}
];}
function insurance(world:WorldState):InsurancePolicy[]{const home=playerHousehold(world);if(!home||!home.responsibleAdultIds.includes(world.character.id))return[];const policies:InsurancePolicy[]=[{id:'policy-renters-player',ownerIds:[world.character.id],kind:'renters',provider:'Pioneer Mutual',premiumMonthly:22,deductible:500,coverageLimit:30000,active:true}];const employment=world.employments.find(e=>e.personId===world.character.id&&e.status==='active');if(employment?.benefits.healthInsurance)policies.push({id:'policy-health-player',ownerIds:[world.character.id],kind:'health',provider:'Employer Health Plan',premiumMonthly:145,deductible:1750,coverageLimit:500000,active:true});return policies;}
function budgets(world:WorldState):BudgetRule[]{const home=playerHousehold(world);if(!home)return[];return[{id:`budget-groceries-${home.id}`,householdId:home.id,category:'Groceries',monthlyLimit:650},{id:`budget-dining-${home.id}`,householdId:home.id,category:'Dining',monthlyLimit:300},{id:`budget-misc-${home.id}`,householdId:home.id,category:'Other',monthlyLimit:350}];}
function plan(world:WorldState):HouseholdFinancePlan[]{const home=playerHousehold(world);if(!home)return[];return[{householdId:home.id,emergencyFundTargetMonths:3,savingsRate:5,investmentRate:3,debtStrategy:'highest_apr'}];}
function upsertRecurring(world:WorldState,next:RecurringObligation){const existing=world.recurringObligations.find(o=>o.id===next.id);if(!existing){world.recurringObligations.push(next);return;}if(existing.ownerId!==world.character.id||!existing.active){Object.assign(existing,next);}}
function upsertInsurance(world:WorldState,next:InsurancePolicy){const existing=world.insurancePolicies.find(p=>p.id===next.id);if(!existing){world.insurancePolicies.push(next);return;}if(!existing.ownerIds.includes(world.character.id)||!existing.active)Object.assign(existing,next);}
function upsertBudget(world:WorldState,next:BudgetRule){const existing=world.budgetRules.find(b=>b.id===next.id);if(existing)Object.assign(existing,next);else world.budgetRules.push(next);}
function upsertPlan(world:WorldState,next:HouseholdFinancePlan){const existing=world.householdFinancePlans.find(p=>p.householdId===next.householdId);if(existing)Object.assign(existing,next);else world.householdFinancePlans.push(next);}
export function initializeFinance(world:WorldState){world.financialAccounts??=[];world.recurringObligations??=[];world.budgetRules??=[];world.householdFinancePlans??=[];world.creditProfiles??=[];world.liabilities??=[];world.insurancePolicies??=[];world.properties??=[];world.vehicles??=[];world.investmentPositions??=[];world.bankruptcyRecords??=[];world.market??={usEquityIndex:100,internationalEquityIndex:100,bondIndex:100,volatility:18,regime:'neutral',lastUpdatedDate:world.date};if(!world.financialAccounts.some(a=>a.id==='account-checking-player'))world.financialAccounts.push(account('account-checking-player',world.character.id,'Everyday Checking','checking',world.character.cash,0,world.date));if(!world.financialAccounts.some(a=>a.id==='account-savings-player'))world.financialAccounts.push(account('account-savings-player',world.character.id,'Emergency Savings','savings',0,3.25,world.date));if(!world.financialAccounts.some(a=>a.id==='account-investment-player'))world.financialAccounts.push(account('account-investment-player',world.character.id,'Brokerage','investment',0,0,world.date));if(!world.financialAccounts.some(a=>a.id==='account-retirement-player'))world.financialAccounts.push(account('account-retirement-player',world.character.id,'Retirement','retirement',0,0,world.date));if(!world.creditProfiles.some(c=>c.personId===world.character.id))world.creditProfiles.push(startingCredit(world));for(const o of recurring(world))upsertRecurring(world,o);for(const p of insurance(world))upsertInsurance(world,p);for(const b of budgets(world))upsertBudget(world,b);for(const p of plan(world))upsertPlan(world,p);const studentDebt=world.educationEnrollments.filter(e=>e.personId===world.character.id).reduce((s,e)=>s+e.studentDebt,0);if(studentDebt>0&&!world.liabilities.some(l=>l.kind==='student'&&l.borrowerIds.includes(world.character.id)))world.liabilities.push({id:`liability-student-${world.character.id}`,borrowerIds:[world.character.id],lender:'Education Finance Authority',kind:'student',principal:Math.round(studentDebt*100)/100,apr:5.5,minimumPayment:Math.max(50,Math.round(studentDebt*.01)),creditLimit:null,dueDay:12,status:'current',missedPayments:0,openedDate:world.date,termMonths:120,securedAssetId:null});return world;}
export function refreshHouseholdFinance(world:WorldState){initializeFinance(world);const home=playerHousehold(world);if(!home)return world;const responsible=home.responsibleAdultIds.includes(world.character.id),ownsHome=world.properties.some(p=>p.kind==='primary_home'&&p.status==='owned'&&p.ownerIds.includes(world.character.id));let housing=world.recurringObligations.find(o=>o.category==='Housing'&&o.ownerId===world.character.id&&o.active);if(!responsible||ownsHome){if(housing)housing.active=false;}else{if(!housing){housing={id:`obligation-housing-${home.id}`,ownerId:world.character.id,householdId:home.id,name:'Housing',category:'Housing',amount:home.monthlyHousingCost,frequency:'monthly',dueDay:1,autopay:true,essential:true,active:true,nextDueDate:addMonths(world.date,1),pastDueAmount:0,missedPayments:0};world.recurringObligations.push(housing);}housing.householdId=home.id;housing.amount=home.monthlyHousingCost;housing.active=true;}
  const members=Math.max(1,home.memberIds.length),groceries=world.recurringObligations.find(o=>o.category==='Groceries'&&o.ownerId===world.character.id&&o.active),utilities=world.recurringObligations.find(o=>o.category==='Utilities'&&o.ownerId===world.character.id&&o.active);if(groceries)groceries.amount=Math.round((82+members*38)*foodMultiplier(world));if(utilities)utilities.amount=Math.round(125+members*32);
  const youngChildren=home.memberIds.filter(id=>{const n=world.npcs.find(n=>n.id===id);return n?.role==='Child'&&n.age<5;}).length;let childcare=world.recurringObligations.find(o=>o.category==='Childcare'&&o.ownerId===world.character.id);if(youngChildren>0&&responsible){if(!childcare){childcare={id:`obligation-childcare-${home.id}`,ownerId:world.character.id,householdId:home.id,name:'Childcare',category:'Childcare',amount:220*youngChildren,frequency:'weekly',dueDay:1,autopay:true,essential:true,active:true,nextDueDate:world.date,pastDueAmount:0,missedPayments:0};world.recurringObligations.push(childcare);}childcare.householdId=home.id;childcare.amount=220*youngChildren;childcare.active=true;}else if(childcare)childcare.active=false;
  return world;}
