import type { LifeEvent, WorldState } from '../types/game';
import type { FinancialAccount, InvestmentAssetClass, Liability, PropertyAsset, VehicleAsset } from '../types/finance';
import { SeededRng } from './rng';
import { initializeFinance, refreshHouseholdFinance } from './financeSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.round(v*100)/100;
const addDays=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const addMonths=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,10);};
const addYears=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+n);return d.toISOString().slice(0,10);};
function checking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open')!;}
function account(world:WorldState,id:string){return world.financialAccounts.find(a=>a.id===id&&a.status==='open');}
function ledger(world:WorldState,date:string,description:string,amount:number,category:string){world.ledger.unshift({id:`finance-${category}-${date}-${world.ledger.length+1}`,date,description,amount:money(amount),category});world.ledger=world.ledger.slice(0,1200);}
function event(events:LifeEvent[],date:string,title:string,body:string,priority:LifeEvent['priority']='medium'){events.push({id:`evt-finance-${date}-${title.replace(/\W+/g,'-').toLowerCase()}-${events.length}`,date,title,body,type:'finance',priority});}
function reconcileCash(world:WorldState){initializeFinance(world);const c=checking(world);if(Math.abs(c.balance-world.character.cash)>.009)c.balance=money(world.character.cash);}
function mirrorCash(world:WorldState){world.character.cash=money(checking(world).balance);}
function nextDue(date:string,frequency:'weekly'|'monthly'|'annual'){return frequency==='weekly'?addDays(date,7):frequency==='monthly'?addMonths(date,1):addYears(date,1);}
function spendChecking(world:WorldState,amount:number,date:string,description:string,category:string){const c=checking(world),paid=Math.min(Math.max(0,c.balance),Math.max(0,amount));c.balance=money(c.balance-paid);if(paid>0)ledger(world,date,description,-paid,category);return paid;}
function depositChecking(world:WorldState,amount:number,date:string,description:string,category='Transfer'){const c=checking(world);c.balance=money(c.balance+amount);ledger(world,date,description,amount,category);}
function activePlan(world:WorldState){const home=world.households.find(h=>!h.endedDate&&h.memberIds.includes(world.character.id));return home?world.householdFinancePlans.find(p=>p.householdId===home.id):undefined;}
function grossMonthlyIncome(world:WorldState){return world.employments.filter(e=>e.personId===world.character.id&&e.status==='active').reduce((s,e)=>s+e.salaryAnnual/12,0);}
function debtMonthly(world:WorldState){return world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)&&!['paid'].includes(l.status)).reduce((s,l)=>s+l.minimumPayment,0);}
function paymentFormula(principal:number,apr:number,months:number){const r=apr/100/12;if(r===0)return principal/months;return principal*r/(1-Math.pow(1+r,-months));}

function processObligations(world:WorldState,date:string,events:LifeEvent[]){for(const o of world.recurringObligations.filter(x=>x.active&&x.ownerId===world.character.id&&x.nextDueDate<=date)){const due=money(o.amount+o.pastDueAmount),paid=o.autopay?spendChecking(world,due,date,o.name,o.category):0,remaining=money(due-paid);if(remaining<=.01){o.pastDueAmount=0;o.missedPayments=0;}else{o.pastDueAmount=remaining;o.missedPayments++;world.character.human.needs.security=clamp(world.character.human.needs.security-(o.essential?5:2));if(o.missedPayments===1||o.missedPayments===3)event(events,date,`${o.name} is past due`,`You could not fully cover ${o.name}. ${remaining.toLocaleString('en-US',{style:'currency',currency:'USD'})} remains past due.`,o.essential?'major':'medium');}o.nextDueDate=nextDue(o.nextDueDate,o.frequency);}}
function processInsurance(world:WorldState,date:string,events:LifeEvent[]){if(Number(date.slice(-2))!==5)return;for(const p of world.insurancePolicies.filter(p=>p.active&&p.ownerIds.includes(world.character.id))){const paid=spendChecking(world,p.premiumMonthly,date,`${p.kind.replace('_',' ')} insurance premium`,'Insurance');if(paid+0.01<p.premiumMonthly){p.active=false;event(events,date,`${p.kind} coverage lapsed`,'The premium could not be paid in full, so this policy is no longer active.','major');}}}
function processDebt(world:WorldState,date:string,events:LifeEvent[]){const day=Number(date.slice(-2));for(const l of world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)&&l.status!=='paid')){if(day===1&&l.principal>0)l.principal=money(l.principal*(1+l.apr/100/12));if(day!==l.dueDay)continue;const due=Math.min(l.principal,l.minimumPayment),paid=spendChecking(world,due,date,`${l.kind.replace('_',' ')} payment`,'Debt');l.principal=money(Math.max(0,l.principal-paid));if(l.principal<=.01){l.principal=0;l.status='paid';continue;}if(paid+0.01<due){l.missedPayments++;l.status=l.missedPayments>=3?'default':'delinquent';if(l.missedPayments===1||l.missedPayments===3)event(events,date,l.status==='default'?`${l.kind.replace('_',' ')} debt defaulted`:`${l.kind.replace('_',' ')} payment missed`,'The missed payment will affect credit and may create asset or collection consequences.','major');}else{l.missedPayments=Math.max(0,l.missedPayments-1);if(l.status==='delinquent'&&l.missedPayments===0)l.status='current';}}
  for(const l of world.liabilities.filter(l=>l.status==='default'&&l.securedAssetId)){const v=world.vehicles.find(v=>v.id===l.securedAssetId&&v.status==='owned');if(v){v.status='repossessed';event(events,date,'A vehicle was repossessed',`${v.description} was repossessed after the secured loan defaulted.`,'major');}const p=world.properties.find(p=>p.id===l.securedAssetId&&p.status==='owned');if(p&&l.missedPayments>=5)event(events,date,'Your home is at risk','The mortgage default has progressed far enough that foreclosure risk is now serious.','major');}}
function processSavingsAndInvesting(world:WorldState,date:string){const incomeToday=world.ledger.filter(x=>x.date===date&&x.amount>0&&x.category==='Income').reduce((s,x)=>s+x.amount,0),plan=activePlan(world);if(incomeToday<=0||!plan)return;const c=checking(world),save=Math.min(c.balance,money(incomeToday*plan.savingsRate/100)),savings=account(world,'account-savings-player');if(savings&&save>0){c.balance=money(c.balance-save);savings.balance=money(savings.balance+save);ledger(world,date,'Automatic emergency savings',-save,'Savings');}const invest=Math.min(c.balance,money(incomeToday*plan.investmentRate/100));if(invest>0)investAmountMutable(world,'account-investment-player','us_equity',invest,date);}
function processInterest(world:WorldState,date:string){if(Number(date.slice(-2))!==1)return;for(const a of world.financialAccounts.filter(a=>a.status==='open'&&a.apy>0&&a.balance>0)){const interest=money(a.balance*a.apy/100/12);a.balance=money(a.balance+interest);if(a.ownerIds.includes(world.character.id)&&interest>0)ledger(world,date,`${a.name} interest`,interest,'Interest');}}
function updateMarket(world:WorldState,date:string,rng:SeededRng){const m=world.market,drift=m.regime==='bull'?.00035:m.regime==='bear'?-.00025:.00015,shock=(rng.next()-.5)*2*(m.volatility/100)/Math.sqrt(252);m.usEquityIndex=Math.max(10,money(m.usEquityIndex*(1+drift+shock)));m.internationalEquityIndex=Math.max(10,money(m.internationalEquityIndex*(1+drift*.8+shock*.85)));m.bondIndex=Math.max(10,money(m.bondIndex*(1+.00008-shock*.12)));if(Number(date.slice(-2))===1){const pressure=world.economy.unemploymentRate+world.economy.inflationRate*.5;if(pressure>10)m.regime='bear';else if(pressure<6)m.regime='bull';else m.regime='neutral';m.volatility=clamp(m.volatility+(rng.next()-.5)*3,8,45);}m.lastUpdatedDate=date;for(const pos of world.investmentPositions){pos.price=pos.assetClass==='us_equity'?m.usEquityIndex:pos.assetClass==='international_equity'?m.internationalEquityIndex:pos.assetClass==='bond'?m.bondIndex:1;}for(const a of world.financialAccounts.filter(a=>a.type==='investment'||a.type==='retirement'))a.balance=money(world.investmentPositions.filter(p=>p.accountId===a.id).reduce((s,p)=>s+p.units*p.price,0));}
function updateAssets(world:WorldState,date:string){if(Number(date.slice(-2))!==1)return;for(const p of world.properties.filter(p=>p.status==='owned')){p.marketValue=money(p.marketValue*(1+(world.economy.inflationRate/100/12*.45)+(world.economy.housingIndex-1)/240));p.condition=clamp(p.condition-.08);}for(const v of world.vehicles.filter(v=>v.status==='owned')){v.marketValue=money(Math.max(v.purchasePrice*.08,v.marketValue*.988));v.mileage+=Math.round(900+world.character.traits.ambition*2);v.condition=clamp(v.condition-.22);}}
function updateCredit(world:WorldState,date:string){if(Number(date.slice(-2))!==1)return;const c=world.creditProfiles.find(c=>c.personId===world.character.id);if(!c)return;const cards=world.liabilities.filter(l=>l.kind==='credit_card'&&l.borrowerIds.includes(world.character.id)&&l.creditLimit),limits=cards.reduce((s,l)=>s+(l.creditLimit??0),0),balances=cards.reduce((s,l)=>s+l.principal,0),missed=world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)).reduce((s,l)=>s+l.missedPayments,0),defaults=world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)&&l.status==='default').length;c.utilization=limits>0?clamp(balances/limits*100):0;c.paymentHistory=clamp(100-missed*5-defaults*12);c.derogatoryMarks=Math.max(c.derogatoryMarks,defaults+world.bankruptcyRecords.filter(b=>b.personId===world.character.id).length);const target=300+c.paymentHistory*3.1+Math.max(0,30-c.utilization)*1.8+Math.min(90,c.averageAgeMonths/2)-c.inquiries*4-c.derogatoryMarks*38;c.score=Math.round(clamp(c.score*.72+target*.28,300,850));c.averageAgeMonths++;c.lastUpdatedDate=date;}
function financialStress(world:WorldState){const pastDue=world.recurringObligations.reduce((s,o)=>s+o.pastDueAmount,0),delinquent=world.liabilities.some(l=>l.status==='delinquent'||l.status==='default'),c=checking(world);if(pastDue>0||delinquent||c.balance<0){world.character.stress=clamp(world.character.stress+1.2);world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+1);world.character.human.needs.security=clamp(world.character.human.needs.security-1);}else if(c.balance>1000){world.character.human.needs.security=clamp(world.character.human.needs.security+.15);}}

function investAmountMutable(world:WorldState,accountId:string,assetClass:InvestmentAssetClass,amount:number,date:string){const a=account(world,accountId),c=checking(world);if(!a||!['investment','retirement'].includes(a.type)||amount<=0||c.balance+0.01<amount)return false;const price=assetClass==='us_equity'?world.market.usEquityIndex:assetClass==='international_equity'?world.market.internationalEquityIndex:assetClass==='bond'?world.market.bondIndex:1,units=amount/price;let p=world.investmentPositions.find(p=>p.accountId===accountId&&p.assetClass===assetClass);if(!p){p={id:`position-${accountId}-${assetClass}`,accountId,assetClass,units:0,price,costBasis:0};world.investmentPositions.push(p);}p.units+=units;p.costBasis=money(p.costBasis+amount);p.price=price;c.balance=money(c.balance-amount);a.balance=money(a.balance+amount);ledger(world,date,`Invested in ${assetClass.replaceAll('_',' ')}`,-amount,'Investment');return true;}
export function investAmount(input:WorldState,accountId:string,assetClass:InvestmentAssetClass,amount:number):WorldState{const world=structuredClone(input);reconcileCash(world);investAmountMutable(world,accountId,assetClass,money(amount),world.date);mirrorCash(world);return world;}
export function transferBetweenAccounts(input:WorldState,fromId:string,toId:string,amount:number):WorldState{const world=structuredClone(input);reconcileCash(world);const from=account(world,fromId),to=account(world,toId),v=money(Math.max(0,amount));if(!from||!to||from.id===to.id||v<=0||from.balance+0.01<v)return world;from.balance=money(from.balance-v);to.balance=money(to.balance+v);ledger(world,world.date,`Transfer · ${from.name} → ${to.name}`,-v,'Transfer');mirrorCash(world);return world;}
export function openCreditCard(input:WorldState,requestedLimit=2000):WorldState{const world=structuredClone(input);reconcileCash(world);const profile=world.creditProfiles.find(c=>c.personId===world.character.id);if(!profile||profile.score<580)return world;const limit=Math.round(clamp(requestedLimit,500,profile.score>=740?15000:profile.score>=680?7500:3500));world.liabilities.push({id:`liability-card-${world.date}-${world.liabilities.length+1}`,borrowerIds:[world.character.id],lender:'Evera Bankcard',kind:'credit_card',principal:0,apr:profile.score>=740?17.9:profile.score>=680?22.9:28.9,minimumPayment:35,creditLimit:limit,dueDay:18,status:'current',missedPayments:0,openedDate:world.date,termMonths:null,securedAssetId:null});profile.inquiries++;world.events.unshift({id:`evt-card-open-${world.date}`,date:world.date,title:'A new credit card account opened',body:`The account has a ${limit.toLocaleString('en-US',{style:'currency',currency:'USD'})} limit. Utilization and payment history will affect credit.`,type:'finance',priority:'medium'});return world;}
export function chargeCreditCard(input:WorldState,liabilityId:string,amount:number,description:string):WorldState{const world=structuredClone(input),l=world.liabilities.find(l=>l.id===liabilityId&&l.kind==='credit_card'&&l.status!=='default'),v=money(Math.max(0,amount));if(!l||!l.creditLimit||v<=0||l.principal+v>l.creditLimit)return world;l.principal=money(l.principal+v);l.minimumPayment=Math.max(35,money(l.principal*.025));ledger(world,world.date,description,-v,'Credit purchase');return world;}
export function payLiability(input:WorldState,liabilityId:string,amount:number):WorldState{const world=structuredClone(input);reconcileCash(world);const l=world.liabilities.find(l=>l.id===liabilityId&&l.status!=='paid'),v=money(Math.min(Math.max(0,amount),l?.principal??0));if(!l||v<=0)return world;const paid=spendChecking(world,v,world.date,`Extra payment · ${l.kind.replace('_',' ')}`,'Debt');l.principal=money(Math.max(0,l.principal-paid));if(l.principal===0)l.status='paid';mirrorCash(world);return world;}
export function buyVehicle(input:WorldState,kind:VehicleAsset['kind'],price:number,downPayment:number):WorldState{const world=structuredClone(input);reconcileCash(world);const c=checking(world),profile=world.creditProfiles.find(x=>x.personId===world.character.id),p=money(Math.max(3000,price)),down=money(clamp(downPayment,0,p));if(!profile||profile.score<560||c.balance+0.01<down)return world;const financed=money(p-down),apr=profile.score>=720?6.5:profile.score>=660?10.5:16.5,id=`vehicle-${world.date}-${world.vehicles.length+1}`;c.balance=money(c.balance-down);if(down>0)ledger(world,world.date,'Vehicle down payment',-down,'Transportation');let liabilityId:null|string=null;if(financed>0){liabilityId=`liability-auto-${id}`;world.liabilities.push({id:liabilityId,borrowerIds:[world.character.id],lender:'Evera Auto Finance',kind:'auto',principal:financed,apr,minimumPayment:money(paymentFormula(financed,apr,60)),creditLimit:null,dueDay:14,status:'current',missedPayments:0,openedDate:world.date,termMonths:60,securedAssetId:id});}world.vehicles.push({id,ownerIds:[world.character.id],kind,description:`${kind.charAt(0).toUpperCase()+kind.slice(1)} vehicle`,purchaseDate:world.date,purchasePrice:p,marketValue:money(p*.92),mileage:0,condition:100,fuelType:kind==='ev'?'electric':'gas',financingLiabilityId:liabilityId,status:'owned'});if(!world.insurancePolicies.some(x=>x.kind==='auto'&&x.active))world.insurancePolicies.push({id:`policy-auto-${id}`,ownerIds:[world.character.id],kind:'auto',provider:'Pioneer Mutual',premiumMonthly:165,deductible:1000,coverageLimit:100000,active:true});profile.inquiries++;mirrorCash(world);return world;}
export function buyHome(input:WorldState,price:number,downPayment:number):WorldState{const world=structuredClone(input);reconcileCash(world);const c=checking(world),profile=world.creditProfiles.find(x=>x.personId===world.character.id),home=world.households.find(h=>!h.endedDate&&h.memberIds.includes(world.character.id)),p=money(Math.max(50000,price)),down=money(clamp(downPayment,0,p)),income=grossMonthlyIncome(world);if(!profile||!home||profile.score<620||down<p*.03||c.balance+0.01<down||income<=0)return world;const loan=money(p-down),apr=money(world.economy.baseInterestRate+(profile.score>=740?1.1:profile.score>=680?1.8:2.7)),payment=money(paymentFormula(loan,apr,360));if((debtMonthly(world)+payment)/income>.45)return world;const id=`property-${world.date}-${world.properties.length+1}`,liabilityId=`liability-mortgage-${id}`;c.balance=money(c.balance-down);ledger(world,world.date,'Home down payment',-down,'Housing');world.liabilities.push({id:liabilityId,borrowerIds:[world.character.id],lender:'Evera Home Lending',kind:'mortgage',principal:loan,apr,minimumPayment:payment,creditLimit:null,dueDay:1,status:'current',missedPayments:0,openedDate:world.date,termMonths:360,securedAssetId:id});const property:PropertyAsset={id,ownerIds:[world.character.id],kind:'primary_home',location:home.location,description:'Primary residence',purchaseDate:world.date,purchasePrice:p,marketValue:p,mortgageLiabilityId:liabilityId,propertyTaxAnnual:p*.008,hoaMonthly:0,condition:92,status:'owned'};world.properties.push(property);home.homeType='house';home.monthlyHousingCost=0;for(const o of world.recurringObligations.filter(o=>o.category==='Housing'&&o.ownerId===world.character.id))o.active=false;if(!world.insurancePolicies.some(x=>x.kind==='homeowners'&&x.active))world.insurancePolicies.push({id:`policy-home-${id}`,ownerIds:[world.character.id],kind:'homeowners',provider:'Pioneer Mutual',premiumMonthly:money(p*.0035/12),deductible:2000,coverageLimit:p,active:true});profile.inquiries++;mirrorCash(world);world.events.unshift({id:`evt-home-${id}`,date:world.date,title:'You bought a home',body:'The property, mortgage, insurance, taxes and market value are now persistent parts of your financial life.',type:'finance',priority:'major'});return world;}
export function fileBankruptcy(input:WorldState):WorldState{const world=structuredClone(input);reconcileCash(world);const existing=world.bankruptcyRecords.some(b=>b.personId===world.character.id&&b.status==='filed');if(existing)return world;const eligible=world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)&&['credit_card','personal'].includes(l.kind)&&l.status!=='paid');if(eligible.length===0)return world;const ids=eligible.map(l=>l.id);for(const l of eligible){l.principal=0;l.status='paid';}world.bankruptcyRecords.push({id:`bankruptcy-${world.character.id}-${world.date}`,personId:world.character.id,filedDate:world.date,chapter:'liquidation',dischargedLiabilityIds:ids,status:'discharged',creditPenaltyUntil:addYears(world.date,10)});const profile=world.creditProfiles.find(c=>c.personId===world.character.id);if(profile){profile.score=Math.max(300,profile.score-170);profile.derogatoryMarks+=1;}world.events.unshift({id:`evt-bankruptcy-${world.date}`,date:world.date,title:'Bankruptcy changed your financial life',body:'Eligible unsecured debts were discharged. The filing remains part of your credit history for years, but it also creates a path to rebuild.',type:'finance',priority:'major'});return world;}
export function netWorth(world:WorldState){const accounts=world.financialAccounts.filter(a=>a.status==='open'&&a.ownerIds.includes(world.character.id)).reduce((s,a)=>s+a.balance,0),property=world.properties.filter(p=>p.status==='owned'&&p.ownerIds.includes(world.character.id)).reduce((s,p)=>s+p.marketValue,0),vehicles=world.vehicles.filter(v=>v.status==='owned'&&v.ownerIds.includes(world.character.id)).reduce((s,v)=>s+v.marketValue,0),debt=world.liabilities.filter(l=>l.status!=='paid'&&l.borrowerIds.includes(world.character.id)).reduce((s,l)=>s+l.principal,0);return money(accounts+property+vehicles-debt);}
export function simulateFinance(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{reconcileCash(world);refreshHouseholdFinance(world);const events:LifeEvent[]=[];processObligations(world,date,events);processInsurance(world,date,events);processDebt(world,date,events);processSavingsAndInvesting(world,date);processInterest(world,date);updateMarket(world,date,rng);updateAssets(world,date);updateCredit(world,date);financialStress(world);mirrorCash(world);return events;}
