import type { LifeEvent, WorldState } from '../types/game';
import type { EncounterKind, MedicalCondition } from '../types/health';
import { SeededRng } from './rng';
import { initializeHealth } from './healthSeed';
import { ageAt } from './familyEngine';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.round(v*100)/100;
const daysBetween=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/86_400_000);
function humanFor(world:WorldState,personId:string){if(personId===world.character.id)return world.character.human;return world.npcs.find(n=>n.id===personId)?.human??null;}
function birthDateFor(world:WorldState,personId:string){if(personId===world.character.id)return world.character.birthDate;return world.npcs.find(n=>n.id===personId)?.birthDate??world.character.birthDate;}
function profileFor(world:WorldState,personId:string){return world.healthProfiles.find(p=>p.personId===personId);}
function activeHealthPolicy(world:WorldState,personId:string){return world.insurancePolicies.find(p=>p.kind==='health'&&p.active&&p.ownerIds.includes(personId));}
function checking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open');}
function event(date:string,title:string,body:string,priority:LifeEvent['priority']='medium'):LifeEvent{return{id:`evt-health-${date}-${title.replace(/\W+/g,'-').toLowerCase()}`,date,title,body,type:'health',priority};}
function addLedger(world:WorldState,date:string,description:string,amount:number){world.ledger.unshift({id:`health-${date}-${world.ledger.length+1}`,date,description,amount:money(amount),category:'Healthcare'});}
function spendForCare(world:WorldState,amount:number,date:string,description:string){const c=checking(world);if(!c)return 0;const paid=money(Math.min(Math.max(0,c.balance),Math.max(0,amount)));c.balance=money(c.balance-paid);world.character.cash=c.balance;if(paid>0)addLedger(world,date,description,-paid);return paid;}
function grossCost(kind:EncounterKind){return{preventive:280,primary_care:195,urgent_care:360,emergency:2400,specialist:475,therapy:165}[kind];}
function careFinancials(world:WorldState,personId:string,kind:EncounterKind,gross:number){if(personId!==world.character.id)return{insurancePaid:money(gross*.72),patientResponsibility:money(gross*.28)};const profile=profileFor(world,personId),policy=activeHealthPolicy(world,personId);if(!profile||!policy)return{insurancePaid:0,patientResponsibility:gross};if(kind==='preventive')return{insurancePaid:gross,patientResponsibility:0};const remainingDeductible=Math.max(0,policy.deductible-profile.deductibleSpentYear),deductiblePart=Math.min(gross,remainingDeductible),afterDeductible=Math.max(0,gross-deductiblePart),coinsurance=money(afterDeductible*.2),patientResponsibility=money(deductiblePart+coinsurance);profile.deductibleSpentYear=money(profile.deductibleSpentYear+deductiblePart);return{insurancePaid:money(gross-patientResponsibility),patientResponsibility};}
function careEffect(kind:EncounterKind){return{preventive:0,primary_care:10,urgent_care:17,emergency:26,specialist:15,therapy:9}[kind];}
function ensureMedication(world:WorldState,condition:MedicalCondition){if(world.medications.some(m=>m.conditionId===condition.id&&m.active)||!['chronic','mental'].includes(condition.kind))return;world.medications.push({id:`med-${condition.id}`,personId:condition.personId,conditionId:condition.id,name:condition.kind==='mental'?'Behavioral-health medication':'Maintenance medication',monthlyCost:condition.kind==='mental'?24:38,effectiveness:condition.kind==='mental'?62:68,adherence:75,startDate:world.date,endDate:null,active:true});}
function performEncounterMutable(world:WorldState,personId:string,kind:EncounterKind,reason:string,conditionIds:string[]){initializeHealth(world);const gross=grossCost(kind),financial=careFinancials(world,personId,kind,gross),paidNow=personId===world.character.id?spendForCare(world,financial.patientResponsibility,world.date,`${kind.replaceAll('_',' ')} care`):financial.patientResponsibility,unpaid=money(financial.patientResponsibility-paidNow),conditions=world.medicalConditions.filter(c=>conditionIds.includes(c.id));for(const condition of conditions){condition.diagnosisStatus='diagnosed';condition.diagnosedDate??=world.date;condition.severity=clamp(condition.severity-careEffect(kind));condition.treatmentSummary=kind==='therapy'?'Ongoing behavioral-health treatment':`Evaluated during ${kind.replaceAll('_',' ')} care`;if(condition.kind==='chronic'||condition.kind==='mental')condition.status='managed';ensureMedication(world,condition);}const outcome=conditions.length?`Care addressed ${conditions.map(c=>c.name).join(', ')}.`:'Preventive evaluation completed.';const encounterId=`encounter-${personId}-${world.date}-${world.medicalEncounters.length+1}`;world.medicalEncounters.unshift({id:encounterId,personId,date:world.date,kind,provider:kind==='emergency'?'Regional Medical Center':kind==='therapy'?'Behavioral Health Practice':'Community Health Network',reason,conditionIds,grossCost:gross,insurancePaid:financial.insurancePaid,patientResponsibility:financial.patientResponsibility,paidNow,outcome});if(unpaid>0&&personId===world.character.id)world.medicalBills.push({id:`bill-${encounterId}`,personId,encounterId,originalAmount:unpaid,balance:unpaid,openedDate:world.date,status:'current',missedMonths:0});const profile=profileFor(world,personId);if(profile&&kind==='preventive'){profile.lastPreventiveDate=world.date;profile.preventiveAdherence=clamp(profile.preventiveAdherence+4);const human=humanFor(world,personId);if(human)human.health.physicalCondition=clamp(human.health.physicalCondition+2);}return world;}

function createCondition(world:WorldState,personId:string,date:string,kind:MedicalCondition['kind'],name:string,severity:number,symptomSummary:string,recurrenceRisk:number){const condition:MedicalCondition={id:`condition-${personId}-${date}-${world.medicalConditions.length+1}`,personId,name,kind,severity:clamp(severity),diagnosisStatus:'suspected',status:'active',onsetDate:date,diagnosedDate:null,resolvedDate:null,recurrenceRisk:clamp(recurrenceRisk),symptomSummary,treatmentSummary:null};world.medicalConditions.unshift(condition);return condition;}
function newConditions(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){const people=[world.character.id,...world.npcs.filter(n=>n.tier===1&&n.human).map(n=>n.id)];for(const personId of people){const profile=profileFor(world,personId),human=humanFor(world,personId);if(!profile||!human)continue;profile.sleepQuality=clamp(90-human.health.sleepDebt*.65);profile.nutritionQuality=clamp(profile.nutritionQuality+(human.habits.some(h=>h.domain==='fitness'&&h.valence==='helpful')?.15:-.03));const acuteChance=.0018+(100-profile.sleepQuality)/65000+(100-profile.nutritionQuality)/90000;if(rng.chance(acuteChance)&&!world.medicalConditions.some(c=>c.personId===personId&&c.kind==='acute'&&c.status==='active')){const severity=28+rng.next()*40,condition=createCondition(world,personId,date,'acute',rng.chance(.55)?'Respiratory illness':'Acute viral illness',severity,'Fatigue and uncomfortable acute symptoms',12);if(personId===world.character.id)events.push(event(date,'You are feeling sick',condition.symptomSummary,severity>=58?'medium':'low'));if(severity>=72)performEncounterMutable(world,personId,'urgent_care',condition.symptomSummary,[condition.id]);}
    const accidentChance=.00012+profile.accidentRisk/500000;if(rng.chance(accidentChance)&&!world.medicalConditions.some(c=>c.personId===personId&&c.kind==='injury'&&c.status==='active')){const severity=32+rng.next()*55,condition=createCondition(world,personId,date,'injury','Accidental injury',severity,'Pain and reduced function after an accident',18);human.health.injuryBurden=clamp(human.health.injuryBurden+severity*.45);if(personId===world.character.id)events.push(event(date,'An accident caused an injury','You were injured. The severity and recovery path will depend on care and time.',severity>=70?'major':'medium'));if(severity>=76)performEncounterMutable(world,personId,'emergency','Accidental injury',[condition.id]);}
    const day=Number(date.slice(-2));if(day===1){const age=ageAt(birthDateFor(world,personId),date);if(age>=35&&profile.chronicRisk>=35&&rng.chance(profile.chronicRisk/9000)&&!world.medicalConditions.some(c=>c.personId===personId&&c.kind==='chronic'&&c.status!=='resolved')){const condition=createCondition(world,personId,date,'chronic','Chronic metabolic condition',32+rng.next()*30,'Persistent changes that may require ongoing monitoring',35);if(personId===world.character.id)events.push(event(date,'A health pattern needs attention','Some ongoing symptoms may warrant a medical evaluation.','medium'));if(profile.preventiveAdherence+profile.careAccess>=135)performEncounterMutable(world,personId,'primary_care',condition.symptomSummary,[condition.id]);}
      if(human.health.mentalLoad>=70&&rng.chance((human.health.mentalLoad-55)/1200)&&!world.medicalConditions.some(c=>c.personId===personId&&c.kind==='mental'&&c.status!=='resolved')){const condition=createCondition(world,personId,date,'mental','Persistent anxiety or depressive symptoms',30+rng.next()*35,'Mood, sleep, concentration or anxiety symptoms have persisted',28);if(personId===world.character.id)events.push(event(date,'Your mental health has been under strain','The pattern has lasted long enough that support could be useful.','medium'));if(profile.careAccess>=65&&rng.chance(.55))performEncounterMutable(world,personId,'therapy',condition.symptomSummary,[condition.id]);}}
  }}
function progressConditions(world:WorldState,date:string){for(const condition of world.medicalConditions.filter(c=>c.status!=='resolved')){const human=humanFor(world,condition.personId);if(!human)continue;const medication=world.medications.find(m=>m.conditionId===condition.id&&m.active),treatment=medication?medication.effectiveness*medication.adherence/10000:0;if(condition.kind==='acute')condition.severity=clamp(condition.severity-(condition.diagnosisStatus==='diagnosed'?3.4:2.1));else if(condition.kind==='injury')condition.severity=clamp(condition.severity-(condition.diagnosisStatus==='diagnosed'?1.7:.8));else if(condition.kind==='chronic')condition.severity=clamp(condition.severity+(treatment>.35?-.15:.06),18,92);else condition.severity=clamp(condition.severity+(human.health.mentalLoad>68?.12:-.08)-treatment*.3,15,95);if((condition.kind==='acute'||condition.kind==='injury')&&condition.severity<8){condition.status='resolved';condition.resolvedDate=date;condition.treatmentSummary??='Recovered over time';}if(condition.kind==='injury')human.health.injuryBurden=clamp(human.health.injuryBurden+condition.severity/800-.2);}}
function applyHealthBurden(world:WorldState){const personId=world.character.id,human=world.character.human,active=world.medicalConditions.filter(c=>c.personId===personId&&c.status!=='resolved'),acuteBurden=active.filter(c=>c.kind==='acute'||c.kind==='injury').reduce((s,c)=>s+c.severity,0),chronicBurden=active.filter(c=>c.kind==='chronic').reduce((s,c)=>s+c.severity,0),mentalBurden=active.filter(c=>c.kind==='mental').reduce((s,c)=>s+c.severity,0);human.health.physicalCondition=clamp(human.health.physicalCondition-acuteBurden/900-chronicBurden/1800+(active.length===0?.04:0));human.health.mentalLoad=clamp(human.health.mentalLoad+mentalBurden/1800);world.character.energy=clamp(world.character.energy-acuteBurden/700);world.character.stress=clamp(world.character.stress+mentalBurden/1500);}
function processMedications(world:WorldState,date:string){if(Number(date.slice(-2))!==15)return;for(const med of world.medications.filter(m=>m.active&&m.personId===world.character.id)){const paid=spendForCare(world,med.monthlyCost,date,med.name);if(paid+0.01<med.monthlyCost)med.adherence=clamp(med.adherence-12);else med.adherence=clamp(med.adherence+2);}}
function processMedicalBills(world:WorldState,date:string,events:LifeEvent[]){if(Number(date.slice(-2))!==20)return;for(const bill of world.medicalBills.filter(b=>b.personId===world.character.id&&b.status!=='paid')){const target=money(Math.min(bill.balance,Math.max(25,bill.originalAmount*.12))),paid=spendForCare(world,target,date,'Medical bill payment');bill.balance=money(Math.max(0,bill.balance-paid));if(bill.balance<=.01){bill.balance=0;bill.status='paid';continue;}bill.missedMonths++;bill.status=bill.missedMonths>=1?'past_due':'current';world.character.human.needs.security=clamp(world.character.human.needs.security-2);world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+1);if(bill.missedMonths===1||bill.missedMonths===3)events.push(event(date,'A medical bill remains unpaid',`${bill.balance.toLocaleString('en-US',{style:'currency',currency:'USD'})} remains on a medical bill.`,'medium'));}}
function preventiveReminder(world:WorldState,date:string,events:LifeEvent[]){if(date.slice(5)!=='01-15')return;const p=profileFor(world,world.character.id);if(!p)return;const overdue=!p.lastPreventiveDate||daysBetween(p.lastPreventiveDate,date)>420;if(overdue)events.push(event(date,'Preventive care is overdue','A routine preventive visit may reveal health issues before they become more serious.','low'));}

export function simulateHealth(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{initializeHealth(world);const events:LifeEvent[]=[];newConditions(world,date,rng,events);progressConditions(world,date);processMedications(world,date);processMedicalBills(world,date,events);preventiveReminder(world,date,events);applyHealthBurden(world);for(const p of world.healthProfiles)p.lastUpdatedDate=date;return events;}
export function seekMedicalCare(input:WorldState,conditionId:string,kind:Exclude<EncounterKind,'preventive'>='primary_care'):WorldState{const world=structuredClone(input);initializeHealth(world);const condition=world.medicalConditions.find(c=>c.id===conditionId&&c.personId===world.character.id&&c.status!=='resolved');if(!condition)return world;performEncounterMutable(world,world.character.id,kind,condition.symptomSummary,[condition.id]);world.events.unshift(event(world.date,'You sought medical care',`You received ${kind.replaceAll('_',' ')} care for ${condition.name}.`,'medium'));return world;}
export function getPreventiveCare(input:WorldState):WorldState{const world=structuredClone(input);initializeHealth(world);performEncounterMutable(world,world.character.id,'preventive','Routine preventive care',[]);world.events.unshift(event(world.date,'Preventive visit completed','You completed routine preventive care and updated your medical history.','low'));return world;}
