import type { CustodyPlan, Household, LifeEvent, WorldState } from '../types/game';

const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const ageAt=(birthDate:string,date:string)=>{const b=new Date(`${birthDate}T12:00:00Z`),d=new Date(`${date}T12:00:00Z`);let age=d.getUTCFullYear()-b.getUTCFullYear();const md=d.getUTCMonth()-b.getUTCMonth();if(md<0||(md===0&&d.getUTCDate()<b.getUTCDate()))age--;return age;};
function birthDateOf(world:WorldState,id:string){if(id===world.character.id)return world.character.birthDate;return world.npcs.find(n=>n.id===id)?.birthDate??null;}
function personAge(world:WorldState,id:string){const birth=birthDateOf(world,id);return birth?ageAt(birth,world.date):18;}
function humanOf(world:WorldState,id:string){if(id===world.character.id)return world.character.human;return world.npcs.find(n=>n.id===id)?.human??null;}
function edge(world:WorldState,from:string,to:string){return world.relationships.find(r=>r.fromId===from&&r.toId===to);}
export function activeHouseholdForPerson(world:WorldState,id:string){return world.households.find(h=>!h.endedDate&&h.memberIds.includes(id));}
function dependentChildren(world:WorldState,parentId:string){const links=world.familyLinks.filter(f=>f.fromId===parentId&&!f.endedDate&&['biological_child','adoptive_child','step_child'].includes(f.relation));return links.map(f=>f.toId).filter(id=>personAge(world,id)<18);}
function removeFromOldHome(world:WorldState,id:string,date:string){const home=activeHouseholdForPerson(world,id);if(!home)return;home.memberIds=home.memberIds.filter(x=>x!==id);home.responsibleAdultIds=home.responsibleAdultIds.filter(x=>x!==id);home.laborAssignments=home.laborAssignments.filter(x=>x.ownerId!==id);home.schedule=home.schedule.filter(x=>x.personId!==id);if(home.memberIds.length===0||home.responsibleAdultIds.length===0)home.endedDate=date;}
function defaultLabor(adults:string[]){const tasks=[['Meals','daily',18],['Cleaning','weekly',16],['Household admin','weekly',14],['Laundry','weekly',13]] as const;return tasks.map((t,i)=>({id:`labor-${i}-${adults[i%adults.length]}`,task:t[0],ownerId:adults[i%adults.length]!,cadence:t[1],burden:t[2]}));}
function defaultSchedules(world:WorldState,members:string[]){return members.map((id,i)=>({id:`schedule-${id}-primary`,personId:id,label:personAge(world,id)<18?'School / care':'Work / primary responsibilities',dayOfWeek:1,startHour:personAge(world,id)<18?8:9,endHour:personAge(world,id)<18?15:17+i%2}));}
export function movePeopleTogether(world:WorldState,a:string,b:string,date:string,financeStyle:Household['financeStyle']='hybrid'){const existing=world.households.find(h=>!h.endedDate&&h.memberIds.includes(a)&&h.memberIds.includes(b));if(existing)return existing.id;const homeA=activeHouseholdForPerson(world,a),homeB=activeHouseholdForPerson(world,b);const children=[...new Set([...dependentChildren(world,a),...dependentChildren(world,b)])];const cost=Math.round(((homeA?.monthlyHousingCost??1450*world.economy.housingIndex)+(homeB?.monthlyHousingCost??1450*world.economy.housingIndex))*.55);removeFromOldHome(world,a,date);removeFromOldHome(world,b,date);for(const child of children){const old=activeHouseholdForPerson(world,child);if(old){old.memberIds=old.memberIds.filter(x=>x!==child);old.schedule=old.schedule.filter(x=>x.personId!==child);if(old.memberIds.length===0)old.endedDate=date;}}
  const adults=[a,b].filter(id=>personAge(world,id)>=18);const members=[a,b,...children];const household:Household={id:`household-${[a,b].sort().join('-')}-${date}`,name:'Shared household',memberIds:members,location:(a===world.character.id?world.character.location:world.npcs.find(n=>n.id===a)?.location)??world.character.location,homeType:'apartment',monthlyHousingCost:Math.max(650,cost),responsibleAdultIds:adults,financeStyle,laborAssignments:defaultLabor(adults),schedule:defaultSchedules(world,members),createdDate:date,endedDate:null};world.households.push(household);return household.id;}
function makeSoloHome(world:WorldState,adultId:string,date:string,baseCost:number,children:string[]):Household{const members=[adultId,...children];return{id:`household-${adultId}-${date}-${world.households.length}`,name:`${adultId===world.character.id?world.character.lastName:world.npcs.find(n=>n.id===adultId)?.name.split(' ').at(-1)??'New'} household`,memberIds:members,location:(adultId===world.character.id?world.character.location:world.npcs.find(n=>n.id===adultId)?.location)??world.character.location,homeType:'apartment',monthlyHousingCost:Math.max(650,Math.round(baseCost*.68)),responsibleAdultIds:[adultId],financeStyle:'separate',laborAssignments:defaultLabor([adultId]),schedule:defaultSchedules(world,members),createdDate:date,endedDate:null};}
function sharedChild(world:WorldState,childId:string,a:string,b:string){const parents=world.familyLinks.filter(f=>f.toId===childId&&!f.endedDate&&['biological_parent','adoptive_parent'].includes(f.relation)).map(f=>f.fromId);return parents.includes(a)&&parents.includes(b);}
export function separatePartners(world:WorldState,a:string,b:string,date:string){const joint=world.households.find(h=>!h.endedDate&&h.memberIds.includes(a)&&h.memberIds.includes(b));if(!joint)return;const children=joint.memberIds.filter(id=>id!==a&&id!==b&&personAge(world,id)<18);joint.endedDate=date;const shared=children.filter(c=>sharedChild(world,c,a,b));const aOnly=children.filter(c=>!shared.includes(c)&&dependentChildren(world,a).includes(c));const bOnly=children.filter(c=>!shared.includes(c)&&dependentChildren(world,b).includes(c));const homeA=makeSoloHome(world,a,date,joint.monthlyHousingCost,[...aOnly,...shared]);const homeB=makeSoloHome(world,b,date,joint.monthlyHousingCost,bOnly);world.households.push(homeA,homeB);for(const childId of shared){if(world.custodyPlans.some(c=>c.childId===childId&&c.active))continue;const plan:CustodyPlan={id:`custody-${childId}-${date}`,childId,parentIds:[a,b],householdIds:[homeA.id,homeB.id],arrangement:'shared',currentHouseholdId:homeA.id,monthlySupport:0,supportPayerId:null,startDate:date,active:true};world.custodyPlans.push(plan);}}
export function reassignHouseholdLabor(input:WorldState,householdId:string,assignmentId:string,ownerId:string):WorldState{const world=structuredClone(input);const home=world.households.find(h=>h.id===householdId&&!h.endedDate);if(!home||!home.responsibleAdultIds.includes(ownerId))return world;const task=home.laborAssignments.find(l=>l.id===assignmentId);if(task)task.ownerId=ownerId;return world;}
function moveCustodyChild(world:WorldState,plan:CustodyPlan,newHome:string){for(const homeId of plan.householdIds){const home=world.households.find(h=>h.id===homeId);if(!home)continue;home.memberIds=home.memberIds.filter(id=>id!==plan.childId);}const target=world.households.find(h=>h.id===newHome);if(target&&!target.memberIds.includes(plan.childId))target.memberIds.push(plan.childId);plan.currentHouseholdId=newHome;}
export function simulateHouseholds(world:WorldState,date:string):LifeEvent[]{const events:LifeEvent[]=[];const day=new Date(`${date}T12:00:00Z`).getUTCDay();if(day===0){for(const plan of world.custodyPlans.filter(c=>c.active&&c.arrangement==='shared')){const next=plan.currentHouseholdId===plan.householdIds[0]?plan.householdIds[1]:plan.householdIds[0];moveCustodyChild(world,plan,next);}for(const home of world.households.filter(h=>!h.endedDate&&h.responsibleAdultIds.length>1)){const burdens=new Map(home.responsibleAdultIds.map(id=>[id,0]));for(const task of home.laborAssignments)burdens.set(task.ownerId,(burdens.get(task.ownerId)??0)+task.burden);const vals=[...burdens.entries()].sort((a,b)=>b[1]-a[1]);if(vals.length<2)continue;const[highId,high]=vals[0]!,[lowId,low]=vals.at(-1)!;if(high-low>22){const h=humanOf(world,highId);if(h)h.health.mentalLoad=clamp(h.health.mentalLoad+1.3);const rel=edge(world,highId,lowId);if(rel)rel.resentment=clamp(rel.resentment+.55);}}}
  const dom=Number(date.slice(-2));if(dom===1){for(const plan of world.custodyPlans.filter(c=>c.active&&c.monthlySupport>0&&c.supportPayerId)){const recipient=plan.parentIds.find(id=>id!==plan.supportPayerId);if(plan.supportPayerId===world.character.id){world.character.cash-=plan.monthlySupport;world.ledger.unshift({id:`support-${plan.id}-${date}`,date,description:'Child support',amount:-plan.monthlySupport,category:'Family'});}else if(recipient===world.character.id){world.character.cash+=plan.monthlySupport;world.ledger.unshift({id:`support-${plan.id}-${date}`,date,description:'Child support received',amount:plan.monthlySupport,category:'Family'});}}}return events;}
