import type { LifeEvent, WorldState } from '../types/game';
import type { CivilCase, CrimeIncident, CriminalCase, OffenseKind } from '../types/legacyLegal';
import { SeededRng } from './rng';
import { deriveSeed } from './humanEngine';
import { initializeLegacyLegal, isDeceased, isIncarcerated } from './legacyLegalSeed';

const DAY=86_400_000;const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));const money=(v:number)=>Math.round(v*100)/100;
const daysBetween=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/DAY);
const addDays=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
function event(date:string,title:string,body:string,priority:LifeEvent['priority']='medium'):LifeEvent{return{id:`evt-legal-${date}-${title.replace(/\W+/g,'-').toLowerCase()}`,date,title,body,type:'legal',priority};}
function nameFor(world:WorldState,id:string){if(id===world.character.id)return`${world.character.firstName} ${world.character.lastName}`;return world.npcs.find(n=>n.id===id)?.name??world.ancestorArchives.find(a=>a.personId===id)?.name??'Unknown person';}
function checking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open');}
function ledger(world:WorldState,date:string,description:string,amount:number){world.ledger.unshift({id:`legal-${date}-${world.ledger.length+1}`,date,description,amount:money(amount),category:'Legal'});world.ledger=world.ledger.slice(0,1400);}
function chargePlayer(world:WorldState,amount:number,date:string,description:string){const c=checking(world),owed=money(Math.max(0,amount));if(!c||owed<=0)return 0;const paid=money(Math.min(c.balance,owed));c.balance=money(c.balance-paid);world.character.cash=c.balance;if(paid>0)ledger(world,date,description,-paid);const unpaid=money(owed-paid);if(unpaid>0)world.liabilities.push({id:`liability-legal-${date}-${world.liabilities.length+1}`,borrowerIds:[world.character.id],lender:'Court / Legal Services',kind:'personal',principal:unpaid,apr:8.5,minimumPayment:Math.max(25,money(unpaid*.05)),creditLimit:null,dueDay:25,status:'current',missedPayments:0,openedDate:date,termMonths:24,securedAssetId:null});return paid;}
function creditPlayer(world:WorldState,amount:number,date:string,description:string){const c=checking(world);if(!c||amount<=0)return;c.balance=money(c.balance+amount);world.character.cash=c.balance;ledger(world,date,description,amount);}
function offenseSeverity(kind:OffenseKind){return{theft:42,fraud:56,assault:68,impaired_driving:62,property_offense:47}[kind];}
function offenseLabel(kind:OffenseKind){return kind.replaceAll('_',' ');}
function makeIncident(world:WorldState,actorId:string,date:string,offense:OffenseKind,victimId:string|null,rng:SeededRng,visible=false):CrimeIncident{const actor=actorId===world.character.id?world.character:world.npcs.find(n=>n.id===actorId),impulsivity=actor?.traits.impulsivity??50,severity=clamp(offenseSeverity(offense)+(rng.next()-.5)*18),evidence=clamp(32+severity*.38+(100-impulsivity)*.12+(rng.next()-.5)*36);const incident:CrimeIncident={id:`crime-${actorId}-${date}-${world.crimeIncidents.length+1}`,actorId,date,offense,severity,discovered:false,discoveredDate:null,evidenceStrength:evidence,victimId,status:'undiscovered'};world.crimeIncidents.unshift(incident);if(visible&&actorId===world.character.id)world.events.unshift(event(date,'An illegal act is now part of your history',`You committed ${offenseLabel(offense)}. Whether it is discovered depends on evidence, witnesses and what happens next.`,'medium'));return incident;}
export function commitOffense(input:WorldState,offense:OffenseKind,victimId:string|null=null):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);if(isDeceased(world,world.character.id)||isIncarcerated(world,world.character.id))return world;const rng=new SeededRng(deriveSeed(world.seed,`player-crime:${world.character.id}:${offense}:${world.date}:${world.crimeIncidents.length}`));makeIncident(world,world.character.id,world.date,offense,victimId,rng,true);return world;}
function discoverIncident(world:WorldState,incident:CrimeIncident,date:string,events:LifeEvent[]){incident.discovered=true;incident.discoveredDate=date;incident.status='investigating';if(incident.actorId===world.character.id)events.push(event(date,'An investigation reached you',`Authorities are investigating the ${offenseLabel(incident.offense)} incident. An investigation is not a conviction.`,'major'));else if(incident.victimId===world.character.id)events.push(event(date,'An incident involving you is under investigation',`Authorities are investigating an incident in which you were affected by ${offenseLabel(incident.offense)}.`,'medium'));}
function chargeIncident(world:WorldState,incident:CrimeIncident,date:string,events:LifeEvent[]){incident.status='charged';const legalCase:CriminalCase={id:`criminal-case-${incident.id}`,defendantId:incident.actorId,incidentId:incident.id,filedDate:date,status:'charged',representation:'public_defender',legalCost:0,outcomeDate:null,sentenceSummary:null};world.criminalCases.unshift(legalCase);if(incident.actorId===world.character.id)events.push(event(date,`Criminal charge: ${offenseLabel(incident.offense)}`,'A charge has been filed. You can plead or contest the case, and representation can affect cost and outcome without guaranteeing either.','major'));if(incident.victimId===world.character.id&&incident.actorId!==world.character.id)events.push(event(date,'Charges were filed in a case involving you',`A criminal charge was filed for ${offenseLabel(incident.offense)}.`,'medium'));if(incident.victimId&&['assault','property_offense','theft'].includes(incident.offense)&&!world.civilCases.some(c=>c.plaintiffId===incident.victimId&&c.defendantId===incident.actorId&&c.filedDate===date)){world.civilCases.push({id:`civil-from-${incident.id}`,plaintiffId:incident.victimId,defendantId:incident.actorId,filedDate:date,category:incident.offense==='assault'?'injury':'property',amountClaimed:money(1000+incident.severity*140),status:'filed',outcomeDate:null,amountAwarded:0,legalCost:0});}}
function processInvestigations(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const incident of world.crimeIncidents.filter(i=>!isDeceased(world,i.actorId)&&['undiscovered','investigating'].includes(i.status))){if(incident.status==='undiscovered'){const elapsed=daysBetween(incident.date,date);if(elapsed<1)continue;const daily=.0015+incident.evidenceStrength/12000+incident.severity/24000;if(rng.chance(daily))discoverIncident(world,incident,date,events);else if(elapsed>365&&rng.chance(.02))incident.status='closed';continue;}const since=daysBetween(incident.discoveredDate??incident.date,date);if(since<7)continue;const chargingStrength=incident.evidenceStrength+incident.severity*.35+(rng.next()-.5)*20;if(chargingStrength>=58)chargeIncident(world,incident,date,events);else if(since>=21){incident.status='closed';if(incident.actorId===world.character.id)events.push(event(date,'The investigation closed without charges','The investigation ended without a criminal charge. The underlying incident remains part of world history.','medium'));}}}
function representationEffect(rep:CriminalCase['representation']){return rep==='private_attorney'?14:rep==='public_defender'?7:-8;}
function endEmploymentForConviction(world:WorldState,personId:string,date:string){for(const e of world.employments.filter(e=>e.personId===personId&&e.status==='active')){e.status='ended';e.endDate=date;}if(personId===world.character.id)world.character.career='Unemployed';}
function convict(world:WorldState,c:CriminalCase,date:string,severity:number,plea:boolean,events:LifeEvent[]){const incident=world.crimeIncidents.find(i=>i.id===c.incidentId)!;c.status='convicted';c.outcomeDate=date;const effective=clamp(severity-(plea?12:0));world.criminalRecords.push({id:`record-${c.id}`,personId:c.defendantId,caseId:c.id,offense:incident.offense,convictionDate:date,severity:effective,active:true});const fine=money(250+effective*35);if(c.defendantId===world.character.id){chargePlayer(world,fine,date,'Court fine and costs');world.character.human.needs.security=clamp(world.character.human.needs.security-12);world.character.human.health.mentalLoad=clamp(world.character.human.health.mentalLoad+10);}let sentence=`Fine and court consequences totaling about ${fine.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}.`;if(effective>=70){const days=Math.round(30+(effective-70)*18);world.incarcerationRecords.push({id:`incarceration-${c.id}`,personId:c.defendantId,caseId:c.id,startDate:date,endDate:addDays(date,days),status:'incarcerated'});sentence=`Incarceration through ${addDays(date,days)} plus financial penalties.`;endEmploymentForConviction(world,c.defendantId,date);}c.sentenceSummary=sentence;if(c.defendantId===world.character.id)events.push(event(date,'You were convicted',`${sentence} The conviction can affect employment, finances and reputation long after the case ends.`,'major'));}
function acquit(world:WorldState,c:CriminalCase,date:string,events:LifeEvent[]){c.status='acquitted';c.outcomeDate=date;c.sentenceSummary='No criminal sentence.';if(c.defendantId===world.character.id)events.push(event(date,'You were acquitted','The criminal trial ended without a conviction. Legal costs and the experience itself may still have consequences.','major'));}
function processCriminalCases(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const c of world.criminalCases.filter(c=>!['dismissed','convicted','acquitted','closed'].includes(c.status))){const incident=world.crimeIncidents.find(i=>i.id===c.incidentId);if(!incident)continue;const age=daysBetween(c.filedDate,date);if(c.status==='charged'&&c.defendantId!==world.character.id&&age>=5)c.status=incident.evidenceStrength+incident.severity>115?'plea':'trial';if(c.status==='plea'&&age>=7){convict(world,c,date,incident.severity,true,events);continue;}if(c.status==='trial'&&age>=21){const defense=representationEffect(c.representation),convictionChance=clamp(incident.evidenceStrength*.008+incident.severity*.003-defense*.006,.08,.94);if(rng.chance(convictionChance))convict(world,c,date,incident.severity,false,events);else acquit(world,c,date,events);}}
}
function processRelease(world:WorldState,date:string,events:LifeEvent[]){for(const r of world.incarcerationRecords.filter(r=>r.status==='incarcerated'&&r.endDate<=date)){r.status='released';if(r.personId===world.character.id)events.push(event(date,'You were released from incarceration','You return to ordinary life with the world having continued while you were away. Employment, money and relationships may not be where you left them.','major'));}}
function backgroundCrime(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){if(Number(date.slice(-2))!==1||!rng.chance(.012))return;const actors=world.npcs.filter(n=>n.tier<=2&&n.human&&!isDeceased(world,n.id)&&!isIncarcerated(world,n.id,date));if(!actors.length)return;const actor=rng.pick(actors),offenses:OffenseKind[]=['theft','fraud','assault','property_offense'],offense=rng.pick(offenses),others=actors.filter(n=>n.id!==actor.id),victim=rng.chance(.12)?world.character.id:(rng.chance(.45)&&others.length?rng.pick(others).id:null),incident=makeIncident(world,actor.id,date,offense,victim,rng,false);if(victim===world.character.id){incident.discovered=true;incident.discoveredDate=date;incident.status='investigating';events.push(event(date,'You were affected by a crime',`A ${offenseLabel(offense)} incident affected you. The investigation may or may not lead to charges.`,'major'));}}
export function chooseCriminalResponse(input:WorldState,caseId:string,response:'plead'|'contest'):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const c=world.criminalCases.find(c=>c.id===caseId&&c.defendantId===world.character.id&&c.status==='charged');if(!c)return world;c.status=response==='plead'?'plea':'trial';world.events.unshift(event(world.date,response==='plead'?'You entered a plea':'You chose to contest the charge',response==='plead'?'The case will proceed through the plea process.':'The case will proceed toward trial. Neither choice guarantees a specific outcome.','medium'));return world;}
export function setCriminalRepresentation(input:WorldState,caseId:string,representation:CriminalCase['representation']):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const c=world.criminalCases.find(c=>c.id===caseId&&c.defendantId===world.character.id&&!['convicted','acquitted','dismissed','closed'].includes(c.status));if(!c)return world;if(representation==='private_attorney'&&c.representation!=='private_attorney'){const retainer=3000;chargePlayer(world,retainer,world.date,'Private legal retainer');c.legalCost=money(c.legalCost+retainer);}c.representation=representation;return world;}
export function fileCivilCase(input:WorldState,defendantId:string,category:CivilCase['category'],amountClaimed:number):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const amount=money(clamp(amountClaimed,250,500000));if(defendantId===world.character.id||isDeceased(world,defendantId))return world;world.civilCases.unshift({id:`civil-${world.character.id}-${defendantId}-${world.date}-${world.civilCases.length+1}`,plaintiffId:world.character.id,defendantId,filedDate:world.date,category,amountClaimed:amount,status:'filed',outcomeDate:null,amountAwarded:0,legalCost:350});chargePlayer(world,350,world.date,'Civil filing and legal costs');world.events.unshift(event(world.date,'A civil case was filed',`You filed a ${category} claim. Settlement and trial outcomes remain uncertain.`,'medium'));return world;}
function settleCivilMutable(world:WorldState,c:CivilCase,date:string,ratio:number){const award=money(c.amountClaimed*clamp(ratio,.05,.95));c.status='settled';c.outcomeDate=date;c.amountAwarded=award;if(c.plaintiffId===world.character.id)creditPlayer(world,award,date,'Civil settlement received');else if(c.defendantId===world.character.id)chargePlayer(world,award,date,'Civil settlement paid');return award;}
export function respondCivilCase(input:WorldState,caseId:string,response:'settle'|'trial'):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const c=world.civilCases.find(c=>c.id===caseId&&(c.plaintiffId===world.character.id||c.defendantId===world.character.id)&&['filed','negotiating'].includes(c.status));if(!c)return world;if(response==='settle'){const rng=new SeededRng(deriveSeed(world.seed,`civil-settle:${c.id}:${world.date}`)),award=settleCivilMutable(world,c,world.date,.38+rng.next()*.22);world.events.unshift(event(world.date,'Civil case settled',`The case settled for ${award.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}.`,'medium'));}else{c.status='trial';c.legalCost=money(c.legalCost+1800);chargePlayer(world,1800,world.date,'Civil trial legal costs');world.events.unshift(event(world.date,'Civil case set for trial','The case will be decided later. The outcome is uncertain and legal costs have increased.','medium'));}return world;}
function processCivil(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const c of world.civilCases.filter(c=>!['settled','judgment','dismissed'].includes(c.status))){const age=daysBetween(c.filedDate,date);if(c.status==='filed'&&age>=10){c.status='negotiating';if(c.plaintiffId===world.character.id||c.defendantId===world.character.id)events.push(event(date,'A civil case entered negotiation','The parties can settle or continue toward trial.','medium'));continue;}if(c.status==='trial'&&age>=35){const plaintiffChance=clamp(.42+(rng.next()-.5)*.28,.12,.82);c.outcomeDate=date;if(rng.chance(plaintiffChance)){c.status='judgment';c.amountAwarded=money(c.amountClaimed*(.45+rng.next()*.45));if(c.plaintiffId===world.character.id)creditPlayer(world,c.amountAwarded,date,'Civil judgment received');else if(c.defendantId===world.character.id)chargePlayer(world,c.amountAwarded,date,'Civil judgment paid');if(c.plaintiffId===world.character.id||c.defendantId===world.character.id)events.push(event(date,'Civil judgment entered',`The court awarded ${c.amountAwarded.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}.`,'major'));}else{c.status='dismissed';if(c.plaintiffId===world.character.id||c.defendantId===world.character.id)events.push(event(date,'Civil claim dismissed','The court ended the claim without an award.','medium'));}}}}
export function simulateLegal(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{initializeLegacyLegal(world,date);const events:LifeEvent[]=[];processRelease(world,date,events);backgroundCrime(world,date,rng,events);processInvestigations(world,date,rng,events);processCriminalCases(world,date,rng,events);processCivil(world,date,rng,events);return events;}
