import type { LifeEvent, WorldState } from '../types/game';
import type { FoodStrategy, HobbyKind, HomeUpgradeKind, LifestyleMilestone, ServiceKind, StyleIdentity } from '../types/lifestyle';
import { SeededRng } from './rng';
import { deriveSeed } from './humanEngine';
import { activeHouseholdForPerson } from './householdEngine';
import { initializeLifestyle } from './lifestyleSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const DAY=86_400_000;
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function yearsBetween(from:string,to:string){return Math.max(0,(new Date(`${to}T12:00:00Z`).getTime()-new Date(`${from}T12:00:00Z`).getTime())/(365.25*DAY));}
function checking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open')??world.financialAccounts.find(a=>a.type==='checking'&&a.ownerIds.includes(world.character.id)&&a.status==='open');}
function syncCash(world:WorldState){const a=checking(world);if(a)world.character.cash=Math.round(a.balance*100)/100;}
function spend(world:WorldState,amount:number,description:string,category:string,date=world.date){const a=checking(world);if(!a||amount<=0||a.balance<amount)return false;a.balance-=amount;world.ledger.unshift({id:`lifestyle-${description.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${date}-${world.ledger.length}`,date,description,amount:-Math.round(amount*100)/100,category});syncCash(world);return true;}
function addMilestone(world:WorldState,m:LifestyleMilestone){world.lifestyleMilestones.unshift(m);world.memories.unshift({id:`mem-${m.id}`,date:m.date,title:m.title,summary:m.summary,significance:m.significance});}
function profile(world:WorldState){return initializeLifestyle(world).lifestyleProfiles.find(p=>p.personId===world.character.id)!;}
function relationshipBump(world:WorldState,ids:string[],amount:number,date:string){for(const id of ids.filter(id=>id!==world.character.id)){for(const r of world.relationships.filter(r=>(r.fromId===world.character.id&&r.toId===id)||(r.fromId===id&&r.toId===world.character.id))){r.affection=clamp(r.affection+amount);r.familiarity=clamp(r.familiarity+Math.abs(amount)*.5);r.lastMeaningfulContactDate=date;}}}
function groceryMultiplier(strategy:FoodStrategy){return{budget:.78,standard:1,healthy:1.12,premium:1.42,convenience:1.28}[strategy];}
function homeCapacity(homeType:string){return{apartment:2,townhome:4,house:5,shared:2,temporary:1}[homeType]??2;}

export function setFoodStrategy(input:WorldState,strategy:FoodStrategy):WorldState{const world=initializeLifestyle(structuredClone(input)),p=profile(world);p.foodStrategy=strategy;p.lastUpdatedDate=world.date;return world;}
export function setStyleIdentity(input:WorldState,style:StyleIdentity):WorldState{const world=initializeLifestyle(structuredClone(input)),p=profile(world);p.styleIdentity=style;p.lastUpdatedDate=world.date;addMilestone(world,{id:`milestone-style-${world.date}`,personId:world.character.id,date:world.date,category:'style',title:'A new personal style',summary:`Your everyday presentation shifted toward a ${style.replace('_',' ')} style.`,significance:38});return world;}
export function improveHome(input:WorldState,kind:HomeUpgradeKind):WorldState{const world=initializeLifestyle(structuredClone(input)),h=activeHouseholdForPerson(world,world.character.id);if(!h)return world;const home=world.homeLifestyles.find(x=>x.householdId===h.id);if(!home)return world;const config={furniture:['Furniture refresh',900,9],appliance:['Appliance upgrade',1150,7],decor:['Decor refresh',450,6],office:['Home office setup',800,7],fitness:['Home fitness setup',650,6],entertainment:['Entertainment setup',750,6],child_space:['Child space upgrade',700,8]}[kind] as [string,number,number];if(!spend(world,config[1],config[0],'Household'))return world;const id=`upgrade-${kind}-${world.date}-${world.homeUpgrades.length}`;world.homeUpgrades.push({id,householdId:h.id,kind,name:config[0],purchaseDate:world.date,purchaseCost:config[1],condition:100,comfortImpact:config[2],active:true});home.upgradeIds.push(id);home.comfort=clamp(home.comfort+config[2]);home.furnishingQuality=clamp(home.furnishingQuality+Math.ceil(config[2]/2));addMilestone(world,{id:`milestone-${id}`,personId:world.character.id,date:world.date,category:'home',title:config[0],summary:`You invested ${config[1].toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})} in your household.`,significance:42});return world;}
export function startHobby(input:WorldState,kind:HobbyKind,name=kind.replace('_',' ')):WorldState{const world=initializeLifestyle(structuredClone(input));if(world.hobbies.some(h=>h.personId===world.character.id&&h.kind===kind&&h.active))return world;const costs:Record<HobbyKind,number>={fitness:35,gaming:30,music:25,art:22,cooking:18,reading:12,outdoors:20,community:8,photography:28,sports:40};world.hobbies.push({id:`hobby-${world.character.id}-${kind}-${world.date}`,personId:world.character.id,kind,name:name.replace(/^./,c=>c.toUpperCase()),skill:18,enjoyment:66,socialPotential:['community','sports','fitness','music'].includes(kind)?65:32,monthlyCost:costs[kind],lastPracticedDate:null,active:true});addMilestone(world,{id:`milestone-hobby-${kind}-${world.date}`,personId:world.character.id,date:world.date,category:'hobby',title:`Started ${name}`,summary:`A new hobby entered your weekly life: ${name}.`,significance:35});return world;}
export function practiceHobby(input:WorldState,hobbyId:string):WorldState{const world=initializeLifestyle(structuredClone(input)),h=world.hobbies.find(x=>x.id===hobbyId&&x.personId===world.character.id&&x.active);if(!h)return world;h.skill=clamp(h.skill+.8);h.enjoyment=clamp(h.enjoyment+.2);h.lastPracticedDate=world.date;world.character.human.needs.recreation=clamp(world.character.human.needs.recreation+9);world.character.stress=clamp(world.character.stress-3);if(h.kind==='fitness')world.character.human.health.fitness=clamp(world.character.human.health.fitness+1.2);return world;}
export function dineOut(input:WorldState,companionIds:string[]=[],kind:'restaurant'|'date'|'family_meal'|'nightlife'|'community'|'entertainment'|'outdoors'='restaurant'):WorldState{const world=initializeLifestyle(structuredClone(input)),p=profile(world),cost=Math.round((kind==='nightlife'?70:kind==='date'?85:kind==='family_meal'?62:48)*(1+p.socialSpending/140));if(!spend(world,cost,kind==='restaurant'?'Restaurant outing':`${kind.replace('_',' ')} outing`,'Dining'))return world;const people=[world.character.id,...companionIds],satisfaction=clamp(58+p.human?.needs?.recreation??68);world.lifestyleOutings.unshift({id:`outing-${world.date}-${world.lifestyleOutings.length}`,date:world.date,personIds:people,kind,venue:kind==='outdoors'?'Local outdoor destination':'Local venue',cost,satisfaction:Math.round(60+p.socialSpending*.2)});relationshipBump(world,companionIds,2.2,world.date);world.character.human.needs.recreation=clamp(world.character.human.needs.recreation+8);world.character.human.needs.socialConnection=clamp(world.character.human.needs.socialConnection+(companionIds.length?7:1));return world;}
export function adoptPet(input:WorldState,species:'dog'|'cat'|'bird'|'small_pet',name:string):WorldState{const world=initializeLifestyle(structuredClone(input)),home=activeHouseholdForPerson(world,world.character.id);if(!home||!name.trim())return world;const fee={dog:350,cat:250,bird:180,small_pet:120}[species];if(!spend(world,fee,`Adopted ${name.trim()}`,'Pet'))return world;const attachments:Record<string,number>={};for(const id of home.memberIds)attachments[id]=id===world.character.id?72:58;world.pets.push({id:`pet-${species}-${world.date}-${world.pets.length}`,householdId:home.id,name:name.trim(),species,birthDate:addDays(world.date,-Math.round(365*(species==='dog'||species==='cat'?1.5:.7))),adoptedDate:world.date,health:86,training:species==='dog'?42:55,attachmentByPerson:attachments,monthlyCost:{dog:95,cat:70,bird:40,small_pet:30}[species],status:'alive',deathDate:null});addMilestone(world,{id:`milestone-pet-${world.date}-${world.pets.length}`,personId:world.character.id,date:world.date,category:'pet',title:`${name.trim()} joined the household`,summary:`You adopted a ${species.replace('_',' ')} named ${name.trim()}.`,significance:68});return world;}
export function subscribeHouseholdService(input:WorldState,kind:ServiceKind):WorldState{const world=initializeLifestyle(structuredClone(input)),home=activeHouseholdForPerson(world,world.character.id);if(!home||world.householdServices.some(s=>s.householdId===home.id&&s.kind===kind&&s.active))return world;const cfg:Record<ServiceKind,[number,number,string]>={cleaning:[180,7,'BrightHome Cleaning'],childcare:[900,28,'Neighborhood Childcare'],meal_service:[280,9,'Weeknight Kitchen'],landscaping:[120,4,'GreenLine Yard Care'],assistant:[450,12,'Personal Admin Co.'],pet_care:[160,5,'Companion Pet Care']};const [monthlyCost,timeSavedHours,providerName]=cfg[kind];world.householdServices.push({id:`service-${home.id}-${kind}`,householdId:home.id,kind,providerName,monthlyCost,timeSavedHours,active:true,startedDate:world.date});return world;}
export function cancelHouseholdService(input:WorldState,serviceId:string):WorldState{const world=initializeLifestyle(structuredClone(input)),s=world.householdServices.find(x=>x.id===serviceId);if(s)s.active=false;return world;}
export function buyDevice(input:WorldState,kind:'phone'|'computer'|'tablet'|'tv'|'game_console'):WorldState{const world=initializeLifestyle(structuredClone(input));const cfg={phone:['Smartphone',850,86],computer:['Laptop',1200,88],tablet:['Tablet',650,82],tv:['Smart TV',700,80],game_console:['Game console',500,84]}[kind] as [string,number,number];if(!spend(world,cfg[1],cfg[0],'Technology'))return world;for(const d of world.deviceAssets.filter(d=>d.ownerId===world.character.id&&d.kind===kind&&d.status==='active'))d.status='replaced';world.deviceAssets.push({id:`device-${world.character.id}-${kind}-${world.date}`,ownerId:world.character.id,kind,name:cfg[0],purchaseDate:world.date,purchasePrice:cfg[1],condition:100,capability:cfg[2],status:'active'});addMilestone(world,{id:`milestone-device-${kind}-${world.date}`,personId:world.character.id,date:world.date,category:'technology',title:`New ${cfg[0]}`,summary:`You replaced or added a ${cfg[0].toLowerCase()} to your everyday life.`,significance:28});return world;}
export function planTravel(input:WorldState,destination:string,startDate:string,durationDays:number,companionIds:string[]=[],lodging:'budget'|'standard'|'premium'|'luxury'='standard',purpose:'vacation'|'family'|'romantic'|'business'|'sports'='vacation'):WorldState{const world=initializeLifestyle(structuredClone(input));if(!destination.trim()||startDate<world.date)return world;const days=Math.max(1,Math.min(21,Math.round(durationDays))),base={budget:110,standard:190,premium:340,luxury:650}[lodging],budget=Math.round(days*base+320+companionIds.length*days*55),ids=[world.character.id,...companionIds];world.travelPlans.push({id:`travel-${world.date}-${world.travelPlans.length}`,travelerIds:ids,origin:world.character.location,destination:destination.trim(),startDate,endDate:addDays(startDate,days-1),lodging,purpose,budget,spent:0,status:'planned',satisfaction:null});const home=activeHouseholdForPerson(world,world.character.id);world.calendarCommitments.push({id:`calendar-travel-${world.travelPlans.length}`,householdId:home?.id??null,personId:world.character.id,date:startDate,startHour:6,endHour:23,label:`Travel to ${destination.trim()}`,category:'travel',priority:85,status:'planned'});return world;}
export function serviceVehicle(input:WorldState,vehicleId:string):WorldState{const world=initializeLifestyle(structuredClone(input)),v=world.vehicles.find(x=>x.id===vehicleId&&x.status==='owned'),use=world.vehicleUseProfiles.find(x=>x.vehicleId===vehicleId);if(!v||!use)return world;const cost=Math.round(140+(100-v.condition)*7);if(!spend(world,cost,`Vehicle service · ${v.description}`,'Transportation'))return world;v.condition=clamp(v.condition+18);use.reliability=clamp(use.reliability+22);use.lastServiceDate=world.date;use.nextServiceMileage=v.mileage+5000;return world;}

function syncFoodCosts(world:WorldState){const p=profile(world),home=activeHouseholdForPerson(world,world.character.id);if(!home)return;const obligation=world.recurringObligations.find(o=>o.householdId===home.id&&o.category==='Groceries'&&o.active);if(obligation){const members=Math.max(1,home.memberIds.length);obligation.amount=Math.round((95+members*42)*groceryMultiplier(p.foodStrategy));}}
function updateHome(world:WorldState,date:string){const home=activeHouseholdForPerson(world,world.character.id);if(!home)return;const state=world.homeLifestyles.find(x=>x.householdId===home.id);if(!state)return;const members=home.memberIds.length,capacity=homeCapacity(home.homeType);state.spacePressure=clamp(Math.max(0,(members-capacity)*22+(members>state.bedrooms*1.5?12:0)));state.privacy=clamp(72-state.spacePressure*.45);state.maintenance=clamp(state.maintenance-.025);state.organization=clamp(state.organization-.04+world.character.traits.discipline*.0005);if(state.spacePressure>55){world.character.stress=clamp(world.character.stress+.12);world.character.human.needs.autonomy=clamp(world.character.human.needs.autonomy-.1);}for(const u of world.homeUpgrades.filter(u=>u.householdId===home.id&&u.active))u.condition=clamp(u.condition-.015);if(Number(date.slice(-2))===1&&state.maintenance<45){const cost=Math.round(180+(50-state.maintenance)*18);if(spend(world,cost,'Home maintenance','Household',date)){state.maintenance=clamp(state.maintenance+18);state.lastMaintenanceDate=date;}}}
function updateVehicle(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const v of world.vehicles.filter(v=>v.status==='owned'&&v.ownerIds.includes(world.character.id))){let use=world.vehicleUseProfiles.find(x=>x.vehicleId===v.id);if(!use){initializeLifestyle(world);use=world.vehicleUseProfiles.find(x=>x.vehicleId===v.id);}if(!use)continue;const weekday=new Date(`${date}T12:00:00Z`).getUTCDay(),miles=weekday>=1&&weekday<=5?22:8;v.mileage+=miles;v.condition=clamp(v.condition-.018-miles/50000);use.reliability=clamp(use.reliability-.012-miles/60000);if(v.mileage>=use.nextServiceMileage)use.reliability=clamp(use.reliability-.08);const risk=Math.max(0,(55-use.reliability)/9000+(35-v.condition)/7000);if(rng.chance(risk)){use.breakdowns++;use.reliability=clamp(use.reliability-12);v.condition=clamp(v.condition-7);const repair=Math.round(220+(100-use.reliability)*11);spend(world,repair,`Vehicle repair · ${v.description}`,'Transportation',date);events.push({id:`evt-vehicle-breakdown-${v.id}-${date}`,date,title:'Your vehicle broke down',body:`${v.description} needed an unexpected repair. Reliability and transportation costs are starting to matter.`,type:'finance',priority:'medium'});}}}
function updateDevices(world:WorldState,date:string,events:LifeEvent[]){for(const d of world.deviceAssets.filter(d=>d.status==='active')){d.condition=clamp(d.condition-.018);if(d.condition<12){d.status='broken';if(d.ownerId===world.character.id)events.push({id:`evt-device-broke-${d.id}-${date}`,date,title:`Your ${d.kind} stopped working`,body:`${d.name} reached the end of its useful life. Replacing it would restore convenience and capability.`,type:'routine',priority:'medium'});}}}
function updatePets(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const pet of world.pets.filter(p=>p.status==='alive')){const age=yearsBetween(pet.birthDate,date),senior=pet.species==='dog'||pet.species==='cat'?age>11:age>7;pet.health=clamp(pet.health-(senior?.025:.006));if(Number(date.slice(-2))===1){spend(world,pet.monthlyCost,`${pet.name} care`,'Pet',date);}const mortality=Math.max(0,(senior?(age-10)*.000035:0)+(pet.health<25?(25-pet.health)*.00006:0));if(rng.chance(mortality)){pet.status='deceased';pet.deathDate=date;const attached=pet.attachmentByPerson[world.character.id]??0;world.character.stress=clamp(world.character.stress+attached*.12);events.push({id:`evt-pet-death-${pet.id}-${date}`,date,title:`${pet.name} died`,body:`${pet.name} had become part of the household. The loss is felt differently by each person who was attached.`,type:'relationship',priority:'major'});addMilestone(world,{id:`milestone-pet-loss-${pet.id}`,personId:world.character.id,date,category:'pet',title:`Said goodbye to ${pet.name}`,summary:`${pet.name} died after being part of the household.`,significance:76});}}}
function updateTravel(world:WorldState,date:string,rng:SeededRng,events:LifeEvent[]){for(const trip of world.travelPlans){if(trip.status==='planned'&&trip.startDate===date){if(!spend(world,trip.budget,`Travel · ${trip.destination}`,'Travel',date)){trip.status='cancelled';events.push({id:`evt-trip-cancel-${trip.id}`,date,title:'Travel plans fell through',body:`The planned trip to ${trip.destination} could not be funded from current cash.`,type:'finance',priority:'medium'});continue;}trip.status='active';trip.spent=trip.budget;events.push({id:`evt-trip-start-${trip.id}`,date,title:`Trip to ${trip.destination}`,body:`You left ${trip.origin} for ${trip.destination}. Travel changes time, money and relationships at the same time.`,type:'routine',priority:'medium'});}if(trip.status==='active'&&trip.endDate===date){trip.status='completed';const p=profile(world),satisfaction=clamp(58+p.travelInterest*.25+(rng.next()-.5)*16);trip.satisfaction=Math.round(satisfaction);relationshipBump(world,trip.travelerIds.filter(id=>id!==world.character.id),(satisfaction-50)/18,date);world.character.human.needs.recreation=clamp(world.character.human.needs.recreation+12);addMilestone(world,{id:`milestone-trip-${trip.id}`,personId:world.character.id,date,category:'travel',title:`Returned from ${trip.destination}`,summary:`The ${trip.purpose} trip ended with ${satisfaction>=72?'strong memories':satisfaction>=52?'a generally positive experience':'mixed feelings'}.`,significance:62});}}}
function updateServices(world:WorldState,date:string){if(Number(date.slice(-2))!==1)return;const home=activeHouseholdForPerson(world,world.character.id);if(!home)return;let saved=0;for(const s of world.householdServices.filter(s=>s.householdId===home.id&&s.active)){if(spend(world,s.monthlyCost,`${s.kind.replace('_',' ')} service`,'Subscription',date))saved+=s.timeSavedHours;}const p=profile(world);p.timePressure=clamp(p.timePressure-saved*.35);}
function updateCalendar(world:WorldState,date:string,events:LifeEvent[]){const entries=world.calendarCommitments.filter(c=>c.personId===world.character.id&&c.date===date&&c.status==='planned').sort((a,b)=>a.startHour-b.startHour);for(let i=0;i<entries.length;i++){const a=entries[i]!;const conflict=entries.slice(i+1).find(b=>b.startHour<a.endHour&&b.endHour>a.startHour);if(conflict){const miss=a.priority<conflict.priority?a:conflict;miss.status='missed';events.push({id:`evt-calendar-conflict-${miss.id}`,date,title:'Your schedule collided',body:`${miss.label} conflicted with another commitment. Time is finite, and one plan was missed.`,type:'routine',priority:'medium'});}}for(const c of entries.filter(e=>e.status==='planned'))c.status='completed';const p=profile(world),base=entries.reduce((s,e)=>s+(e.endHour-e.startHour),0);p.timePressure=clamp(p.timePressure*.85+base*4.5);if(p.timePressure>75)world.character.stress=clamp(world.character.stress+.4);}
function updateFoodAndHobbies(world:WorldState,date:string){const p=profile(world);if(new Date(`${date}T12:00:00Z`).getUTCDay()===0){const home=activeHouseholdForPerson(world,world.character.id),familyMeals=home&&home.memberIds.length>1&&p.familyMealFrequency>50?1:0;if(familyMeals){world.lifestyleOutings.unshift({id:`outing-family-${date}`,date,personIds:home!.memberIds,kind:'family_meal',venue:'Home',cost:0,satisfaction:Math.round(58+p.cookingSkill*.25)});relationshipBump(world,home!.memberIds.filter(id=>id!==world.character.id),1.1,date);}if(p.foodStrategy==='healthy')world.character.human.health.physicalCondition=clamp(world.character.human.health.physicalCondition+.18);if(p.foodStrategy==='convenience')p.timePressure=clamp(p.timePressure-2);for(const h of world.hobbies.filter(h=>h.personId===world.character.id&&h.active)){if(h.lastPracticedDate!==date&&world.character.human.needs.recreation<55){h.skill=clamp(h.skill+.16);h.lastPracticedDate=date;world.character.human.needs.recreation=clamp(world.character.human.needs.recreation+4);}}}}
export function simulateLifestyle(input:WorldState,date:string,rng:SeededRng):LifeEvent[]{const world=initializeLifestyle(input),events:LifeEvent[]=[];syncFoodCosts(world);updateHome(world,date);updateVehicle(world,date,rng,events);updateDevices(world,date,events);updatePets(world,date,rng,events);updateTravel(world,date,rng,events);updateServices(world,date);updateCalendar(world,date,events);updateFoodAndHobbies(world,date);for(const p of world.lifestyleProfiles)p.lastUpdatedDate=date;world.lifestyleOutings=world.lifestyleOutings.slice(0,240);world.calendarCommitments=world.calendarCommitments.filter(c=>c.date>=addDays(date,-60));return events;}
export function lifestyleRng(world:WorldState,date=world.date){return new SeededRng(deriveSeed(world.seed,`lifestyle:${date}`));}
