import type { LifeEvent, WorldState } from '../types/game';
import type { RegionalShock, WorldNewsItem } from '../types/livingWorld';
import { SeededRng } from './rng';
import { refreshHouseholdFinance } from './financeSeed';
import { initializeLivingWorld } from './livingWorldSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const round2=(v:number)=>Math.round(v*100)/100;
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function checking(world:WorldState){return world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open')??world.financialAccounts.find(a=>a.type==='checking'&&a.ownerIds.includes(world.character.id)&&a.status==='open');}
function spend(world:WorldState,amount:number,description:string,date=world.date){const a=checking(world);if(!a||a.balance<amount)return false;a.balance=round2(a.balance-amount);world.character.cash=a.balance;world.ledger.unshift({id:`world-${description.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${date}`,date,description,amount:-amount,category:'Moving'});return true;}
export function currentCity(world:WorldState){return world.cities.find(c=>c.id===world.currentCityId)??null;}
export function currentCountry(world:WorldState){const city=currentCity(world);return city?world.countries.find(c=>c.id===city.countryId)??null:null;}
export function currentNeighborhood(world:WorldState){return world.neighborhoods.find(n=>n.id===world.currentNeighborhoodId)??null;}
function cityShock(world:WorldState,cityId:string){const countryId=world.cities.find(c=>c.id===cityId)?.countryId;return world.regionalShocks.filter(s=>s.status!=='resolved'&&(s.locationType==='global'||(s.locationType==='city'&&s.locationId===cityId)||(s.locationType==='country'&&s.locationId===countryId)));}
function shockLabel(kind:RegionalShock['kind']){return kind.replace('_',' ');}
function addNews(world:WorldState,item:WorldNewsItem){if(world.worldNews.some(n=>n.id===item.id))return;world.worldNews.unshift(item);world.worldNews=world.worldNews.slice(0,240);}
function addHistory(world:WorldState,id:string,date:string,kind:'policy'|'company'|'migration'|'institution'|RegionalShock['kind'],locationId:string|null,title:string,summary:string,importance:number){if(world.worldHistory.some(h=>h.id===id))return;world.worldHistory.unshift({id,date,kind,locationId,title,summary,importance});world.worldHistory=world.worldHistory.slice(0,700);}
function syncLocalMirrors(world:WorldState){const city=currentCity(world),hood=currentNeighborhood(world);if(!city)return;const shocks=cityShock(world,city.id),employmentImpact=shocks.reduce((s,x)=>s+x.employmentImpact*x.severity/100,0),housingImpact=shocks.reduce((s,x)=>s+x.housingImpact*x.severity/100,0);world.economy.unemploymentRate=round2(clamp(city.unemploymentRate+employmentImpact,2,25));world.economy.housingIndex=Math.max(.45,round2((hood?.housingCostIndex??city.housingIndex)*(1+housingImpact/100)));world.laborMarket.wageIndex=round2(city.wageIndex);world.laborMarket.demandIndex=Math.round(clamp(72-city.unemploymentRate*3-employmentImpact*2+city.growthRate*4,15,95));}
function updateIndustries(world:WorldState,date:string,rng:SeededRng){for(const industry of world.industries){const affected=world.regionalShocks.filter(s=>s.status!=='resolved'&&(s.kind==='recession'||s.kind==='technology_shift'||s.kind==='labor_shortage'||s.kind==='supply_disruption'));let modifier=0;for(const s of affected){if(s.kind==='recession')modifier-=s.severity*.015;if(s.kind==='labor_shortage')modifier+=s.severity*.01;if(s.kind==='technology_shift')industry.automationPressure=clamp(industry.automationPressure+s.severity*.006);if(s.kind==='supply_disruption'&&industry.id.includes('logistics'))modifier+=s.severity*.012;}industry.growth=round2(clamp(industry.growth+(rng.next()-.5)*.22+modifier,-8,8));industry.demandIndex=round2(clamp(industry.demandIndex+industry.growth*.08+(rng.next()-.5)*.8,15,98));industry.wageIndex=round2(clamp(industry.wageIndex+(industry.demandIndex-60)/6000,.55,1.8));industry.lastUpdatedDate=date;}}
function updateCompanies(world:WorldState,date:string,rng:SeededRng){for(const company of world.companyWorldStates){const employer=world.employers.find(e=>e.id===company.employerId);if(!employer)continue;const industries=world.industries.filter(i=>company.cityIds.some(c=>i.cityIds.includes(c))&&employer.industry.toLowerCase().split(' ').some(word=>word.length>4&&i.name.toLowerCase().includes(word)));const industry=industries[0];const trend=(industry?.growth??0)*.18+(rng.next()-.5)*1.6;company.growth=round2(clamp(company.growth*.7+trend,-10,10));company.health=round2(clamp(company.health+company.growth*.08+(rng.next()-.5)*.5,0,100));company.headcountIndex=round2(Math.max(0,company.headcountIndex*(1+company.growth/100/12)));const prior=company.status;company.status=company.health<12?'failed':company.growth>2.4?'growing':company.growth<-.9?'contracting':'stable';company.lastUpdatedDate=date;employer.stability=Math.round(company.health);employer.wageIndex=round2(clamp(employer.wageIndex+(company.growth/1000),.65,1.6));if(company.status!==prior&&(company.status==='failed'||company.status==='contracting'||company.status==='growing')){const title=company.status==='failed'?`${employer.name} shuts down`:company.status==='contracting'?`${employer.name} begins cutting back`:`${employer.name} is expanding`;const summary=company.status==='failed'?`${employer.name} failed after sustained financial pressure.`:company.status==='contracting'?`${employer.name} is reducing activity and headcount as conditions weaken.`:`${employer.name} is expanding hiring and activity.`;addNews(world,{id:`news-company-${company.id}-${date}`,date,scope:'business',locationId:company.cityIds[0]??null,title,summary,sourceId:company.id,importance:company.status==='failed'?86:62});addHistory(world,`history-company-${company.id}-${date}`,date,'company',company.cityIds[0]??null,title,summary,company.status==='failed'?88:64);}}}
function updateCities(world:WorldState,date:string,rng:SeededRng){for(const city of world.cities){const shocks=cityShock(world,city.id);const economic=shocks.reduce((s,x)=>s+x.economicImpact*x.severity/100,0),housing=shocks.reduce((s,x)=>s+x.housingImpact*x.severity/100,0),employment=shocks.reduce((s,x)=>s+x.employmentImpact*x.severity/100,0);const cityIndustries=world.industries.filter(i=>city.industryIds.includes(i.id)),growth=cityIndustries.length?cityIndustries.reduce((s,i)=>s+i.growth,0)/cityIndustries.length:0;city.growthRate=round2(clamp(city.growthRate*.72+growth*.2-economic*.08+(rng.next()-.5)*.18,-4,5));city.population=Math.max(1000,Math.round(city.population*(1+city.growthRate/100/12)));city.unemploymentRate=round2(clamp(city.unemploymentRate-growth*.015+employment*.03+(rng.next()-.5)*.05,2,24));city.wageIndex=round2(clamp(city.wageIndex+(growth-economic)/9000,.45,2));city.housingIndex=round2(clamp(city.housingIndex*(1+(city.growthRate+housing*.2)/100/12),.4,3));}}
function updateInstitutions(world:WorldState,date:string){for(const i of world.worldInstitutions){const city=world.cities.find(c=>c.id===i.cityId);if(!city)continue;const shocks=cityShock(world,city.id),infra=shocks.reduce((s,x)=>s+x.infrastructureImpact*x.severity/100,0);i.quality=round2(clamp(i.quality-infra*.012+(city.growthRate>2?-.03:.02),15,100));i.status=infra>25?'strained':i.quality<28?'strained':'open';i.lastUpdatedDate=date;if(i.status==='strained'&&!world.worldNews.some(n=>n.sourceId===i.id&&n.date===date)){const title=`${i.name} is under strain`,summary='Capacity and service quality are being pressured by current local conditions.';addNews(world,{id:`news-institution-${i.id}-${date}`,date,scope:'local',locationId:city.id,title,summary,sourceId:i.id,importance:58});}}}
function advanceShocks(world:WorldState,date:string){for(const s of world.regionalShocks){if(s.status==='active'&&s.endDate&&date>=s.endDate){s.status='recovering';s.endDate=null;}else if(s.status==='recovering'){s.severity=round2(Math.max(0,s.severity-3));if(s.severity<=5){s.status='resolved';const title=`Recovery from ${shockLabel(s.kind)}`,summary='The immediate disruption has faded, although its longer-term consequences remain in the world state.';addHistory(world,`history-recovery-${s.id}`,date,s.kind,s.locationId,title,summary,60);}}}}
function maybeShock(world:WorldState,date:string,rng:SeededRng){const shockMultiplier=world.gameConfiguration?.rules.worldShockMultiplier??1;if(!rng.chance(clamp(.035*shockMultiplier,0,.18)))return;const pressure=world.gameConfiguration?.rules.economicPressureMultiplier??1,city=world.cities[Math.floor(rng.next()*world.cities.length)]!,kinds:RegionalShock['kind'][]=['recession','housing_boom','housing_correction','disaster','supply_disruption','labor_shortage','technology_shift','strike'],kind=kinds[Math.floor(rng.next()*kinds.length)]!,severity=Math.round(clamp((28+rng.next()*55)*pressure,20,96)),positive=kind==='housing_boom'||kind==='labor_shortage';const duration=kind==='disaster'?45:kind==='strike'?30:kind==='supply_disruption'?75:180;const shock:RegionalShock={id:`shock-${kind}-${city.id}-${date}`,kind,locationType:kind==='recession'||kind==='technology_shift'?'global':'city',locationId:kind==='recession'||kind==='technology_shift'?'global':city.id,startDate:date,endDate:addDays(date,duration),severity,economicImpact:positive?-5:kind==='disaster'?18:kind==='recession'?14:6,housingImpact:kind==='housing_boom'?16:kind==='housing_correction'?-14:kind==='disaster'?-8:0,employmentImpact:kind==='labor_shortage'?-5:kind==='recession'?6:kind==='strike'?4:1,infrastructureImpact:kind==='disaster'?30:kind==='strike'?5:0,status:'active'};world.regionalShocks.unshift(shock);const place=shock.locationType==='global'?'Global economy':city.name,title=kind==='housing_boom'?`${city.name} housing demand surges`:kind==='housing_correction'?`${city.name} housing market cools`:kind==='disaster'?`Major disruption hits ${city.name}`:kind==='labor_shortage'?`Employers struggle to hire in ${city.name}`:kind==='strike'?`Labor action disrupts ${city.name}`:kind==='technology_shift'?'A major technology shift accelerates':kind==='supply_disruption'?`Supply disruption reaches ${city.name}`:'Economic conditions weaken';const summary=`${place} is experiencing a ${shockLabel(kind)} with meaningful effects on jobs, prices or infrastructure.`;addNews(world,{id:`news-${shock.id}`,date,scope:shock.locationType==='global'?'global':'local',locationId:shock.locationType==='global'?null:city.id,title,summary,sourceId:shock.id,importance:severity});addHistory(world,`history-${shock.id}`,date,kind,shock.locationType==='global'?null:city.id,title,summary,severity);}
function localMonthlyNews(world:WorldState,date:string){const city=currentCity(world);if(!city)return;const strongest=world.industries.filter(i=>city.industryIds.includes(i.id)).sort((a,b)=>b.growth-a.growth)[0];if(strongest){addNews(world,{id:`news-local-economy-${city.id}-${date.slice(0,7)}`,date,scope:'local',locationId:city.id,title:`${city.name}'s ${strongest.name} sector ${strongest.growth>=0?'grows':'slows'}`,summary:`Local demand is ${Math.round(strongest.demandIndex)}/100 while unemployment is ${city.unemploymentRate.toFixed(1)}%.`,sourceId:strongest.id,importance:45});}}

export function simulateLivingWorld(input:WorldState,date:string,rng:SeededRng):LifeEvent[]{const world=initializeLivingWorld(input),events:LifeEvent[]=[];advanceShocks(world,date);if(Number(date.slice(-2))===1){updateIndustries(world,date,rng);updateCompanies(world,date,rng);updateCities(world,date,rng);updateInstitutions(world,date);maybeShock(world,date,rng);localMonthlyNews(world,date);}syncLocalMirrors(world);const recent=world.worldNews.find(n=>n.date===date&&n.importance>=75);if((recent&&recent.locationId===world.currentCityId)||recent?.scope==='global')events.push({id:`evt-world-news-${recent!.id}`,date,title:recent!.title,body:recent!.summary,type:'world',priority:recent!.importance>=88?'major':'medium'});return events;}

export function moveToCity(input:WorldState,cityId:string,neighborhoodId?:string):WorldState{const world=initializeLivingWorld(structuredClone(input)),from=currentCity(world),to=world.cities.find(c=>c.id===cityId);if(!to||to.id===from?.id)return world;const hood=world.neighborhoods.find(n=>n.id===neighborhoodId&&n.cityId===to.id)??world.neighborhoods.find(n=>n.cityId===to.id&&n.id.endsWith('-family'))??world.neighborhoods.find(n=>n.cityId===to.id),fromCountry=from?world.countries.find(c=>c.id===from.countryId):null,toCountry=world.countries.find(c=>c.id===to.countryId)!;const international=Boolean(fromCountry&&fromCountry.id!==toCountry.id),base=international?4200:1800,pressure=world.gameConfiguration?.rules.economicPressureMultiplier??1,cost=Math.round(base*(hood?.housingCostIndex??to.housingIndex)*pressure);if(!spend(world,cost,`Move to ${to.name}`))return world;if(international){for(const r of world.residencyRecords.filter(r=>r.personId===world.character.id&&r.endDate===null))r.endDate=world.date;world.residencyRecords.push({id:`residency-${world.character.id}-${toCountry.id}-${world.date}`,personId:world.character.id,countryId:toCountry.id,kind:toCountry.immigrationOpenness>=65?'work_visa':'visitor',startDate:world.date,endDate:null});}
  world.currentCityId=to.id;world.currentNeighborhoodId=hood?.id??null;world.character.location=`${to.name}, ${to.region}`;for(const h of world.households.filter(h=>!h.endedDate&&h.memberIds.includes(world.character.id))){h.location=world.character.location;h.monthlyHousingCost=Math.round(1450*(hood?.housingCostIndex??to.housingIndex)*pressure);}
  const employment=world.employments.find(e=>e.personId===world.character.id&&e.status==='active');if(employment&&employment.remote!=='remote'){const company=world.companyWorldStates.find(c=>c.employerId===employment.employerId);if(!company?.cityIds.includes(to.id)){employment.status='ended';employment.endDate=world.date;world.character.career='Unemployed';world.events.unshift({id:`evt-relocation-job-${world.date}`,date:world.date,title:'Your move ended your current job',body:'Your role could not move with you, so relocation also became a career transition.',type:'finance',priority:'major'});}}
  refreshHouseholdFinance(world);syncLocalMirrors(world);const id=`migration-${world.character.id}-${world.date}-${world.migrationRecords.length}`;world.migrationRecords.unshift({id,personId:world.character.id,fromCityId:from?.id??null,toCityId:to.id,date:world.date,cost,reason:'player_choice'});const summary=`You moved from ${from?.name??'your prior home'} to ${to.name}, changing your housing, labor market and local institutions.`;world.memories.unshift({id:`mem-${id}`,date:world.date,title:`Moved to ${to.name}`,summary,significance:82});addHistory(world,`history-${id}`,world.date,'migration',to.id,`Moved to ${to.name}`,summary,72);world.events.unshift({id:`evt-${id}`,date:world.date,title:`A new chapter in ${to.name}`,body:summary,type:'world',priority:'major'});return world;}
