import type { AthleticSet, Character, LifeEvent, Npc, WorldState } from '../types/game';
import type { DeathCause, EstateBeneficiary } from '../types/legacyLegal';
import { SeededRng } from './rng';
import { ageAt, childrenOf } from './familyEngine';
import { initializeLegacyLegal, isDeceased } from './legacyLegalSeed';
import { initializeFinance, refreshHouseholdFinance } from './financeSeed';
import { initializeHealth } from './healthSeed';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.round(v*100)/100;
function nameFor(world:WorldState,id:string){if(id===world.character.id)return`${world.character.firstName} ${world.character.lastName}`;return world.npcs.find(n=>n.id===id)?.name??world.ancestorArchives.find(a=>a.personId===id)?.name??'Unknown person';}
function humanFor(world:WorldState,id:string){if(id===world.character.id)return world.character.human;return world.npcs.find(n=>n.id===id)?.human??null;}
function birthDateFor(world:WorldState,id:string){if(id===world.character.id)return world.character.birthDate;return world.npcs.find(n=>n.id===id)?.birthDate??world.ancestorArchives.find(a=>a.personId===id)?.birthDate??null;}
function netWorthFor(world:WorldState,personId:string){const accounts=world.financialAccounts.filter(a=>a.status==='open'&&a.ownerIds.includes(personId)).reduce((s,a)=>s+a.balance,0),properties=world.properties.filter(p=>p.status==='owned'&&p.ownerIds.includes(personId)).reduce((s,p)=>s+p.marketValue/Math.max(1,p.ownerIds.length),0),vehicles=world.vehicles.filter(v=>v.status==='owned'&&v.ownerIds.includes(personId)).reduce((s,v)=>s+v.marketValue/Math.max(1,v.ownerIds.length),0),business=world.businesses.reduce((s,b)=>s+b.valuation*(b.ownerShares.find(o=>o.personId===personId)?.share??0)/100,0),debts=world.liabilities.filter(l=>l.status!=='paid'&&l.borrowerIds.includes(personId)).reduce((s,l)=>s+l.principal,0);return money(accounts+properties+vehicles+business-debts);}
function lifeInsuranceProceeds(world:WorldState,personId:string){return money(world.insurancePolicies.filter(p=>p.kind==='life'&&p.active&&p.ownerIds.includes(personId)).reduce((s,p)=>s+p.coverageLimit,0));}
function spouseId(world:WorldState,personId:string){return world.partnerships.find(p=>p.status==='married'&&p.personIds.includes(personId))?.personIds.find(id=>id!==personId)??null;}
function directChildren(world:WorldState,personId:string){return childrenOf(world,personId).filter(c=>!isDeceased(world,c.id));}
function intestateBeneficiaries(world:WorldState,personId:string):EstateBeneficiary[]{const spouse=spouseId(world,personId),children=directChildren(world,personId);if(spouse&&children.length)return[{personId:spouse,share:50},...children.map(c=>({personId:c.id,share:50/children.length}))];if(spouse)return[{personId:spouse,share:100}];if(children.length)return children.map(c=>({personId:c.id,share:100/children.length}));const parent=world.familyLinks.find(f=>f.fromId===personId&&!f.endedDate&&['biological_child','adoptive_child'].includes(f.relation)&&!isDeceased(world,f.toId))?.toId;return parent?[{personId:parent,share:100}]:[];}
function beneficiaries(world:WorldState,personId:string){const plan=world.estatePlans.find(p=>p.personId===personId&&p.hasWill),valid=plan?.beneficiaries.filter(b=>b.share>0&&!isDeceased(world,b.personId))??[];if(!valid.length)return intestateBeneficiaries(world,personId);const total=valid.reduce((s,b)=>s+b.share,0);return valid.map(b=>({...b,share:b.share/total*100}));}
function cleanupLife(world:WorldState,personId:string,date:string){for(const e of world.employments.filter(e=>e.personId===personId&&e.status==='active')){e.status='ended';e.endDate=date;}for(const c of world.sportsContracts.filter(c=>c.personId===personId&&c.status==='active'))c.status='ended';for(const a of world.athleteProfiles.filter(a=>a.personId===personId)){a.careerStatus='retired';a.teamId=null;a.contractId=null;}for(const c of world.coachProfiles.filter(c=>c.personId===personId)){c.teamId=null;c.contractId=null;}for(const b of world.businessEmployees.filter(b=>b.personId===personId))b.active=false;for(const p of world.partnerships.filter(p=>p.personIds.includes(personId)&&!['ended','divorced'].includes(p.status))){p.status='ended';p.statusSince=date;p.history.push({id:`hist-${p.id}-death-${date}`,date,kind:'ended',summary:`${nameFor(world,personId)} died.`});}for(const h of world.households.filter(h=>!h.endedDate&&h.memberIds.includes(personId))){h.memberIds=h.memberIds.filter(id=>id!==personId);h.responsibleAdultIds=h.responsibleAdultIds.filter(id=>id!==personId);h.schedule=h.schedule.filter(s=>s.personId!==personId);const replacement=h.responsibleAdultIds[0]??h.memberIds[0];if(replacement)for(const task of h.laborAssignments)if(task.ownerId===personId)task.ownerId=replacement;if(h.memberIds.length===0)h.endedDate=date;}for(const c of world.custodyPlans.filter(c=>c.active&&c.supportPayerId===personId)){c.supportPayerId=null;c.monthlySupport=0;}for(const p of world.pregnancies.filter(p=>p.status==='ongoing'&&p.pregnantPersonId===personId)){p.status='loss';p.outcomeDate=date;}for(const m of world.medications.filter(m=>m.personId===personId&&m.active)){m.active=false;m.endDate=date;}for(const p of world.insurancePolicies.filter(p=>p.ownerIds.includes(personId)))p.active=false;}
function applyGrief(world:WorldState,personId:string,date:string){for(const edge of world.relationships.filter(r=>r.toId===personId&&r.affection>=45)){const human=humanFor(world,edge.fromId);if(!human||isDeceased(world,edge.fromId))continue;human.health.mentalLoad=clamp(human.health.mentalLoad+Math.max(4,edge.affection/12));human.needs.socialConnection=clamp(human.needs.socialConnection-5);if(!human.memories.some(m=>m.id===`humanmem-death-${personId}-${edge.fromId}`))human.memories.push({id:`humanmem-death-${personId}-${edge.fromId}`,ownerId:edge.fromId,date,kind:'relationship',summary:`${nameFor(world,edge.fromId)} remembers learning that ${nameFor(world,personId)} died.`,subjectIds:[personId],significance:96,emotionalValence:-80,strength:100,confidence:100,privacy:'private',sourceId:`death-${personId}-${date}`});}}
function creditLivingPlayerInheritance(world:WorldState,decedentId:string,distributions:{personId:string;amount:number}[],date:string){if(decedentId===world.character.id)return;const inherited=distributions.find(d=>d.personId===world.character.id)?.amount??0;if(inherited<=0)return;const checking=world.financialAccounts.find(a=>a.id==='account-checking-player'&&a.status==='open');if(!checking)return;checking.balance=money(checking.balance+inherited);world.character.cash=checking.balance;world.ledger.unshift({id:`inheritance-${decedentId}-${date}`,date,description:`Inheritance from ${nameFor(world,decedentId)}`,amount:inherited,category:'Inheritance'});}
function settleEstate(world:WorldState,personId:string,date:string){const ownedAccounts=world.financialAccounts.filter(a=>a.status==='open'&&a.ownerIds.includes(personId)),accountIds=new Set(ownedAccounts.map(a=>a.id)),grossFinancial=ownedAccounts.reduce((s,a)=>s+a.balance,0),grossProperty=world.properties.filter(p=>p.status==='owned'&&p.ownerIds.includes(personId)).reduce((s,p)=>s+p.marketValue/Math.max(1,p.ownerIds.length),0),grossVehicle=world.vehicles.filter(v=>v.status==='owned'&&v.ownerIds.includes(personId)).reduce((s,v)=>s+v.marketValue/Math.max(1,v.ownerIds.length),0),grossBusiness=world.businesses.reduce((s,b)=>s+b.valuation*(b.ownerShares.find(o=>o.personId===personId)?.share??0)/100,0),grossAssets=money(grossFinancial+grossProperty+grossVehicle+grossBusiness),liabilities=world.liabilities.filter(l=>l.status!=='paid'&&l.borrowerIds.includes(personId)),debtTotal=money(liabilities.reduce((s,l)=>s+l.principal,0)),funeralCost=Math.min(12000,Math.max(2800,Math.round(3500+grossAssets*.006))),insurance=lifeInsuranceProceeds(world,personId),heirs=beneficiaries(world,personId),cashAvailable=money(Math.max(0,grossFinancial+insurance-Math.min(debtTotal,grossFinancial+insurance)-funeralCost)),netEstate=money(Math.max(0,grossAssets+insurance-debtTotal-funeralCost));
  world.investmentPositions=world.investmentPositions.filter(p=>!accountIds.has(p.accountId));for(const a of ownedAccounts)a.balance=0;for(const l of liabilities){l.principal=0;l.status='paid';}
  const primary=heirs.slice().sort((a,b)=>b.share-a.share)[0]?.personId??null;if(primary){for(const p of world.properties.filter(p=>p.status==='owned'&&p.ownerIds.includes(personId)))p.ownerIds=[...new Set(p.ownerIds.map(id=>id===personId?primary:id))];for(const v of world.vehicles.filter(v=>v.status==='owned'&&v.ownerIds.includes(personId)))v.ownerIds=[...new Set(v.ownerIds.map(id=>id===personId?primary:id))];for(const b of world.businesses){const own=b.ownerShares.find(o=>o.personId===personId);if(!own)continue;const existing=b.ownerShares.find(o=>o.personId===primary);if(existing)existing.share+=own.share;else b.ownerShares.push({personId:primary,share:own.share});b.ownerShares=b.ownerShares.filter(o=>o.personId!==personId);}}
  const distributions=heirs.map(h=>({personId:h.personId,amount:money(cashAvailable*h.share/100)}));world.estateCases.push({id:`estate-${personId}-${date}`,decedentId:personId,openedDate:date,closedDate:date,status:'settled',grossAssets,liabilitiesPaid:Math.min(debtTotal,grossFinancial+insurance),funeralCost,lifeInsuranceProceeds:insurance,netEstate,distributions});world.funeralRecords.push({id:`funeral-${personId}-${date}`,decedentId:personId,date,cost:funeralCost,paidFromEstate:Math.min(funeralCost,Math.max(0,grossFinancial+insurance-debtTotal)),attendeeIds:world.relationships.filter(r=>r.toId===personId&&r.affection>=45&&!isDeceased(world,r.fromId)).map(r=>r.fromId).slice(0,30),summary:`Family and friends gathered to remember ${nameFor(world,personId)}.`});creditLivingPlayerInheritance(world,personId,distributions,date);return{netEstate,distributions,primary};}
function archivePerson(world:WorldState,personId:string,date:string,netWorth:number){if(world.ancestorArchives.some(a=>a.personId===personId))return;const current=personId===world.character.id,npc=current?null:world.npcs.find(n=>n.id===personId),name=current?`${world.character.firstName} ${world.character.lastName}`:npc?.name??'Unknown person',birthDate=current?world.character.birthDate:npc?.birthDate??date,career=current?world.character.career:world.employments.find(e=>e.personId===personId&&e.status==='active')?.title??npc?.role??'Unknown',location=current?world.character.location:npc?.location??'Unknown';world.ancestorArchives.push({id:`ancestor-${personId}-${date}`,personId,name,birthDate,deathDate:date,ageAtDeath:ageAt(birthDate,date),career,location,netWorthAtDeath:netWorth,childIds:directChildren(world,personId).map(c=>c.id),summary:`${name}'s life became part of the family history on ${date}.`});}
function mortalityChance(world:WorldState,personId:string,date:string){const bd=birthDateFor(world,personId);if(!bd)return 0;const age=ageAt(bd,date),human=humanFor(world,personId);if(!human)return 0;const annual=age<18?.0002:age<40?.0008:age<55?.002:age<65?.006:age<75?.018:age<85?.055:.14,conditions=world.medicalConditions.filter(c=>c.personId===personId&&c.status!=='resolved'),illness=conditions.filter(c=>c.kind==='chronic'||c.kind==='acute').reduce((s,c)=>s+c.severity,0),injury=conditions.filter(c=>c.kind==='injury').reduce((s,c)=>s+c.severity,0),healthMultiplier=clamp(1+(100-human.health.physicalCondition)/55+illness/120+injury/140,.6,6);return Math.min(.02,annual/365*healthMultiplier+(injury>85?.001:0));}
function chooseCause(world:WorldState,personId:string,date:string,rng:SeededRng):DeathCause{const active=world.medicalConditions.filter(c=>c.personId===personId&&c.status!=='resolved').sort((a,b)=>b.severity-a.severity),top=active[0];if(top?.kind==='injury')return'injury';if(top&&top.severity>=58)return'illness';const bd=birthDateFor(world,personId),age=bd?ageAt(bd,date):0;if(age>=80&&rng.chance(.7))return'natural_age';return rng.chance(.55)?'accident':'other';}
export function recordDeathMutable(world:WorldState,personId:string,date:string,cause:DeathCause,unexpected=true):LifeEvent|null{initializeLegacyLegal(world,date);if(isDeceased(world,personId))return null;const bd=birthDateFor(world,personId);if(!bd)return null;const age=ageAt(bd,date),name=nameFor(world,personId),netWorth=netWorthFor(world,personId),controlled=personId===world.character.id;world.deathRecords.push({id:`death-${personId}-${date}`,personId,date,age,cause,summary:`${name} died at age ${age}.`,unexpected});archivePerson(world,personId,date,netWorth);applyGrief(world,personId,date);settleEstate(world,personId,date);cleanupLife(world,personId,date);if(!controlled)world.npcs=world.npcs.filter(n=>n.id!==personId);world.memories.unshift({id:`mem-death-${personId}-${date}`,date,title:`${name} died`,summary:`${name} died at age ${age}. The world and family continue.`,significance:100});return{id:`evt-death-${personId}-${date}`,date,title:controlled?'Your life has ended':`${name} died`,body:controlled?'Your life is now part of the family history. Choose an eligible descendant to continue this world.':`${name}'s death changes their family, relationships and estate.`,type:'health',priority:'major'};}
export function simulateMortality(world:WorldState,date:string,rng:SeededRng):LifeEvent[]{initializeLegacyLegal(world,date);const events:LifeEvent[]=[];const people=[world.character.id,...world.npcs.filter(n=>n.tier===1&&n.human&&!isDeceased(world,n.id)).map(n=>n.id)];for(const personId of people){if(isDeceased(world,personId)||!rng.chance(mortalityChance(world,personId,date)))continue;const evt=recordDeathMutable(world,personId,date,chooseCause(world,personId,date,rng),true);if(evt)events.push(evt);if(personId===world.character.id)break;}return events;}
export function forceDeath(input:WorldState,personId=input.character.id,cause:DeathCause='other'):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const evt=recordDeathMutable(world,personId,world.date,cause,cause!=='natural_age');if(evt)world.events.unshift(evt);return world;}
export function setEstatePlan(input:WorldState,beneficiaryIds:string[]):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const ids=[...new Set(beneficiaryIds)].filter(id=>id!==world.character.id&&!isDeceased(world,id));if(!ids.length)return world;const beneficiaries=ids.map(personId=>({personId,share:100/ids.length})),existing=world.estatePlans.find(p=>p.personId===world.character.id);if(existing){existing.hasWill=true;existing.beneficiaries=beneficiaries;existing.lastUpdatedDate=world.date;existing.executorId=ids[0]??null;}else world.estatePlans.push({id:`estate-plan-${world.character.id}`,personId:world.character.id,hasWill:true,executorId:ids[0]??null,beneficiaries,createdDate:world.date,lastUpdatedDate:world.date});world.events.unshift({id:`evt-estate-plan-${world.date}`,date:world.date,title:'Estate plan updated',body:'You documented how you want your estate distributed. Laws and circumstances can still affect the eventual outcome.',type:'legal',priority:'low'});return world;}
export function eligibleDescendants(world:WorldState,decedentId=world.deathRecords.find(d=>d.personId===world.character.id)?.personId??world.deathRecords.at(-1)?.personId??world.character.id){const childIds=world.familyLinks.filter(f=>f.fromId===decedentId&&!f.endedDate&&['biological_parent','adoptive_parent'].includes(f.relation)).map(f=>f.toId);return childIds.map(id=>world.npcs.find(n=>n.id===id)).filter((n):n is Npc=>Boolean(n&&n.human&&!isDeceased(world,n.id))).sort((a,b)=>b.age-a.age);}
function athleticismFor(npc:Npc):AthleticSet{const base=npc.human?.health.fitness??50,t=npc.traits;return{speed:clamp(base+(t.riskTolerance-50)*.08),strength:clamp(base+(t.discipline-50)*.1),endurance:clamp(base+(t.discipline-50)*.14),agility:clamp(base+(t.confidence-50)*.08),coordination:clamp(base+(t.analytical-50)*.08),reaction:clamp(base+(t.emotional-50)*.05)};}
function socioFromInheritance(amount:number):Character['socioeconomicBackground']{return amount>=250000?'wealthy':amount>=75000?'affluent':amount>=10000?'stable':amount>=1000?'working':'struggling';}
export function continueAsDescendant(input:WorldState,descendantId:string):WorldState{const world=structuredClone(input);initializeLegacyLegal(world);const death=world.deathRecords.find(d=>d.personId===world.character.id);if(!death)return world;const candidate=eligibleDescendants(world,death.personId).find(n=>n.id===descendantId);if(!candidate||!candidate.human)return world;const decedent=structuredClone(world.character),estate=world.estateCases.find(e=>e.decedentId===decedent.id),cashInheritance=estate?.distributions.find(d=>d.personId===candidate.id)?.amount??0,parts=candidate.name.trim().split(/\s+/),firstName=parts.shift()??candidate.name,lastName=parts.join(' ')||decedent.lastName;world.npcs=world.npcs.filter(n=>n.id!==candidate.id);world.character={id:candidate.id,firstName,lastName,birthDate:candidate.birthDate,sex:candidate.sex,hometown:candidate.location,socioeconomicBackground:socioFromInheritance(cashInheritance),traits:candidate.traits,athleticism:athleticismFor(candidate),human:candidate.human,romantic:candidate.romantic,cash:cashInheritance,career:candidate.role==='Child'?(candidate.age<18?'Student':'Young adult'):candidate.role,location:candidate.location,stress:candidate.human.health.mentalLoad,energy:candidate.human.needs.physicalEnergy};for(const a of world.financialAccounts){if(a.id==='account-checking-player'){a.ownerIds=[candidate.id];a.balance=money(cashInheritance);}else if(['account-savings-player','account-investment-player','account-retirement-player'].includes(a.id)){a.ownerIds=[candidate.id];a.balance=0;}}world.investmentPositions=world.investmentPositions.filter(p=>!['account-investment-player','account-retirement-player'].includes(p.accountId));for(const o of world.recurringObligations.filter(o=>o.ownerId===decedent.id))o.active=false;for(const p of world.insurancePolicies.filter(p=>p.ownerIds.includes(decedent.id)))p.active=false;world.creditProfiles=world.creditProfiles.filter(c=>c.personId!==decedent.id);world.character.cash=world.financialAccounts.find(a=>a.id==='account-checking-player')?.balance??cashInheritance;world.controlTransitions.push({id:`control-${decedent.id}-${candidate.id}-${world.date}`,fromPersonId:decedent.id,toPersonId:candidate.id,date:world.date,reason:'death_continuation',inheritedAmount:cashInheritance});initializeFinance(world);refreshHouseholdFinance(world);initializeHealth(world);world.events.unshift({id:`evt-generation-${candidate.id}-${world.date}`,date:world.date,title:`Continue as ${firstName}`,body:`The family story continues through ${firstName}. Their history, relationships and circumstances already existed before you took control.`,type:'world',priority:'major'});return world;}
