import type { CredentialLevel, EducationEnrollment, EducationInstitution, Employer, Employment, JobOpening, SkillRecord, WorldState } from '../types/game';
import { ageAt } from './familyEngine';

const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v)));
export const credentialRank:Record<CredentialLevel,number>={none:0,high_school:1,certificate:2,associate:3,bachelor:4,graduate:5};

export function skillLevel(world:WorldState,personId:string,name:string){return world.skills.find(s=>s.personId===personId&&s.name===name)?.level??0;}
export function highestCredential(world:WorldState,personId:string):CredentialLevel{let best:CredentialLevel='none';for(const c of world.credentials.filter(c=>c.personId===personId))if(credentialRank[c.level]>credentialRank[best])best=c.level;return best;}
function addSkill(world:WorldState,personId:string,name:string,level:number){if(world.skills.some(s=>s.personId===personId&&s.name===name))return;const skill:SkillRecord={id:`skill-${personId}-${name.toLowerCase().replace(/\s+/g,'-')}`,personId,name,level:clamp(level),experience:0};world.skills.push(skill);}
function seedSkills(world:WorldState,personId:string){const p=personId===world.character.id?world.character:world.npcs.find(n=>n.id===personId);if(!p)return;addSkill(world,personId,'Communication',(p.traits.empathy+p.traits.confidence)/2);addSkill(world,personId,'Analysis',(p.traits.analytical+p.traits.discipline)/2);addSkill(world,personId,'Operations',(p.traits.discipline+p.traits.analytical+p.traits.patience)/3);addSkill(world,personId,'Leadership',(p.traits.ambition+p.traits.confidence+p.traits.empathy)/3);addSkill(world,personId,'Technology',(p.traits.analytical+p.traits.creativity)/2);}
function institutions(location:string):EducationInstitution[]{return[
  {id:'edu-public',name:'Central Community Schools',kind:'public_school',location,quality:67,tuitionAnnual:0,selectivity:0,programs:['General Studies']},
  {id:'edu-charter',name:'Summit Preparatory Academy',kind:'charter_school',location,quality:76,tuitionAnnual:0,selectivity:42,programs:['College Preparatory']},
  {id:'edu-university',name:'Sonoran State University',kind:'university',location,quality:78,tuitionAnnual:11800,selectivity:61,programs:['Business','Operations & Supply Chain','Computer Science','Nursing']},
  {id:'edu-trade',name:'West Valley Trade Institute',kind:'trade_school',location,quality:73,tuitionAnnual:6800,selectivity:28,programs:['Electrical Technology','HVAC','Industrial Maintenance','Logistics']}
];}
function employers(location:string):Employer[]{return[
  {id:'employer-desert-distribution',name:'Desert Distribution Group',industry:'Logistics & Distribution',location,size:'large',reputation:70,wageIndex:1.02,stability:76},
  {id:'employer-horizon-retail',name:'Horizon Retail Operations',industry:'Retail Operations',location,size:'large',reputation:65,wageIndex:.98,stability:72},
  {id:'employer-copperline-health',name:'Copperline Health Network',industry:'Healthcare',location,size:'large',reputation:80,wageIndex:1.08,stability:84},
  {id:'employer-sunridge-tech',name:'Sunridge Systems',industry:'Technology',location,size:'mid',reputation:74,wageIndex:1.15,stability:66}
];}
function openings(date:string):JobOpening[]{return[
  {id:'job-operations-coordinator',employerId:'employer-desert-distribution',title:'Operations Coordinator',level:'entry',salaryAnnual:52000,hoursPerWeek:40,schedule:{days:[1,2,3,4,5],startHour:8,endHour:16},remote:'onsite',requiredCredential:'high_school',requiredSkills:['Operations','Communication'],minSkill:45,status:'open',createdDate:date},
  {id:'job-operations-supervisor',employerId:'employer-horizon-retail',title:'Operations Supervisor',level:'manager',salaryAnnual:64000,hoursPerWeek:45,schedule:{days:[1,2,3,4,5],startHour:7,endHour:16},remote:'onsite',requiredCredential:'high_school',requiredSkills:['Leadership','Operations'],minSkill:58,status:'open',createdDate:date},
  {id:'job-business-analyst',employerId:'employer-sunridge-tech',title:'Business Analyst',level:'mid',salaryAnnual:72000,hoursPerWeek:40,schedule:{days:[1,2,3,4,5],startHour:9,endHour:17},remote:'hybrid',requiredCredential:'bachelor',requiredSkills:['Analysis','Technology'],minSkill:60,status:'open',createdDate:date},
  {id:'job-logistics-apprentice',employerId:'employer-desert-distribution',title:'Logistics Systems Apprentice',level:'entry',salaryAnnual:46000,hoursPerWeek:40,schedule:{days:[1,2,3,4,5],startHour:6,endHour:14},remote:'onsite',requiredCredential:'none',requiredSkills:['Operations'],minSkill:35,status:'open',createdDate:date}
];}
function schoolEnrollment(world:WorldState,personId:string):EducationEnrollment{const age=personId===world.character.id?ageAt(world.character.birthDate,world.date):(world.npcs.find(n=>n.id===personId)?.age??10);return{id:`enrollment-${personId}-school`,personId,institutionId:'edu-public',program:'General Studies',level:age<14?'primary':'secondary',status:'active',startDate:world.date,expectedEndDate:`${Number(world.date.slice(0,4))+(18-age)}-${world.date.slice(5)}`,gpa:3,attendance:94,creditsEarned:Math.max(0,(age-14)*30),creditsRequired:120,scholarshipAnnual:0,studentDebt:0};}
function startingEmployment(world:WorldState,personId:string,title:string,salary:number,employerId='employer-desert-distribution'):Employment{return{id:`employment-${personId}-${world.date}`,personId,employerId,title,level:title.toLowerCase().includes('manager')?'manager':'entry',startDate:world.date,endDate:null,status:'active',salaryAnnual:salary,payFrequency:'biweekly',hoursPerWeek:40,schedule:{days:[1,2,3,4,5],startHour:8,endHour:16},remote:'onsite',benefits:{healthInsurance:true,retirementMatch:4,ptoDays:15},performance:58,satisfaction:60,managerId:null};}
export function syncPrimarySchedule(world:WorldState,personId:string,label:string,days:number[],startHour:number,endHour:number){for(const home of world.households.filter(h=>!h.endedDate&&h.memberIds.includes(personId))){home.schedule=home.schedule.filter(s=>!(s.personId===personId&&s.id.includes('primary')));for(const day of days)home.schedule.push({id:`schedule-${personId}-primary-${day}`,personId,label,dayOfWeek:day,startHour,endHour});}}
export function initializeProgression(world:WorldState){world.educationInstitutions??=[];world.educationEnrollments??=[];world.credentials??=[];world.skills??=[];world.employers??=[];world.employments??=[];world.jobOpenings??=[];world.jobApplications??=[];world.laborMarket??={wageIndex:1,demandIndex:64,remoteShare:28};if(world.educationInstitutions.length===0)world.educationInstitutions.push(...institutions(world.character.location));if(world.employers.length===0)world.employers.push(...employers(world.character.location));if(world.jobOpenings.length===0)world.jobOpenings.push(...openings(world.date));seedSkills(world,world.character.id);for(const npc of world.npcs.filter(n=>n.tier===1))seedSkills(world,npc.id);const playerAge=ageAt(world.character.birthDate,world.date),hasPlayerEmploymentHistory=world.employments.some(e=>e.personId===world.character.id);if(playerAge<18&&!world.educationEnrollments.some(e=>e.personId===world.character.id&&e.status==='active')){world.educationEnrollments.push(schoolEnrollment(world,world.character.id));world.character.career='Student';syncPrimarySchedule(world,world.character.id,'School',[1,2,3,4,5],8,15);}else if(playerAge>=18&&!hasPlayerEmploymentHistory){const title=world.character.career==='Student'?'Operations Associate':world.character.career==='Entry-level worker'?'Operations Associate':world.character.career;world.employments.push(startingEmployment(world,world.character.id,title,42000));world.character.career=title;syncPrimarySchedule(world,world.character.id,title,[1,2,3,4,5],8,16);}const parent=world.npcs.find(n=>n.role==='Parent');if(parent&&!world.employments.some(e=>e.personId===parent.id))world.employments.push(startingEmployment(world,parent.id,'Operations Manager',76000));const friend=world.npcs.find(n=>n.role==='Friend');if(friend&&!world.employments.some(e=>e.personId===friend.id))world.employments.push(startingEmployment(world,friend.id,'Business Coordinator',54000,'employer-horizon-retail'));return world;}
