import type { WorldState } from '../types/game';
import type { SportKind, SportsFixture, SportsLeague, SportsParticipant, SportsTeam } from '../types/sports';
import { SeededRng } from './rng';
import { deriveSeed } from './humanEngine';

const firstNames=['Alex','Andre','Cameron','Darius','Eli','Emilio','Isaiah','Jalen','Jonah','Kai','Leo','Malik','Mateo','Miles','Noah','Owen','Rafael','Theo'];
const lastNames=['Bennett','Brooks','Coleman','Diaz','Flores','Foster','Hayes','Jackson','Kim','Miller','Nguyen','Patel','Price','Reed','Torres','Wright'];
const soccerPositions=['GK','RB','CB','CB','LB','DM','CM','AM','RW','LW','ST'];
const footballPositions=['QB','RB','WR','WR','TE','LT','LG','C','RG','RT','EDGE','DT','DT','EDGE','LB','LB','CB','CB','S','S','K','P'];
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function playerName(rng:SeededRng){return`${rng.pick(firstNames)} ${rng.pick(lastNames)}`;}
function teamDefs(sport:SportKind){return sport==='soccer'?[['phoenix-fc','Phoenix Sol FC'],['mesa-united','Mesa United'],['avondale-city','Avondale City'],['tempe-athletic','Tempe Athletic']]:[['phoenix-firebirds','Phoenix Firebirds'],['mesa-scorpions','Mesa Scorpions'],['avondale-outlaws','Avondale Outlaws'],['tempe-thunder','Tempe Thunder']];}
function createLeague(world:WorldState,sport:SportKind,rng:SeededRng){const year=Number(world.date.slice(0,4)),leagueId=sport==='soccer'?'league-sonoran-premier':'league-desert-gridiron',league:SportsLeague={id:leagueId,sport,name:sport==='soccer'?'Sonoran Premier League':'Desert Gridiron League',tier:'professional',seasonYear:year,teamIds:[]};const teams:SportsTeam[]=teamDefs(sport).map(([slug,name],i)=>({id:`team-${slug}`,sport,leagueId,name,location:`${name.split(' ')[0]}, Arizona`,reputation:62+i*4,budget:sport==='soccer'?4_500_000+i*500_000:18_000_000+i*1_200_000,rosterIds:[],coachProfileId:null,wins:0,losses:0,draws:0,pointsFor:0,pointsAgainst:0}));const positions=sport==='soccer'?soccerPositions:footballPositions;for(const team of teams){for(let i=0;i<positions.length;i++){const id=`participant-${team.id}-${i+1}`,rating=Math.round(54+rng.next()*28),participant:SportsParticipant={id,name:playerName(rng),sport,age:19+Math.floor(rng.next()*14),position:positions[i]!,rating,potential:Math.min(95,rating+Math.round(rng.next()*18)),fitness:78+Math.round(rng.next()*20),fatigue:Math.round(rng.next()*8),morale:58+Math.round(rng.next()*30),teamId:team.id,npcId:null};world.sportsParticipants.push(participant);team.rosterIds.push(id);}league.teamIds.push(team.id);}world.sportsLeagues.push(league);world.sportsTeams.push(...teams);seedFixtures(world,league,teams);}
function seedFixtures(world:WorldState,league:SportsLeague,teams:SportsTeam[]){const pairs:[[number,number],[number,number]][]=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]],[[1,0],[3,2]],[[2,0],[3,1]],[[3,0],[2,1]]];let fixtureNo=0;for(let week=0;week<pairs.length;week++){for(const[a,b]of pairs[week]!){const home=teams[a]!,away=teams[b]!,fixture:SportsFixture={id:`fixture-${league.id}-${++fixtureNo}`,sport:league.sport,leagueId:league.id,seasonYear:league.seasonYear,homeTeamId:home.id,awayTeamId:away.id,date:addDays(world.date,7+week*7),status:'scheduled',homeScore:0,awayScore:0,moments:[]};world.sportsFixtures.push(fixture);}}}
export function initializeSports(world:WorldState){world.sportsLeagues??=[];world.sportsTeams??=[];world.sportsParticipants??=[];world.athleteProfiles??=[];world.coachProfiles??=[];world.sportsContracts??=[];world.sportsFixtures??=[];world.sportsSeasonStats??=[];if(world.sportsLeagues.length===0){const rng=new SeededRng(deriveSeed(world.seed,'sports-world'));createLeague(world,'soccer',rng);createLeague(world,'american_football',rng);}return world;}
