import type { WorldState } from '../types/game';
import type { SportKind, SportsFixture, SportsLeague, SportsParticipant, SportsTeam } from '../types/sports';
import { SeededRng } from './rng';
import { deriveSeed } from './humanEngine';

const firstNames=['Alex','Andre','Cameron','Darius','Eli','Emilio','Isaiah','Jalen','Jonah','Kai','Leo','Malik','Mateo','Miles','Noah','Owen','Rafael','Theo'];
const lastNames=['Bennett','Brooks','Coleman','Diaz','Flores','Foster','Hayes','Jackson','Kim','Miller','Nguyen','Patel','Price','Reed','Torres','Wright'];
const soccerPositions=['GK','RB','CB','CB','LB','DM','CM','AM','RW','LW','ST'];
const footballPositions=['QB','RB','WR','WR','TE','LT','LG','C','RG','RT','EDGE','DT','DT','EDGE','LB','LB','CB','CB','S','S','K','P'];
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function playerName(rng:SeededRng){return`${rng.pick(firstNames)} ${rng.pick(lastNames)}`;}
function baseTeams(sport:SportKind){return sport==='soccer'?[['phoenix','Phoenix Sol'],['mesa','Mesa United'],['avondale','Avondale City'],['tempe','Tempe Athletic']]:[['phoenix','Phoenix Firebirds'],['mesa','Mesa Scorpions'],['avondale','Avondale Outlaws'],['tempe','Tempe Thunder']];}
function leagueConfig(sport:SportKind,tier:SportsLeague['tier']){if(sport==='soccer'&&tier==='youth')return{id:'league-sonoran-academy',name:'Sonoran Academy League',suffix:'Academy',rating:[38,67] as const,age:[14,18] as const,budget:550000};if(sport==='soccer')return{id:'league-sonoran-premier',name:'Sonoran Premier League',suffix:'FC',rating:[55,83] as const,age:[19,34] as const,budget:4_500_000};if(tier==='youth')return{id:'league-desert-prep',name:'Desert Prep Football',suffix:'Prep',rating:[38,66] as const,age:[15,18] as const,budget:450000};if(tier==='college')return{id:'league-arizona-collegiate',name:'Arizona Collegiate Football',suffix:'University',rating:[52,78] as const,age:[18,23] as const,budget:7_500_000};return{id:'league-desert-gridiron',name:'Desert Gridiron League',suffix:'Pro',rating:[62,89] as const,age:[21,35] as const,budget:18_000_000};}
function createLeague(world:WorldState,sport:SportKind,tier:SportsLeague['tier'],rng:SeededRng){const cfg=leagueConfig(sport,tier),year=Number(world.date.slice(0,4)),league:SportsLeague={id:cfg.id,sport,name:cfg.name,tier,seasonYear:year,teamIds:[]};const teams:SportsTeam[]=baseTeams(sport).map(([slug,base],i)=>({id:`team-${slug}-${sport}-${tier}`,sport,leagueId:cfg.id,name:`${base} ${cfg.suffix}`,location:`${base.split(' ')[0]}, Arizona`,reputation:52+i*5+(tier==='professional'?12:tier==='college'?6:0),budget:cfg.budget+i*cfg.budget*.08,rosterIds:[],coachProfileId:null,wins:0,losses:0,draws:0,pointsFor:0,pointsAgainst:0}));const positions=sport==='soccer'?soccerPositions:footballPositions;for(const team of teams){for(let i=0;i<positions.length;i++){const id=`participant-${team.id}-${i+1}`,rating=Math.round(cfg.rating[0]+rng.next()*(cfg.rating[1]-cfg.rating[0])),participant:SportsParticipant={id,name:playerName(rng),sport,age:cfg.age[0]+Math.floor(rng.next()*(cfg.age[1]-cfg.age[0]+1)),position:positions[i]!,rating,potential:Math.min(96,rating+Math.round(rng.next()*20)),fitness:76+Math.round(rng.next()*22),fatigue:Math.round(rng.next()*8),morale:56+Math.round(rng.next()*32),teamId:team.id,npcId:null};world.sportsParticipants.push(participant);team.rosterIds.push(id);}league.teamIds.push(team.id);}world.sportsLeagues.push(league);world.sportsTeams.push(...teams);seedFixtures(world,league,teams);}
function seedFixtures(world:WorldState,league:SportsLeague,teams:SportsTeam[]){const pairs:[[number,number],[number,number]][]=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]],[[1,0],[3,2]],[[2,0],[3,1]],[[3,0],[2,1]]];let fixtureNo=0;for(let week=0;week<pairs.length;week++)for(const[a,b]of pairs[week]!){const fixture:SportsFixture={id:`fixture-${league.id}-${++fixtureNo}`,sport:league.sport,leagueId:league.id,seasonYear:league.seasonYear,homeTeamId:teams[a]!.id,awayTeamId:teams[b]!.id,date:addDays(world.date,7+week*7),status:'scheduled',homeScore:0,awayScore:0,moments:[]};world.sportsFixtures.push(fixture);}}
export function initializeSports(world:WorldState){world.sportsLeagues??=[];world.sportsTeams??=[];world.sportsParticipants??=[];world.athleteProfiles??=[];world.coachProfiles??=[];world.sportsContracts??=[];world.sportsFixtures??=[];world.sportsSeasonStats??=[];if(world.sportsLeagues.length===0){const rng=new SeededRng(deriveSeed(world.seed,'sports-world'));createLeague(world,'soccer','youth',rng);createLeague(world,'soccer','professional',rng);createLeague(world,'american_football','youth',rng);createLeague(world,'american_football','college',rng);createLeague(world,'american_football','professional',rng);}return world;}
