export type SportKind='soccer'|'american_football';
export type SportsCareerRole='athlete'|'coach';
export interface SportsLeague{ id:string; sport:SportKind; name:string; tier:'youth'|'amateur'|'college'|'professional'; seasonYear:number; teamIds:string[]; }
export interface SportsTeam{ id:string; sport:SportKind; leagueId:string; name:string; location:string; reputation:number; budget:number; rosterIds:string[]; coachProfileId:string|null; wins:number; losses:number; draws:number; pointsFor:number; pointsAgainst:number; }
export interface SportsParticipant{ id:string; name:string; sport:SportKind; age:number; position:string; rating:number; potential:number; fitness:number; fatigue:number; morale:number; teamId:string|null; npcId:string|null; }
export interface AthleteProfile{ id:string; personId:string; sport:SportKind; position:string; teamId:string|null; rating:number; potential:number; fitness:number; fatigue:number; morale:number; injuryStatus:'healthy'|'minor'|'moderate'|'major'; injuryDaysRemaining:number; careerStatus:'amateur'|'college'|'professional'|'retired'; contractId:string|null; }
export interface CoachProfile{ id:string; personId:string; sport:SportKind; teamId:string|null; tactical:number; development:number; leadership:number; reputation:number; style:'balanced'|'aggressive'|'conservative'; contractId:string|null; }
export interface SportsContract{ id:string; personId:string; teamId:string; role:SportsCareerRole; salaryAnnual:number; startDate:string; endDate:string; status:'active'|'ended'; }
export interface MatchMoment{ id:string; clock:number; period:number; teamId:string; actorId:string|null; type:'score'|'chance'|'turnover'|'save'|'penalty'|'injury'|'substitution'|'big_play'; description:string; importance:number; }
export interface SportsFixture{ id:string; sport:SportKind; leagueId:string; seasonYear:number; homeTeamId:string; awayTeamId:string; date:string; status:'scheduled'|'complete'; homeScore:number; awayScore:number; moments:MatchMoment[]; }
export interface SportsSeasonStat{ id:string; personId:string; sport:SportKind; seasonYear:number; games:number; starts:number; minutes:number; goals:number; assists:number; saves:number; passingYards:number; rushingYards:number; receivingYards:number; touchdowns:number; tackles:number; interceptions:number; wins:number; losses:number; }
export interface SportsWorldState{ sportsLeagues:SportsLeague[]; sportsTeams:SportsTeam[]; sportsParticipants:SportsParticipant[]; athleteProfiles:AthleteProfile[]; coachProfiles:CoachProfile[]; sportsContracts:SportsContract[]; sportsFixtures:SportsFixture[]; sportsSeasonStats:SportsSeasonStat[]; }
