import type { AthleticSet, Character, Household, Npc, Orientation, RelationshipState, RomanticProfile, Sex, TraitSet, WorldState } from '../types/game';
import type { FinanceWorldState } from '../types/finance';
import type { SportsWorldState } from '../types/sports';
import type { BusinessWorldState } from '../types/business';
import type { NarrationWorldState } from '../types/narration';
import type { HealthWorldState } from '../types/health';
import type { LegacyLegalWorldState } from '../types/legacyLegal';
import type { LifestyleWorldState } from '../types/lifestyle';
import type { LivingWorldState } from '../types/livingWorld';
import { SeededRng } from '../simulation/rng';
import { createHumanState, createNpcTraits } from '../simulation/humanFactory';
import { initializeProgression } from '../simulation/progressionSeed';
import { initializeFinance } from '../simulation/financeSeed';
import { initializeSports } from '../simulation/sportsSeed';
import { initializeBusinessWorld } from '../simulation/businessEngine';
import { initializeHealth } from '../simulation/healthSeed';
import { initializeLegacyLegal } from '../simulation/legacyLegalSeed';
import { emptyLifestyleState, initializeLifestyle } from '../simulation/lifestyleSeed';
import { emptyLivingWorldState, initializeLivingWorld } from '../simulation/livingWorldSeed';
import { initializeNarration } from '../narration/narrationEngine';

type Phase4Keys='educationInstitutions'|'educationEnrollments'|'credentials'|'skills'|'employers'|'employments'|'jobOpenings'|'jobApplications'|'laborMarket';
type Phase6Keys=keyof SportsWorldState|keyof BusinessWorldState;
type LegacyWorldV10=Omit<WorldState,'version'|keyof LivingWorldState>&{version:10};
type LegacyWorldV9=Omit<LegacyWorldV10,'version'|keyof LifestyleWorldState>&{version:9};
type LegacyWorldV8=Omit<LegacyWorldV9,'version'|keyof LegacyLegalWorldState>&{version:8};
type LegacyWorldV7=Omit<LegacyWorldV8,'version'|keyof HealthWorldState>&{version:7};
type LegacyWorldV6=Omit<LegacyWorldV7,'version'|keyof NarrationWorldState>&{version:6};
type LegacyWorldV5=Omit<LegacyWorldV6,'version'|Phase6Keys>&{version:5};
type LegacyWorldV4=Omit<LegacyWorldV5,'version'|keyof FinanceWorldState>&{version:4};
type LegacyWorldV3=Omit<LegacyWorldV4,'version'|Phase4Keys>&{version:3};
type LegacyCharacterV2=Omit<Character,'romantic'>;
type LegacyNpcV2=Omit<Npc,'birthDate'|'sex'|'romantic'|'childDevelopment'>;
interface LegacyWorldV2{version:2;seed:number;date:string;character:LegacyCharacterV2;npcs:LegacyNpcV2[];relationships:RelationshipState[];knowledge:WorldState['knowledge'];secrets:WorldState['secrets'];npcActivity:WorldState['npcActivity'];ledger:WorldState['ledger'];events:WorldState['events'];memories:WorldState['memories'];economy:WorldState['economy'];}
interface LegacyNpcV1{id:string;name:string;role:string;age:number;location:string;affection:number;trust:number;respect:number;resentment:number;mood:string;activeGoal:string;}
interface LegacyWorldV1{version:1;seed:number;date:string;character:Omit<LegacyCharacterV2,'human'>;npcs:LegacyNpcV1[];ledger:WorldState['ledger'];events:WorldState['events'];memories:WorldState['memories'];economy:WorldState['economy'];}
const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v)));
function isVersion(value:unknown,version:number){return typeof value==='object'&&value!==null&&(value as{version?:unknown}).version===version;}
function birthDateForAge(date:string,age:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()-age);return d.toISOString().slice(0,10);}
function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function sexFor(id:string):Sex{return(hash(id)&1)===0?'female':'male';}
function romanticFor(traits:TraitSet,orientation:Orientation='straight'):RomanticProfile{return{orientation,relationshipStyle:'monogamous',wantsChildren:traits.familyOrientation>=72?'yes':traits.familyOrientation>=48?'maybe':'not_now'};}
function ageAt(birthDate:string,date:string){const b=new Date(`${birthDate}T12:00:00Z`),d=new Date(`${date}T12:00:00Z`);let age=d.getUTCFullYear()-b.getUTCFullYear();const md=d.getUTCMonth()-b.getUTCMonth();if(md<0||(md===0&&d.getUTCDate()<b.getUTCDate()))age--;return age;}
function averageAthleticism(a:AthleticSet){return(a.speed+a.strength+a.endurance+a.agility+a.coordination+a.reaction)/6;}
function startingHousehold(character:Character,date:string,economy:WorldState['economy']):Household{return{id:`household-${character.id}-${date}`,name:`${character.lastName} household`,memberIds:[character.id],location:character.location,homeType:'apartment',monthlyHousingCost:Math.round(1450*economy.housingIndex),responsibleAdultIds:[character.id],financeStyle:'separate',laborAssignments:[{id:`labor-meals-${character.id}`,task:'Meals',ownerId:character.id,cadence:'daily',burden:18},{id:`labor-cleaning-${character.id}`,task:'Cleaning',ownerId:character.id,cadence:'weekly',burden:16},{id:`labor-admin-${character.id}`,task:'Household admin',ownerId:character.id,cadence:'weekly',burden:14}],schedule:[{id:`schedule-${character.id}-weekday`,personId:character.id,label:character.career==='Student'?'School / study':'Work / primary responsibilities',dayOfWeek:1,startHour:9,endHour:17}],createdDate:date,endedDate:null};}
function v1ToV2(legacy:LegacyWorldV1):LegacyWorldV2{const rng=new SeededRng(legacy.seed^0x45564552),characterHuman=createHumanState(legacy.character.id,legacy.character.traits as TraitSet,legacy.date,rng,{fitness:averageAthleticism(legacy.character.athleticism as AthleticSet),stress:legacy.character.stress,energy:legacy.character.energy}),character:LegacyCharacterV2={...legacy.character,human:characterHuman};const npcs:LegacyNpcV2[]=legacy.npcs.map((old,index)=>{const traits=createNpcTraits(rng,old.role==='Parent'?{familyOrientation:84,empathy:74}:undefined),human=createHumanState(old.id,traits,legacy.date,rng,{npc:true,stress:old.mood==='strained'?68:28});if(human.goals[0])human.goals[0].title=old.activeGoal||human.goals[0].title;return{id:old.id,name:old.name,role:old.role,age:old.age,location:old.location,tier:index<2?1:2,traits,human,currentFocus:old.activeGoal||'current priorities',lastSimulatedDate:legacy.date};});const relationships:RelationshipState[]=legacy.npcs.flatMap(old=>{const shared={attraction:0,familiarity:clamp((old.affection+old.trust)/2),dependency:clamp(old.affection*.25),lastMeaningfulContactDate:legacy.date};return[{id:`rel-${old.id}-${character.id}`,fromId:old.id,toId:character.id,affection:old.affection,respect:old.respect,resentment:old.resentment,trust:{emotional:old.trust,financial:old.trust,professional:old.respect,romantic:0},...shared},{id:`rel-${character.id}-${old.id}`,fromId:character.id,toId:old.id,affection:old.affection,respect:old.respect,resentment:old.resentment,trust:{emotional:old.trust,financial:old.trust,professional:old.respect,romantic:0},...shared}];});return{version:2,seed:legacy.seed,date:legacy.date,character,npcs,relationships,knowledge:[],secrets:[],npcActivity:[],ledger:legacy.ledger,events:legacy.events,memories:legacy.memories,economy:legacy.economy};}
function v2ToV3(legacy:LegacyWorldV2):LegacyWorldV3{const character:Character={...legacy.character,romantic:romanticFor(legacy.character.traits)},npcs:Npc[]=legacy.npcs.map(n=>({...n,birthDate:birthDateForAge(legacy.date,n.age),sex:sexFor(n.id),romantic:romanticFor(n.traits),childDevelopment:null}));const world:LegacyWorldV3={version:3,seed:legacy.seed,date:legacy.date,character,npcs,relationships:legacy.relationships,partnerships:[],households:[],pregnancies:[],familyLinks:[],custodyPlans:[],conversations:[],knowledge:legacy.knowledge??[],secrets:legacy.secrets??[],npcActivity:legacy.npcActivity??[],ledger:legacy.ledger??[],events:legacy.events??[],memories:legacy.memories??[],economy:legacy.economy};world.households.push(startingHousehold(character,legacy.date,legacy.economy));const parent=npcs.find(n=>n.role==='Parent');if(parent&&ageAt(character.birthDate,legacy.date)<18){const home=world.households[0]!;home.memberIds=[character.id,parent.id];home.responsibleAdultIds=[parent.id];for(const task of home.laborAssignments)task.ownerId=parent.id;}if(parent)world.familyLinks.push({id:`family-${parent.id}-${character.id}-parent`,fromId:parent.id,toId:character.id,relation:'biological_parent',establishedDate:legacy.date,endedDate:null},{id:`family-${character.id}-${parent.id}-child`,fromId:character.id,toId:parent.id,relation:'biological_child',establishedDate:legacy.date,endedDate:null});if(world.secrets.length===0){const friend=npcs.find(n=>n.role==='Friend'&&n.tier===1);if(friend)world.secrets.push({id:`secret-${friend.id}-career-move`,subjectId:friend.id,category:'career',summary:`${friend.name} has quietly been considering an opportunity that could eventually take them to another city.`,sensitivity:44,createdDate:legacy.date,knownBy:[{personId:friend.id,since:legacy.date,sourceId:friend.id}],status:'active'});}return world;}
function normalizeV3(value:unknown):LegacyWorldV3|null{if(!isVersion(value,3))return null;const world=structuredClone(value) as LegacyWorldV3;world.partnerships??=[];world.households??=[];world.pregnancies??=[];world.familyLinks??=[];world.custodyPlans??=[];world.conversations??=[];world.character.romantic??=romanticFor(world.character.traits);for(const n of world.npcs){n.birthDate??=birthDateForAge(world.date,n.age);n.sex??=sexFor(n.id);n.romantic??=romanticFor(n.traits);n.childDevelopment??=null;}for(const h of world.households)h.responsibleAdultIds??=h.memberIds.filter(id=>id===world.character.id?ageAt(world.character.birthDate,world.date)>=18:(world.npcs.find(n=>n.id===id)?.age??18)>=18);if(!world.households.some(h=>!h.endedDate&&h.memberIds.includes(world.character.id)))world.households.push(startingHousehold(world.character,world.date,world.economy));return world;}
function phase5Finance(date:string):FinanceWorldState{return{financialAccounts:[],recurringObligations:[],budgetRules:[],householdFinancePlans:[],creditProfiles:[],liabilities:[],insurancePolicies:[],properties:[],vehicles:[],investmentPositions:[],bankruptcyRecords:[],market:{usEquityIndex:100,internationalEquityIndex:100,bondIndex:100,volatility:18,regime:'neutral',lastUpdatedDate:date}};}
function hydrateV5(world:LegacyWorldV5):LegacyWorldV5{initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);return world;}
function v3ToV5(legacy:LegacyWorldV3):LegacyWorldV5{const world={...structuredClone(legacy),version:5,educationInstitutions:[],educationEnrollments:[],credentials:[],skills:[],employers:[],employments:[],jobOpenings:[],jobApplications:[],laborMarket:{wageIndex:1,demandIndex:64,remoteShare:28},...phase5Finance(legacy.date)} as LegacyWorldV5;return hydrateV5(world);}
function v4ToV5(legacy:LegacyWorldV4):LegacyWorldV5{const world={...structuredClone(legacy),version:5,...phase5Finance(legacy.date)} as LegacyWorldV5;return hydrateV5(world);}
function phase6State():SportsWorldState&BusinessWorldState{return{sportsLeagues:[],sportsTeams:[],sportsParticipants:[],athleteProfiles:[],coachProfiles:[],sportsContracts:[],sportsFixtures:[],sportsSeasonStats:[],businesses:[],warehouseFacilities:[],businessEmployees:[],logisticsContracts:[],logisticsKpis:[],businessOpportunities:[]};}
function phase8Health():HealthWorldState{return{healthProfiles:[],medicalConditions:[],medicalEncounters:[],medicalBills:[],medications:[]};}
function phase9LegacyLegal():LegacyLegalWorldState{return{deathRecords:[],funeralRecords:[],estatePlans:[],estateCases:[],ancestorArchives:[],controlTransitions:[],crimeIncidents:[],criminalCases:[],criminalRecords:[],incarcerationRecords:[],civilCases:[]};}
function v5ToV6(legacy:LegacyWorldV5):LegacyWorldV6{const world={...structuredClone(legacy),version:6,...phase6State()} as LegacyWorldV6;initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);initializeSports(world as unknown as WorldState);initializeBusinessWorld(world as unknown as WorldState);return world;}
function normalizeV6(value:unknown):LegacyWorldV6|null{if(!isVersion(value,6))return null;const world=structuredClone(value) as LegacyWorldV6;initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);initializeSports(world as unknown as WorldState);initializeBusinessWorld(world as unknown as WorldState);return world;}
function v6ToV7(legacy:LegacyWorldV6):LegacyWorldV7{const world={...structuredClone(legacy),version:7,narrationSettings:{mode:'offline',preferredProvider:'evera-offline',allowRemoteNarration:false},annualLifeChapters:[]} as LegacyWorldV7;initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);initializeSports(world as unknown as WorldState);initializeBusinessWorld(world as unknown as WorldState);initializeNarration(world as unknown as WorldState);return world;}
function normalizeV7(value:unknown):LegacyWorldV7|null{if(!isVersion(value,7))return null;const world=structuredClone(value) as LegacyWorldV7;initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);initializeSports(world as unknown as WorldState);initializeBusinessWorld(world as unknown as WorldState);initializeNarration(world as unknown as WorldState);return world;}
function hydrateV8(world:LegacyWorldV8):LegacyWorldV8{world.healthProfiles??=[];world.medicalConditions??=[];world.medicalEncounters??=[];world.medicalBills??=[];world.medications??=[];initializeProgression(world as unknown as WorldState);initializeFinance(world as unknown as WorldState);initializeSports(world as unknown as WorldState);initializeBusinessWorld(world as unknown as WorldState);initializeNarration(world as unknown as WorldState);return world;}
function v7ToV8(legacy:LegacyWorldV7):LegacyWorldV8{return hydrateV8({...structuredClone(legacy),version:8,...phase8Health()} as LegacyWorldV8);}
function normalizeV8(value:unknown):LegacyWorldV8|null{if(!isVersion(value,8))return null;return hydrateV8(structuredClone(value) as LegacyWorldV8);}
function v8ToV9(legacy:LegacyWorldV8):LegacyWorldV9{const world={...structuredClone(legacy),version:9,...phase9LegacyLegal()} as LegacyWorldV9;const compat=world as unknown as WorldState;initializeProgression(compat);initializeFinance(compat);initializeSports(compat);initializeBusinessWorld(compat);initializeHealth(compat);initializeNarration(compat);initializeLegacyLegal(compat);return world;}
function normalizeV9(value:unknown):LegacyWorldV9|null{if(!isVersion(value,9))return null;const world=structuredClone(value) as LegacyWorldV9,compat=world as unknown as WorldState;initializeProgression(compat);initializeFinance(compat);initializeSports(compat);initializeBusinessWorld(compat);initializeHealth(compat);initializeNarration(compat);initializeLegacyLegal(compat);return world;}
function v9ToV10(legacy:LegacyWorldV9):LegacyWorldV10{const world={...structuredClone(legacy),version:10,...emptyLifestyleState()} as LegacyWorldV10,compat=world as unknown as WorldState;initializeProgression(compat);initializeFinance(compat);initializeSports(compat);initializeBusinessWorld(compat);initializeHealth(compat);initializeNarration(compat);initializeLegacyLegal(compat);initializeLifestyle(compat);return world;}
function normalizeV10(value:unknown):LegacyWorldV10|null{if(!isVersion(value,10))return null;const world=structuredClone(value) as LegacyWorldV10,compat=world as unknown as WorldState;initializeProgression(compat);initializeFinance(compat);initializeSports(compat);initializeBusinessWorld(compat);initializeHealth(compat);initializeNarration(compat);initializeLegacyLegal(compat);initializeLifestyle(compat);return world;}
function v10ToV11(legacy:LegacyWorldV10):WorldState{const world={...structuredClone(legacy),version:11,...emptyLivingWorldState()} as WorldState;initializeProgression(world);initializeFinance(world);initializeSports(world);initializeBusinessWorld(world);initializeHealth(world);initializeNarration(world);initializeLegacyLegal(world);initializeLifestyle(world);return initializeLivingWorld(world);}
function normalizeV11(value:unknown):WorldState|null{if(!isVersion(value,11))return null;const world=structuredClone(value) as WorldState;initializeProgression(world);initializeFinance(world);initializeSports(world);initializeBusinessWorld(world);initializeHealth(world);initializeNarration(world);initializeLegacyLegal(world);initializeLifestyle(world);return initializeLivingWorld(world);}
export function migrateWorld(value:unknown):WorldState|null{
  if(isVersion(value,11))return normalizeV11(value);
  if(isVersion(value,10)){const v10=normalizeV10(value);return v10?v10ToV11(v10):null;}
  if(isVersion(value,9)){const v9=normalizeV9(value);return v9?v10ToV11(v9ToV10(v9)):null;}
  if(isVersion(value,8)){const v8=normalizeV8(value);return v8?v10ToV11(v9ToV10(v8ToV9(v8))):null;}
  if(isVersion(value,7)){const v7=normalizeV7(value);return v7?v10ToV11(v9ToV10(v8ToV9(v7ToV8(v7)))):null;}
  if(isVersion(value,6)){const v6=normalizeV6(value);return v6?v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v6))))):null;}
  if(isVersion(value,5))return v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v5ToV6(value as LegacyWorldV5))))));
  if(isVersion(value,4))return v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v5ToV6(v4ToV5(value as LegacyWorldV4)))))));
  if(isVersion(value,3)){const v3=normalizeV3(value);return v3?v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v5ToV6(v3ToV5(v3))))))):null;}
  if(isVersion(value,2))return v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v5ToV6(v3ToV5(v2ToV3(value as LegacyWorldV2))))))));
  if(isVersion(value,1))return v10ToV11(v9ToV10(v8ToV9(v7ToV8(v6ToV7(v5ToV6(v3ToV5(v2ToV3(v1ToV2(value as LegacyWorldV1)))))))));
  return null;
}
