import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Baby, Brain, BriefcaseBusiness, Building2, CalendarDays, CircleDollarSign, Clock3, GraduationCap, HeartHandshake, History, Home, Landmark, MessageCircle, Pause, Play, RotateCcw, Sparkles, Target, Users, WalletCards } from 'lucide-react';
import type { NavArea, Partnership, WorldState } from '../types/game';
import { ageOn, setPlayerGoalFocus, stepWorld } from '../simulation/engine';
import { habitSignal, needSignal, relationshipSignal } from '../simulation/humanEngine';
import { attemptRelationshipStep, haveConversation, partnershipFor, partnershipLabel, relationshipPotential, romanceEligible, setFamilyPlan, type RelationshipAction } from '../simulation/relationshipEngine';
import { activeHouseholdForPerson, reassignHouseholdLabor } from '../simulation/householdEngine';
import { applyParentingAction, childrenOf, type ParentingAction } from '../simulation/familyEngine';
import { acceptJobOffer, activeEmployment, applyForJob, leaveJob } from '../simulation/careerEngine';
import { activeEnrollment, startEducation, withdrawEducation } from '../simulation/educationEngine';
import { saveWorld } from '../persistence/store';
import { FinancePanel } from './FinancePanel';
import { DeepModulesPanel } from './DeepModulesPanel';
import { Logo } from './Logo';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const fmtDate=(d:string)=>dateFmt.format(new Date(`${d}T12:00:00Z`));

export function AppShell({initial,onReset}:{initial:WorldState;onReset:()=>void}){
  const[world,setWorld]=useState(initial),[nav,setNav]=useState<NavArea>('life'),[speed,setSpeed]=useState<0|1|5|20>(0);
  const lastPausedMajorId=useRef<string|null>(null);
  useEffect(()=>{saveWorld(world).catch(console.error);},[world]);
  useEffect(()=>{if(speed===0)return;const timer=window.setInterval(()=>setWorld(w=>stepWorld(w,speed)),1100);return()=>window.clearInterval(timer);},[speed]);
  const age=ageOn(world.character.birthDate,world.date),major=world.events.find(e=>e.priority==='major'&&e.id!=='evt-start');
  useEffect(()=>{if(major&&major.id!==lastPausedMajorId.current){lastPausedMajorId.current=major.id;setSpeed(0);}},[major?.id]);
  let content:ReactNode;
  if(nav==='life')content=<Life world={world} age={age} onFocus={goalId=>setWorld(w=>setPlayerGoalFocus(w,goalId))} onChange={setWorld}/>;
  else if(nav==='people')content=<People world={world} onChange={setWorld}/>;
  else if(nav==='money')content=<FinancePanel world={world} onChange={setWorld}/>;
  else if(nav==='world')content=<><WorldView world={world}/><DeepModulesPanel world={world} onChange={setWorld}/></>;
  else content=<Timeline world={world}/>;
  return <div className="app-shell">
    <header className="topbar"><Logo/><div className="top-date"><span>{fmtDate(world.date)}</span><small>Age {age} · {world.character.location}</small></div><button className="icon-btn" onClick={()=>{setSpeed(0);onReset();}} title="Start a new world"><RotateCcw size={18}/></button></header>
    <section className="timebar"><button className={speed===0?'active':''} onClick={()=>setSpeed(0)}><Pause size={16}/>Pause</button>{([1,5,20] as const).map(s=><button key={s} className={speed===s?'active':''} onClick={()=>setSpeed(s)}><Play size={15}/>{s}×</button>)}<button onClick={()=>setWorld(w=>stepWorld(w,1))}><Clock3 size={16}/>Next day</button></section>
    <div className="main-content">{content}</div>
    <nav className="bottom-nav" aria-label="Primary"><NavButton icon={<CalendarDays/>} label="Life" active={nav==='life'} onClick={()=>setNav('life')}/><NavButton icon={<Users/>} label="People" active={nav==='people'} onClick={()=>setNav('people')}/><NavButton icon={<Landmark/>} label="World" active={nav==='world'} onClick={()=>setNav('world')}/><NavButton icon={<WalletCards/>} label="Money" active={nav==='money'} onClick={()=>setNav('money')}/><NavButton icon={<History/>} label="Timeline" active={nav==='timeline'} onClick={()=>setNav('timeline')}/></nav>
  </div>;
}
function NavButton({icon,label,active,onClick}:{icon:ReactNode;label:string;active:boolean;onClick:()=>void}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span></button>;}

function Life({world,age,onFocus,onChange}:{world:WorldState;age:number;onFocus:(goalId:string)=>void;onChange:(world:WorldState)=>void}){
  const c=world.character,signals=needSignal(c.human),habits=habitSignal(c.human),goals=c.human.goals.filter(g=>g.status==='active').sort((a,b)=>b.priority-a.priority);
  return <><section className="identity-card"><div className="avatar">{c.firstName[0]}{c.lastName[0]}</div><div><span className="eyebrow">YOUR LIFE</span><h1>{c.firstName} {c.lastName}</h1><p>{age} · {c.career}</p></div></section>
    <div className="metric-grid"><Metric label="Cash" value={money.format(c.cash)} detail="Checking balance"/><Metric label="Energy" value={energyLabel(c.energy)} detail="How you seem to be holding up"/><Metric label="Pressure" value={stressLabel(c.stress)} detail="Not a diagnosis or score"/><Metric label="Mood" value={titleCase(c.human.mood.label)} detail="Current emotional weather"/></div>
    <CareerEducation world={world} onChange={onChange}/>
    <Section title="What you are noticing" subtitle="Underlying human-state math stays hidden.">{signals.length?<div className="signal-list">{signals.map(signal=><div className="signal" key={signal}><Brain size={18}/><span>{signal}</span></div>)}</div>:<div className="signal"><Sparkles size={18}/><span>Nothing feels especially out of balance right now.</span></div>}</Section>
    <Section title="Your direction" subtitle="Priorities are not guaranteed outcomes."><div className="goal-grid">{goals.map((goal,index)=><article className={`goal-card ${index===0?'focused':''}`} key={goal.id}><div><span className="eyebrow">{goal.domain.toUpperCase()}</span><h3>{goal.title}</h3><p>{goalProgressText(goal.progress)}</p></div><button className="secondary-btn" onClick={()=>onFocus(goal.id)}>{index===0?'Current focus':'Prioritize'}</button></article>)}</div></Section>
    <Section title="Habits taking shape"><div className="habit-list">{habits.map(h=><div className="habit-row" key={h.name}><span>{h.name}</span><small>{h.signal}</small></div>)}</div></Section>
    <Section title="What needs your attention">{world.events.slice(0,5).map(e=><article className={`event ${e.priority}`} key={e.id}><span className="eyebrow">{e.type.toUpperCase()} · {fmtDate(e.date)}</span><h3>{e.title}</h3><p>{e.body}</p></article>)}</Section>
  </>;
}

function CareerEducation({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  const employment=activeEmployment(world),enrollment=activeEnrollment(world),applications=world.jobApplications.filter(a=>a.personId===world.character.id).slice(0,5),credentials=world.credentials.filter(c=>c.personId===world.character.id),employer=employment?world.employers.find(e=>e.id===employment.employerId):undefined;
  return <><Section title="Career" subtitle="Jobs are contracts with schedules, pay, benefits and performance expectations.">{employment?<article className="career-card"><div className="career-head"><BriefcaseBusiness size={22}/><div><span className="eyebrow">ACTIVE EMPLOYMENT</span><h3>{employment.title}</h3><p>{employer?.name??'Employer'} · {money.format(employment.salaryAnnual)}/yr · {employment.remote}</p></div></div><div className="career-stats"><span><b>{Math.round(employment.performance)}</b><small>Performance</small></span><span><b>{employment.hoursPerWeek}</b><small>Hours / week</small></span><span><b>{employment.benefits.retirementMatch}%</b><small>Retirement match</small></span><span><b>{employment.benefits.ptoDays}</b><small>PTO days</small></span></div><button className="secondary-btn danger-soft" onClick={()=>onChange(leaveJob(world))}>Leave job</button></article>:<Empty text="You are not currently employed. The labor market continues moving without you."/>}
    <div className="job-grid">{world.jobOpenings.filter(j=>j.status==='open').slice(0,6).map(job=>{const company=world.employers.find(e=>e.id===job.employerId),existing=world.jobApplications.find(a=>a.openingId===job.id&&a.personId===world.character.id&&!['rejected','withdrawn'].includes(a.status));return <article className="job-card" key={job.id}><span className="eyebrow">{job.remote.toUpperCase()} · {job.level.toUpperCase()}</span><h3>{job.title}</h3><p>{company?.name} · {money.format(job.salaryAnnual)}/yr</p><small>Requires {job.requiredCredential.replace('_',' ')} · {job.requiredSkills.join(' + ')}</small><button className="secondary-btn" disabled={Boolean(existing)} onClick={()=>onChange(applyForJob(world,job.id))}>{existing?`Application: ${existing.status}`:'Apply'}</button></article>;})}</div>
    {applications.length>0&&<div className="application-list">{applications.map(app=>{const job=world.jobOpenings.find(j=>j.id===app.openingId);return <div className="application-row" key={app.id}><span><b>{job?.title??'Role'}</b><small>{titleCase(app.status)}{app.offerSalary?` · ${money.format(app.offerSalary)}/yr`:''}</small></span>{app.status==='offer'&&<button className="primary mini" onClick={()=>onChange(acceptJobOffer(world,app.id))}>Accept offer</button>}</div>;})}</div>}</Section>
    <Section title="Education" subtitle="School can open paths, but it costs time and sometimes money.">{enrollment?<article className="education-card"><div className="career-head"><GraduationCap size={22}/><div><span className="eyebrow">ACTIVE ENROLLMENT</span><h3>{enrollment.program}</h3><p>{institutionName(world,enrollment.institutionId)} · {enrollment.level.replace('_',' ')}</p></div></div><div className="career-stats"><span><b>{enrollment.gpa.toFixed(2)}</b><small>GPA</small></span><span><b>{Math.round(enrollment.creditsEarned)}/{enrollment.creditsRequired}</b><small>Credits</small></span><span><b>{Math.round(enrollment.attendance)}%</b><small>Attendance</small></span><span><b>{money.format(enrollment.studentDebt)}</b><small>Student debt</small></span></div>{!['primary','secondary'].includes(enrollment.level)&&<button className="secondary-btn danger-soft" onClick={()=>onChange(withdrawEducation(world,enrollment.id))}>Leave program</button>}</article>:<div className="education-grid">{world.educationInstitutions.filter(i=>i.kind==='university'||i.kind==='trade_school').map(i=><article className="education-option" key={i.id}><Building2 size={20}/><span className="eyebrow">{i.kind.replace('_',' ').toUpperCase()}</span><h3>{i.name}</h3><p>{money.format(i.tuitionAnnual)}/yr · quality {Math.round(i.quality)}</p><div className="program-row">{i.programs.slice(0,3).map(program=><button className="secondary-btn" key={program} onClick={()=>onChange(startEducation(world,i.id,program))}>{program}</button>)}</div></article>)}</div>}
    {credentials.length>0&&<div className="credential-list">{credentials.map(c=><div className="credential" key={c.id}><GraduationCap size={17}/><span><b>{c.name}</b><small>{institutionName(world,c.institutionId)} · {fmtDate(c.dateEarned)}</small></span></div>)}</div>}</Section>
  </>;
}

function People({world,onChange}:{world:WorldState;onChange:(w:WorldState)=>void}){
  const player=world.character.id,close=world.npcs.filter(n=>n.tier===1),active=world.npcs.filter(n=>n.tier===2),household=activeHouseholdForPerson(world,player),children=childrenOf(world,player),pregnancy=world.pregnancies.find(p=>p.status==='ongoing'&&(p.pregnantPersonId===player||p.partnerId===player)),custody=world.custodyPlans.filter(c=>c.active&&c.parentIds.includes(player));
  return <><Section title="People in your orbit" subtitle="Relationships have history, uncertainty and two separate points of view.">{[...close,...active.slice(0,4)].map(n=><PersonCard key={n.id} world={world} npcId={n.id} onChange={onChange}/>)}</Section>
    {household&&<Section title="Your household" subtitle="Living together changes money, schedules and invisible work."><article className="household-card"><div><span className="eyebrow">{household.homeType.toUpperCase()}</span><h3>{household.name}</h3><p>{household.memberIds.map(id=>nameFor(world,id)).join(' · ')}</p></div><div><Home size={22}/><strong>{household.monthlyHousingCost>0?`${money.format(household.monthlyHousingCost)}/mo`:'Owned home'}</strong></div></article><div className="labor-list">{household.laborAssignments.map(task=><div className="labor-row" key={task.id}><span><b>{task.task}</b><small>{task.cadence}</small></span><select value={task.ownerId} onChange={e=>onChange(reassignHouseholdLabor(world,household.id,task.id,e.target.value))}>{household.responsibleAdultIds.map(id=><option key={id} value={id}>{nameFor(world,id)}</option>)}</select></div>)}</div><div className="schedule-list">{household.schedule.slice(0,12).map(s=><div className="schedule-row" key={s.id}><span>{nameFor(world,s.personId)}</span><small>{s.label} · {s.startHour}:00–{s.endHour}:00</small></div>)}</div></Section>}
    {pregnancy&&<Section title="Growing family"><article className="child-card"><Baby size={22}/><h3>Pregnancy in progress</h3><p>Expected due date: {fmtDate(pregnancy.dueDate)} · {pregnancy.planned?'Planned':'Unplanned/open circumstance'}</p></article></Section>}
    {children.length>0&&<Section title="Children & parenting" subtitle="Children are full people whose development responds gradually, not mechanically."><div className="family-grid">{children.map(child=><article className="child-card" key={child.id}><span className="eyebrow">{child.childDevelopment?.stage.replace('_',' ').toUpperCase()}</span><h3>{child.name}</h3><p>{child.age} years old · {child.currentFocus}</p><div className="action-row"><ParentButton label="Quality time" action="quality_time" world={world} childId={child.id} onChange={onChange}/><ParentButton label="Support" action="support" world={world} childId={child.id} onChange={onChange}/><ParentButton label="Structure" action="structure" world={world} childId={child.id} onChange={onChange}/></div></article>)}</div></Section>}
    {custody.length>0&&<Section title="Co-parenting"><>{custody.map(c=><article className="custody-card" key={c.id}><span className="eyebrow">{c.arrangement.replace('_',' ').toUpperCase()}</span><h3>{nameFor(world,c.childId)}</h3><p>Current home: {world.households.find(h=>h.id===c.currentHouseholdId)?.name??'Household'}</p><small>{c.monthlySupport>0?`${money.format(c.monthlySupport)} monthly support`:'No monthly support order in the current arrangement'}</small></article>)}</></Section>}
    <Section title="Family network"><div className="family-grid">{world.familyLinks.filter(f=>!f.endedDate&&(f.fromId===player||f.toId===player)).slice(0,12).map(link=><article className="family-link" key={link.id}><b>{nameFor(world,link.fromId)} → {nameFor(world,link.toId)}</b><small>{link.relation.replace('_',' ')}</small></article>)}</div></Section>
  </>;
}

function PersonCard({world,npcId,onChange}:{world:WorldState;npcId:string;onChange:(w:WorldState)=>void}){
  const[text,setText]=useState(''),npc=world.npcs.find(n=>n.id===npcId)!,rel=world.relationships.find(r=>r.fromId===world.character.id&&r.toId===npcId),p=partnershipFor(world,world.character.id,npcId),potential=relationshipPotential(world,world.character.id,npcId),eligible=romanceEligible(world,world.character.id,npcId),latest=world.conversations.find(c=>c.personIds.includes(npcId)&&c.personIds.includes(world.character.id));
  const actions:RelationshipAction[]=[];if(!p&&eligible)actions.push('ask_date');if(p?.status==='dating')actions.push('exclusive');if(p&&['exclusive','engaged'].includes(p.status)&&!p.cohabitingHouseholdId)actions.push('move_in');if(p?.status==='exclusive')actions.push('engage');if(p?.status==='engaged')actions.push('marry');if(p?.status==='married')actions.push('separate');if(p?.status==='separated')actions.push('divorce');
  const submit=()=>{if(!text.trim())return;onChange(haveConversation(world,npcId,text));setText('');};
  return <article className="person-card"><div className="person-row bare"><div className="avatar small">{initials(npc.name)}</div><div className="person-copy"><h3>{npc.name}</h3><p>{npc.role} · {npc.location}</p><small>{relationshipSignal(rel)}</small><small>{p?`${partnershipLabel(p.status)}${p.cohabitingHouseholdId?' · living together':''}`:eligible?potential.chemistry>=60?'There seems to be some chemistry.':'The romantic picture is uncertain.':'No clear romantic possibility.'}</small></div><HeartHandshake size={20}/></div>{actions.length>0&&<div className="action-row">{actions.map(a=><button className="secondary-btn" key={a} onClick={()=>onChange(attemptRelationshipStep(world,npcId,a))}>{actionLabel(a)}</button>)}</div>}{p&&['exclusive','engaged','married'].includes(p.status)&&<FamilyPlanControl partnership={p} world={world} onChange={onChange}/>}<div className="conversation-box"><MessageCircle size={17}/><input placeholder={`Talk to ${npc.name.split(' ')[0]}…`} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit();}}/><button onClick={submit}>Send</button></div>{latest&&<p className="reply">{latest.response}</p>}</article>;
}
function FamilyPlanControl({partnership,world,onChange}:{partnership:Partnership;world:WorldState;onChange:(w:WorldState)=>void}){return <label className="compact-select"><span>Family plan</span><select value={partnership.familyPlan} onChange={e=>onChange(setFamilyPlan(world,partnership.id,e.target.value as Partnership['familyPlan']))}><option value="avoid">Avoid pregnancy</option><option value="not_now">Not now</option><option value="open">Open to it</option><option value="trying">Trying</option></select></label>;}
function ParentButton({label,action,world,childId,onChange}:{label:string;action:ParentingAction;world:WorldState;childId:string;onChange:(w:WorldState)=>void}){return <button className="secondary-btn" onClick={()=>onChange(applyParentingAction(world,childId,action))}>{label}</button>;}

function WorldView({world}:{world:WorldState}){
  const privateSecrets=world.secrets.filter(s=>!s.knownBy.some(k=>k.personId===world.character.id)).length;
  return <><div className="metric-grid"><Metric label="Inflation" value={`${world.economy.inflationRate.toFixed(1)}%`} detail="Annualized environment"/><Metric label="Unemployment" value={`${world.economy.unemploymentRate.toFixed(1)}%`} detail="Labor market"/><Metric label="Labor demand" value={`${Math.round(world.laborMarket.demandIndex)}/100`} detail={`${Math.round(world.laborMarket.remoteShare)}% remote share`}/><Metric label="Market" value={titleCase(world.market.regime)} detail={`Equity index ${world.market.usEquityIndex.toFixed(1)}`}/></div>
    <Section title="Living-world engine"><div className="world-engine"><div><Target size={20}/><span><b>{world.npcActivity.length}</b><small>NPC decisions remembered</small></span></div><div><Users size={20}/><span><b>{world.npcs.length}</b><small>People currently represented</small></span></div><div><Brain size={20}/><span><b>Hidden</b><small>{privateSecrets} private truths exist outside your knowledge</small></span></div></div></Section>
    <Section title="Economic institutions"><div className="institution-grid">{world.employers.map(e=><article className="institution-card" key={e.id}><BriefcaseBusiness size={19}/><b>{e.name}</b><small>{e.industry} · stability {Math.round(e.stability)}</small></article>)}{world.educationInstitutions.map(i=><article className="institution-card" key={i.id}><GraduationCap size={19}/><b>{i.name}</b><small>{i.kind.replace('_',' ')} · quality {Math.round(i.quality)}</small></article>)}</div></Section>
  </>;
}
function Timeline({world}:{world:WorldState}){const personal=world.character.human.memories.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10);return <><Section title="Life timeline">{world.memories.map(m=><article className="memory" key={m.id}><time>{fmtDate(m.date)}</time><div><h3>{m.title}</h3><p>{m.summary}</p></div></article>)}</Section><Section title="Personal memory">{personal.length?personal.map(m=><article className="memory subtle" key={m.id}><time>{fmtDate(m.date)}</time><div><span className="eyebrow">{m.kind.toUpperCase()}</span><p>{m.summary}</p></div></article>):<Empty text="No additional long-term memories have formed yet."/>}</Section></>;}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;}
function Section({title,subtitle,children}:{title:string;subtitle?:string;children:ReactNode}){return <section className="section"><header><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</header><div className="section-body">{children}</div></section>;}
function Empty({text}:{text:string}){return <div className="empty"><CircleDollarSign size={26}/><p>{text}</p></div>;}
function initials(name:string){return name.split(' ').map(x=>x[0]).join('').slice(0,2);}
function titleCase(v:string){return v.charAt(0).toUpperCase()+v.slice(1);}
function energyLabel(v:number){return v>=78?'Strong':v>=58?'Steady':v>=38?'Low':'Drained';}
function stressLabel(v:number){return v>=76?'Heavy':v>=56?'Building':v>=34?'Manageable':'Light';}
function goalProgressText(v:number){return v>=78?'You have made substantial progress.':v>=48?'This has real momentum.':v>=18?'You have started moving this forward.':'This is still mostly an intention.';}
function actionLabel(a:RelationshipAction){return({ask_date:'Ask on a date',exclusive:'Become exclusive',move_in:'Move in together',engage:'Propose',marry:'Get married',separate:'Separate',divorce:'Finalize divorce'} as const)[a];}
function nameFor(world:WorldState,id:string){if(id===world.character.id)return`${world.character.firstName} ${world.character.lastName}`;return world.npcs.find(n=>n.id===id)?.name??'Unknown person';}
function institutionName(world:WorldState,id:string){return world.educationInstitutions.find(i=>i.id===id)?.name??'Institution';}
