import { useEffect, useMemo, useState } from 'react';
import { Accessibility, ChevronLeft, ChevronRight, Dumbbell, HeartHandshake, Shield, Sparkles, Users } from 'lucide-react';
import type { CharacterDraft } from '../simulation/createWorld';
import type { GameMode, ScenarioId } from '../types/gameplay';
import { applyAccessibilityPreferences, configurationForMode, defaultAccessibility, defaultSeriousContent } from '../simulation/gameConfig';
import { Logo } from './Logo';

const Slider=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className="slider-row"><span>{label}<b>{value}</b></span><input type="range" min="0" max="100" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const modeCopy:Record<GameMode,{title:string;body:string;tag:string}>={
  life:{title:'Life Mode',body:'The standard EVERA experience. The world is unfair sometimes, but neither unusually forgiving nor unusually punishing.',tag:'STANDARD'},
  hard:{title:'Hard Life',body:'Lower starting resources, stronger world shocks and greater mortality pressure. Preparation helps, but luck still matters.',tag:'CHALLENGING'},
  sandbox:{title:'Sandbox',body:'More starting resources, softer shocks and random mortality disabled. Built for experimentation rather than survival pressure.',tag:'FLEXIBLE'},
  legacy:{title:'Legacy Mode',body:'Standard realism with stronger emphasis on family continuity, descendants and building a multi-generation story.',tag:'GENERATIONS'},
  scenario:{title:'Scenario',body:'Begin from a defined life circumstance with its own deterministic constraints and starting pressure.',tag:'CURATED'}
};
const scenarioCopy:Record<Exclude<ScenarioId,'none'>,string>={fresh_start:'Fresh Start · very limited starting cash and extra economic pressure',career_rebuild:'Career Rebuild · begin between jobs while keeping your skills and experience',legacy_seed:'Legacy Seed · a dynasty-focused start with slightly stronger resources'};
const stepNames=['Mode','Identity','Traits','Family & content','Accessibility'];

export function CharacterCreator({onCreate}:{onCreate:(draft:CharacterDraft)=>void}){
  const[step,setStep]=useState(0);
  const[draft,setDraft]=useState<CharacterDraft>({firstName:'Alex',lastName:'Morgan',age:18,sex:'male',orientation:'straight',hometown:'Phoenix, Arizona',socioeconomicBackground:'stable',ambition:70,discipline:65,empathy:65,athleticism:60,analytical:62,emotional:62,creativity:60,confidence:62,patience:60,loyalty:70,impulsivity:42,riskTolerance:55,familyOrientation:65,athleticSpeed:60,athleticStrength:60,athleticEndurance:60,athleticAgility:60,athleticCoordination:60,athleticReaction:60,familyStructure:'single_parent',siblingCount:0,parentCloseness:78,gameMode:'life',scenarioId:'none',accessibility:{...defaultAccessibility},seriousContent:{...defaultSeriousContent}});
  const set=<K extends keyof CharacterDraft>(key:K,value:CharacterDraft[K])=>setDraft(d=>({...d,[key]:value}));
  const cfg=useMemo(()=>configurationForMode(draft.gameMode??'life',draft.scenarioId??'none',draft.accessibility,draft.seriousContent),[draft.gameMode,draft.scenarioId,draft.accessibility,draft.seriousContent]);
  useEffect(()=>applyAccessibilityPreferences(cfg),[cfg]);
  useEffect(()=>{if(draft.age<18&&draft.familyStructure==='independent')set('familyStructure','single_parent');},[draft.age,draft.familyStructure]);
  const valid=draft.firstName.trim().length>0&&draft.lastName.trim().length>0&&draft.hometown.trim().length>0&&(draft.gameMode!=='scenario'||draft.scenarioId!=='none');
  const next=()=>setStep(s=>Math.min(stepNames.length-1,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
  return <main className="creator-page guided-creator">
    <header className="creator-hero"><Logo/><p>Live one life. Shape generations.</p><h1>Create the life, not the outcome.</h1><p className="muted">You choose the starting circumstances. EVERA simulates what follows.</p></header>
    <ol className="creator-progress" aria-label="Character creation progress">{stepNames.map((name,index)=><li key={name} className={index===step?'active':index<step?'done':''}><button type="button" onClick={()=>index<=step&&setStep(index)} aria-current={index===step?'step':undefined}><span>{index+1}</span>{name}</button></li>)}</ol>
    <form onSubmit={e=>{e.preventDefault();if(valid&&step===stepNames.length-1)onCreate(draft);}}>
      {step===0&&<section className="creator-stage"><div className="stage-heading"><Sparkles/><div><span className="eyebrow">GAME MODE</span><h2>How should this world treat you?</h2><p>Modes change simulation rules, not whether choices have consequences.</p></div></div><div className="mode-grid">{(Object.keys(modeCopy) as GameMode[]).map(mode=>{const info=modeCopy[mode],selected=draft.gameMode===mode;return <button type="button" key={mode} className={`mode-card ${selected?'selected':''}`} onClick={()=>{set('gameMode',mode);set('scenarioId',mode==='scenario'?'fresh_start':'none');}} aria-pressed={selected}><span className="eyebrow">{info.tag}</span><h3>{info.title}</h3><p>{info.body}</p></button>;})}</div>{draft.gameMode==='scenario'&&<label className="scenario-select">Scenario<select value={draft.scenarioId} onChange={e=>set('scenarioId',e.target.value as ScenarioId)}><option value="fresh_start">{scenarioCopy.fresh_start}</option><option value="career_rebuild">{scenarioCopy.career_rebuild}</option><option value="legacy_seed">{scenarioCopy.legacy_seed}</option></select></label>}<div className="rule-summary"><Shield/><span><b>{modeCopy[draft.gameMode??'life'].title}</b><small>Starting resources ×{cfg.rules.startingCashMultiplier.toFixed(2)} · world shock pressure ×{cfg.rules.worldShockMultiplier.toFixed(2)} · mortality pressure ×{cfg.rules.mortalityMultiplier.toFixed(2)}</small></span></div></section>}
      {step===1&&<section className="creator-stage"><div className="stage-heading"><Users/><div><span className="eyebrow">IDENTITY & BACKGROUND</span><h2>Where does this life begin?</h2><p>These facts shape access, money, relationships and the local world. They do not determine destiny.</p></div></div><div className="panel"><div className="fields two"><label>First name<input value={draft.firstName} onChange={e=>set('firstName',e.target.value)}/></label><label>Last name<input value={draft.lastName} onChange={e=>set('lastName',e.target.value)}/></label></div><div className="fields two"><label>Starting age<input type="number" min="5" max="90" value={draft.age} onChange={e=>set('age',Math.max(5,Math.min(90,Number(e.target.value))))}/></label><label>Sex<select value={draft.sex} onChange={e=>set('sex',e.target.value as CharacterDraft['sex'])}><option value="male">Male</option><option value="female">Female</option></select></label></div><label>Romantic orientation<select value={draft.orientation} onChange={e=>set('orientation',e.target.value as CharacterDraft['orientation'])}><option value="straight">Straight</option><option value="gay">Gay / lesbian</option><option value="bisexual">Bisexual</option></select></label><label>Hometown<input value={draft.hometown} onChange={e=>set('hometown',e.target.value)} placeholder="City, region"/></label><label>Socioeconomic background<select value={draft.socioeconomicBackground} onChange={e=>set('socioeconomicBackground',e.target.value as CharacterDraft['socioeconomicBackground'])}><option value="struggling">Struggling</option><option value="working">Working class</option><option value="stable">Stable</option><option value="affluent">Affluent</option><option value="wealthy">Wealthy</option></select></label></div></section>}
      {step===2&&<section className="creator-stage"><div className="stage-heading"><Dumbbell/><div><span className="eyebrow">TRAITS & ABILITIES</span><h2>Define the starting tendencies.</h2><p>These can change over a lifetime. They influence friction and opportunity, not guaranteed outcomes.</p></div></div><div className="trait-columns"><section className="panel"><h3>Core tendencies</h3><Slider label="Ambition" value={draft.ambition} onChange={v=>set('ambition',v)}/><Slider label="Discipline" value={draft.discipline} onChange={v=>set('discipline',v)}/><Slider label="Empathy" value={draft.empathy} onChange={v=>set('empathy',v)}/><Slider label="Athletic baseline" value={draft.athleticism} onChange={v=>set('athleticism',v)}/></section><section className="panel"><h3>Mind & personality</h3><Slider label="Analytical" value={draft.analytical??60} onChange={v=>set('analytical',v)}/><Slider label="Emotional intelligence" value={draft.emotional??60} onChange={v=>set('emotional',v)}/><Slider label="Creativity" value={draft.creativity??60} onChange={v=>set('creativity',v)}/><Slider label="Confidence" value={draft.confidence??60} onChange={v=>set('confidence',v)}/><Slider label="Patience" value={draft.patience??60} onChange={v=>set('patience',v)}/><Slider label="Loyalty" value={draft.loyalty??70} onChange={v=>set('loyalty',v)}/><Slider label="Impulsivity" value={draft.impulsivity??40} onChange={v=>set('impulsivity',v)}/><Slider label="Risk tolerance" value={draft.riskTolerance??55} onChange={v=>set('riskTolerance',v)}/><Slider label="Family orientation" value={draft.familyOrientation??65} onChange={v=>set('familyOrientation',v)}/></section></div><details className="advanced-card"><summary>Advanced athletic profile</summary><p>Use the baseline above for a quick setup, or tune each physical dimension.</p><div className="trait-columns"><div><Slider label="Speed" value={draft.athleticSpeed??draft.athleticism} onChange={v=>set('athleticSpeed',v)}/><Slider label="Strength" value={draft.athleticStrength??draft.athleticism} onChange={v=>set('athleticStrength',v)}/><Slider label="Endurance" value={draft.athleticEndurance??draft.athleticism} onChange={v=>set('athleticEndurance',v)}/></div><div><Slider label="Agility" value={draft.athleticAgility??draft.athleticism} onChange={v=>set('athleticAgility',v)}/><Slider label="Coordination" value={draft.athleticCoordination??draft.athleticism} onChange={v=>set('athleticCoordination',v)}/><Slider label="Reaction" value={draft.athleticReaction??draft.athleticism} onChange={v=>set('athleticReaction',v)}/></div></div></details></section>}
      {step===3&&<section className="creator-stage"><div className="stage-heading"><HeartHandshake/><div><span className="eyebrow">FAMILY & SERIOUS CONTENT</span><h2>Choose the starting family and your boundaries.</h2><p>Family members become persistent people. Content controls change what the simulation is allowed to generate.</p></div></div><div className="trait-columns"><section className="panel"><h3>Starting family</h3><label>Family structure<select value={draft.familyStructure} onChange={e=>set('familyStructure',e.target.value as CharacterDraft['familyStructure'])}><option value="two_parent">Two-parent household/background</option><option value="single_parent">Single-parent household/background</option><option value="guardian">Guardian household/background</option><option value="independent" disabled={draft.age<18}>Independent start</option></select></label><label>Number of siblings<input type="number" min="0" max="4" value={draft.siblingCount??0} onChange={e=>set('siblingCount',Math.max(0,Math.min(4,Number(e.target.value))))}/></label><Slider label="Closeness with parent / guardian" value={draft.parentCloseness??78} onChange={v=>set('parentCloseness',v)}/><p className="muted small">Adult starts keep family relationships without automatically living in the same household.</p></section><section className="panel content-controls"><h3>Serious content</h3><Toggle label="Premature death can occur" checked={draft.seriousContent?.allowPrematureDeath??true} onChange={v=>set('seriousContent',{...(draft.seriousContent??defaultSeriousContent),allowPrematureDeath:v})}/><Toggle label="Pregnancy loss can occur" checked={draft.seriousContent?.allowPregnancyLoss??true} onChange={v=>set('seriousContent',{...(draft.seriousContent??defaultSeriousContent),allowPregnancyLoss:v})}/><Toggle label="Violent crime can appear" checked={draft.seriousContent?.allowViolentCrime??true} onChange={v=>set('seriousContent',{...(draft.seriousContent??defaultSeriousContent),allowViolentCrime:v})}/><Toggle label="Allow future addiction content" checked={draft.seriousContent?.allowAddiction??true} onChange={v=>set('seriousContent',{...(draft.seriousContent??defaultSeriousContent),allowAddiction:v})}/><Toggle label="Severe illness can occur" checked={draft.seriousContent?.allowSevereIllness??true} onChange={v=>set('seriousContent',{...(draft.seriousContent??defaultSeriousContent),allowSevereIllness:v})}/><p className="muted small">Implemented categories are blocked at generation when turned off. The addiction preference is stored for a future addiction system and does not imply one exists in v0.13.</p></section></div></section>}
      {step===4&&<section className="creator-stage"><div className="stage-heading"><Accessibility/><div><span className="eyebrow">ACCESSIBILITY & REVIEW</span><h2>Make the interface comfortable.</h2><p>These settings apply immediately and remain part of this save.</p></div></div><div className="trait-columns"><section className="panel content-controls"><h3>Display & motion</h3><label>Text size<select value={draft.accessibility?.textScale??'standard'} onChange={e=>set('accessibility',{...(draft.accessibility??defaultAccessibility),textScale:e.target.value as NonNullable<CharacterDraft['accessibility']>['textScale']})}><option value="standard">Standard</option><option value="large">Large</option><option value="extra_large">Extra large</option></select></label><Toggle label="High contrast" checked={draft.accessibility?.highContrast??false} onChange={v=>set('accessibility',{...(draft.accessibility??defaultAccessibility),highContrast:v})}/><Toggle label="Reduced motion" checked={draft.accessibility?.reducedMotion??false} onChange={v=>set('accessibility',{...(draft.accessibility??defaultAccessibility),reducedMotion:v})}/><Toggle label="Stronger keyboard focus" checked={draft.accessibility?.strongerFocus??false} onChange={v=>set('accessibility',{...(draft.accessibility??defaultAccessibility),strongerFocus:v})}/></section><section className="panel review-card"><h3>Your starting world</h3><Review label="Mode" value={modeCopy[draft.gameMode??'life'].title}/><Review label="Character" value={`${draft.firstName} ${draft.lastName}, age ${draft.age}`}/><Review label="Home" value={draft.hometown}/><Review label="Background" value={draft.socioeconomicBackground.replace('_',' ')}/><Review label="Family" value={`${(draft.familyStructure??'single_parent').replaceAll('_',' ')} · ${draft.siblingCount??0} sibling${draft.siblingCount===1?'':'s'}`}/><Review label="Accessibility" value={`${(draft.accessibility?.textScale??'standard').replace('_',' ')} text${draft.accessibility?.highContrast?' · high contrast':''}${draft.accessibility?.reducedMotion?' · reduced motion':''}`}/><div className="review-rule"><Shield/><p>No mode reveals the “correct” decision. EVERA shows facts your character could know and leaves uncertain outcomes uncertain.</p></div></section></div></section>}
      <footer className="creator-actions">{step>0?<button type="button" className="secondary-btn creator-back" onClick={back}><ChevronLeft/>Back</button>:<span/>}{step<stepNames.length-1?<button type="button" className="primary creator-next" onClick={next} disabled={step===1&&!valid}>Continue<ChevronRight/></button>:<button className="primary creator-next" disabled={!valid}>Begin this life<ChevronRight/></button>}</footer>
    </form>
  </main>;
}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;}
function Review({label,value}:{label:string;value:string}){return <div className="review-row"><small>{label}</small><b>{value}</b></div>;}