import { useState } from 'react';
import { Banknote, CarFront, CreditCard, Home, Landmark, PiggyBank, ShieldCheck, TrendingUp, WalletCards } from 'lucide-react';
import type { WorldState } from '../types/game';
import { buyHome, buyVehicle, chargeCreditCard, fileBankruptcy, investAmount, netWorth, openCreditCard, payLiability, transferBetweenAccounts } from '../simulation/financeEngine';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const fmtDate=(d:string)=>dateFmt.format(new Date(`${d}T12:00:00Z`));
export function FinancePanel({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){const[amount,setAmount]=useState(250),checking=world.financialAccounts.find(a=>a.id==='account-checking-player'),savings=world.financialAccounts.find(a=>a.id==='account-savings-player'),brokerage=world.financialAccounts.find(a=>a.id==='account-investment-player'),retirement=world.financialAccounts.find(a=>a.id==='account-retirement-player'),credit=world.creditProfiles.find(c=>c.personId===world.character.id),debt=world.liabilities.filter(l=>l.borrowerIds.includes(world.character.id)&&l.status!=='paid'),pastDue=world.recurringObligations.reduce((s,o)=>s+o.pastDueAmount,0),activeBills=world.recurringObligations.filter(o=>o.active&&o.ownerId===world.character.id);return <>
  <div className="metric-grid"><Metric label="Net worth" value={money.format(netWorth(world))} detail="Assets minus liabilities"/><Metric label="Checking" value={money.format(checking?.balance??0)} detail="Authoritative liquid cash"/><Metric label="Credit" value={credit?.score?String(credit.score):'No file'} detail={credit?`${Math.round(credit.utilization)}% utilization`:'Not established'}/><Metric label="Past due" value={money.format(pastDue)} detail={pastDue>0?'Needs attention':'Current'}/></div>
  <Section title="Accounts" subtitle="Money moves between real account balances now."><div className="finance-grid">{world.financialAccounts.filter(a=>a.status==='open').map(a=><article className="finance-card" key={a.id}><WalletCards size={20}/><span className="eyebrow">{a.type.toUpperCase()}</span><h3>{a.name}</h3><strong>{money.format(a.balance)}</strong><small>{a.apy>0?`${a.apy.toFixed(2)}% APY`:a.institution}</small></article>)}</div><div className="money-action-row"><NumberField value={amount} onChange={setAmount}/><button className="secondary-btn" onClick={()=>onChange(transferBetweenAccounts(world,'account-checking-player','account-savings-player',amount))}><PiggyBank size={16}/>Save</button><button className="secondary-btn" onClick={()=>onChange(investAmount(world,'account-investment-player','us_equity',amount))}><TrendingUp size={16}/>Invest</button></div></Section>
  <Section title="Bills & obligations" subtitle="If cash is short, the unpaid amount survives as past due state."><div className="obligation-list">{activeBills.map(o=><div className={`obligation-row ${o.pastDueAmount>0?'past-due':''}`} key={o.id}><span><b>{o.name}</b><small>{o.frequency} · next {fmtDate(o.nextDueDate)}</small></span><span><strong>{money.format(o.amount)}</strong>{o.pastDueAmount>0&&<small>{money.format(o.pastDueAmount)} past due</small>}</span></div>)}</div></Section>
  <Section title="Debt & credit" subtitle="APR, utilization, payment history and defaults persist."><div className="finance-grid">{debt.map(l=><article className="finance-card" key={l.id}><CreditCard size={20}/><span className="eyebrow">{l.status.toUpperCase()}</span><h3>{l.kind.replace('_',' ')}</h3><strong>{money.format(l.principal)}</strong><small>{l.apr.toFixed(1)}% APR · min {money.format(l.minimumPayment)}</small><button className="secondary-btn mini" onClick={()=>onChange(payLiability(world,l.id,Math.min(amount,l.principal)))}>Pay {money.format(Math.min(amount,l.principal))}</button></article>)}</div>{!debt.some(l=>l.kind==='credit_card')&&<button className="secondary-btn" onClick={()=>onChange(openCreditCard(world,3000))}>Apply for starter credit card</button>}{debt.filter(l=>l.kind==='credit_card'&&l.status!=='default').map(card=><div className="money-action-row" key={`charge-${card.id}`}><button className="secondary-btn" onClick={()=>onChange(chargeCreditCard(world,card.id,Math.min(amount,500),'Everyday purchase'))}>Put {money.format(Math.min(amount,500))} on card</button></div>)}{debt.some(l=>['credit_card','personal'].includes(l.kind))&&<button className="secondary-btn danger-soft" onClick={()=>onChange(fileBankruptcy(world))}>Consider bankruptcy</button>}</Section>
  <Section title="Housing & vehicles" subtitle="Major purchases create assets, financing, insurance and long-term consequences."><div className="finance-grid">{world.properties.filter(p=>p.status==='owned').map(p=><article className="finance-card" key={p.id}><Home size={20}/><span className="eyebrow">PROPERTY</span><h3>{p.description}</h3><strong>{money.format(p.marketValue)}</strong><small>Condition {Math.round(p.condition)} · {p.location}</small></article>)}{world.vehicles.filter(v=>v.status==='owned').map(v=><article className="finance-card" key={v.id}><CarFront size={20}/><span className="eyebrow">VEHICLE</span><h3>{v.description}</h3><strong>{money.format(v.marketValue)}</strong><small>{v.mileage.toLocaleString()} miles · condition {Math.round(v.condition)}</small></article>)}</div><div className="money-action-row">{world.vehicles.filter(v=>v.status==='owned').length===0&&<button className="secondary-btn" onClick={()=>onChange(buyVehicle(world,'suv',30000,3000))}><CarFront size={16}/>Buy $30k SUV</button>}{world.properties.filter(p=>p.kind==='primary_home'&&p.status==='owned').length===0&&<button className="secondary-btn" onClick={()=>onChange(buyHome(world,180000,18000))}><Home size={16}/>Try $180k home purchase</button>}</div></Section>
  <Section title="Protection & markets"><div className="finance-grid">{world.insurancePolicies.filter(p=>p.active).map(p=><article className="finance-card" key={p.id}><ShieldCheck size={20}/><span className="eyebrow">{p.kind.toUpperCase()}</span><h3>{p.provider}</h3><strong>{money.format(p.premiumMonthly)}/mo</strong><small>{money.format(p.deductible)} deductible</small></article>)}<article className="finance-card"><Landmark size={20}/><span className="eyebrow">MARKET</span><h3>{world.market.regime} regime</h3><strong>{world.market.usEquityIndex.toFixed(1)}</strong><small>US equity index · vol {world.market.volatility.toFixed(1)}</small></article></div></Section>
  <Section title="Recent transactions">{world.ledger.length===0?<div className="empty"><Banknote size={26}/><p>No transactions yet.</p></div>:world.ledger.slice(0,18).map(t=><div className="transaction" key={t.id}><div><b>{t.description}</b><small>{fmtDate(t.date)} · {t.category}</small></div><strong className={t.amount>=0?'positive':''}>{t.amount>=0?'+':''}{money.format(t.amount)}</strong></div>)}</Section>
  {world.bankruptcyRecords.length>0&&<Section title="Financial history"><>{world.bankruptcyRecords.map(b=><article className="finance-card" key={b.id}><span className="eyebrow">BANKRUPTCY · {b.status.toUpperCase()}</span><h3>Filed {fmtDate(b.filedDate)}</h3><p>Credit penalty horizon: {fmtDate(b.creditPenaltyUntil)}</p></article>)}</></Section>}
</>;}
function NumberField({value,onChange}:{value:number;onChange:(v:number)=>void}){return <label className="money-field"><span>Amount</span><input type="number" min="1" step="50" value={value} onChange={e=>onChange(Math.max(1,Number(e.target.value)||1))}/></label>;}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;}
function Section({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="section"><header><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</header><div className="section-body">{children}</div></section>;}
