import { FileText, Gavel, Landmark, Scale, ShieldAlert, UsersRound } from 'lucide-react';
import type { WorldState } from '../types/game';
import type { OffenseKind } from '../types/legacyLegal';
import { chooseCriminalResponse, commitOffense, respondCivilCase, setCriminalRepresentation } from '../simulation/legalEngine';
import { continueAsDescendant, eligibleDescendants, setEstatePlan } from '../simulation/mortalityEstateEngine';
import { isDeceased, isIncarcerated } from '../simulation/legacyLegalSeed';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const fmtDate=(d:string)=>dateFmt.format(new Date(`${d}T12:00:00Z`));
function nameFor(world:WorldState,id:string){if(id===world.character.id)return`${world.character.firstName} ${world.character.lastName}`;return world.npcs.find(n=>n.id===id)?.name??world.ancestorArchives.find(a=>a.personId===id)?.name??'Unknown person';}
function defaultHeirs(world:WorldState){const player=world.character.id,spouse=world.partnerships.find(p=>p.status==='married'&&p.personIds.includes(player))?.personIds.find(id=>id!==player),children=world.familyLinks.filter(f=>f.fromId===player&&!f.endedDate&&['biological_parent','adoptive_parent'].includes(f.relation)).map(f=>f.toId).filter(id=>!isDeceased(world,id)),ids=[...(spouse&&!isDeceased(world,spouse)?[spouse]:[]),...children];if(ids.length)return[...new Set(ids)];const parent=world.familyLinks.find(f=>f.fromId===player&&!f.endedDate&&['biological_child','adoptive_child'].includes(f.relation)&&!isDeceased(world,f.toId))?.toId;return parent?[parent]:[];}
function offenseLabel(kind:OffenseKind){return({theft:'Theft',fraud:'Fraud',assault:'Assault',impaired_driving:'Impaired driving',property_offense:'Property offense'} as const)[kind];}

export function LegacyLegalPanel({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  if(isDeceased(world,world.character.id))return <DeathContinuation world={world} onChange={onChange}/>;
  const player=world.character.id,plan=world.estatePlans.find(p=>p.personId===player),heirs=defaultHeirs(world),criminalCases=world.criminalCases.filter(c=>c.defendantId===player&&!['dismissed','convicted','acquitted','closed'].includes(c.status)),records=world.criminalRecords.filter(r=>r.personId===player&&r.active),civil=world.civilCases.filter(c=>(c.plaintiffId===player||c.defendantId===player)&&!['settled','judgment','dismissed'].includes(c.status)),incarceration=world.incarcerationRecords.find(r=>r.personId===player&&r.status==='incarcerated'),offenses:OffenseKind[]=['theft','fraud','assault','impaired_driving','property_offense'];
  return <section className="section legacy-legal"><header><h2>Legacy & legal life</h2><p>Estate choices, legal consequences and criminal history persist. Outcomes are uncertain and the world does not erase what happened.</p></header><div className="section-body">
    <div className="legal-grid"><article className="legacy-card"><div className="legacy-head"><FileText size={20}/><div><span className="eyebrow">ESTATE PLAN</span><h3>{plan?.hasWill?'Will on file':'No will on file'}</h3></div></div><p>{plan?.hasWill?`${plan.beneficiaries.length} named ${plan.beneficiaries.length===1?'beneficiary':'beneficiaries'}.`:'Without a will, the estate will use the simulated jurisdiction’s intestacy order.'}</p>{plan?.beneficiaries.length?<div className="legacy-rows">{plan.beneficiaries.map(b=><small key={b.personId}>{nameFor(world,b.personId)} · {Math.round(b.share)}%</small>)}</div>:null}<button className="secondary-btn" disabled={!heirs.length} onClick={()=>onChange(setEstatePlan(world,heirs))}>{plan?.hasWill?'Update will to current family':'Create family will'}</button>{!heirs.length&&<small>No eligible close-family beneficiary is currently available.</small>}</article>
      <article className="legacy-card"><div className="legacy-head"><Scale size={20}/><div><span className="eyebrow">LEGAL STATUS</span><h3>{incarceration?'Incarcerated':criminalCases.length?'Open criminal case':records.length?'Criminal record':'No active criminal case'}</h3></div></div>{incarceration?<p>Current incarceration is scheduled through {fmtDate(incarceration.endDate)}. The world continues while time passes.</p>:records.length?<p>{records.length} active conviction {records.length===1?'record can':'records can'} affect hiring and other opportunities.</p>:<p>No active conviction record is currently affecting this life.</p>}</article></div>
    {criminalCases.map(c=><article className="legal-case" key={c.id}><span className="eyebrow">CRIMINAL CASE · {c.status.toUpperCase()}</span><h3>{offenseLabel(world.crimeIncidents.find(i=>i.id===c.incidentId)?.offense??'property_offense')}</h3><p>Representation: {c.representation.replaceAll('_',' ')}. A charge is not a conviction.</p><div className="action-row">{c.status==='charged'&&<><button className="secondary-btn" onClick={()=>onChange(chooseCriminalResponse(world,c.id,'plead'))}>Enter plea</button><button className="secondary-btn" onClick={()=>onChange(chooseCriminalResponse(world,c.id,'contest'))}>Contest charge</button></>}<button className="secondary-btn" onClick={()=>onChange(setCriminalRepresentation(world,c.id,'public_defender'))}>Public defender</button><button className="secondary-btn" onClick={()=>onChange(setCriminalRepresentation(world,c.id,'private_attorney'))}>Private attorney</button></div></article>)}
    {civil.map(c=><article className="legal-case" key={c.id}><span className="eyebrow">CIVIL CASE · {c.status.toUpperCase()}</span><h3>{c.category.replaceAll('_',' ')}</h3><p>{c.plaintiffId===player?'You are the plaintiff.':'You are the defendant.'} Claimed amount: {money.format(c.amountClaimed)}.</p>{['filed','negotiating'].includes(c.status)&&<div className="action-row"><button className="secondary-btn" onClick={()=>onChange(respondCivilCase(world,c.id,'settle'))}>Pursue settlement</button><button className="secondary-btn" onClick={()=>onChange(respondCivilCase(world,c.id,'trial'))}>Go to trial</button></div>}</article>)}
    {records.length>0&&<div className="health-subsection"><h3><Gavel size={18}/>Criminal record</h3>{records.map(r=><div className="medical-row" key={r.id}><span><b>{offenseLabel(r.offense)}</b><small>Convicted {fmtDate(r.convictionDate)}</small></span><small>Persistent record</small></div>)}</div>}
    <div className="risk-box"><div className="legacy-head"><ShieldAlert size={20}/><div><span className="eyebrow">RISKY / ILLEGAL CHOICES</span><h3>Actions have discovery risk</h3></div></div><p>Illegal actions are recorded as world events. Discovery, evidence, investigation and conviction are separate systems rather than automatic punishment.</p><div className="action-row">{offenses.map(o=><button className="secondary-btn danger-soft" key={o} disabled={isIncarcerated(world,player)} onClick={()=>onChange(commitOffense(world,o))}>{offenseLabel(o)}</button>)}</div></div>
  </div></section>;
}

function DeathContinuation({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  const death=world.deathRecords.find(d=>d.personId===world.character.id),estate=world.estateCases.find(e=>e.decedentId===world.character.id),funeral=world.funeralRecords.find(f=>f.decedentId===world.character.id),descendants=eligibleDescendants(world,world.character.id);if(!death)return null;
  return <section className="section death-continuation"><header><span className="eyebrow">THIS LIFE HAS ENDED</span><h2>{world.character.firstName} {world.character.lastName}, age {death.age}</h2><p>{death.summary} Time is paused until you choose how this family story continues.</p></header><div className="section-body"><div className="death-summary"><article><Landmark size={21}/><span><b>{death.cause.replaceAll('_',' ')}</b><small>{fmtDate(death.date)}</small></span></article><article><FileText size={21}/><span><b>{estate?money.format(estate.netEstate):'Estate recorded'}</b><small>{estate?'Net estate after modeled debts and funeral costs':'Estate settlement unavailable'}</small></span></article><article><UsersRound size={21}/><span><b>{funeral?.attendeeIds.length??0} remembered attendees</b><small>The event remains in family history.</small></span></article></div><div className="continuation-list">{descendants.map(d=>{const distribution=estate?.distributions.find(x=>x.personId===d.id)?.amount??0;return <article className="continuation-card" key={d.id}><div><span className="eyebrow">ELIGIBLE DESCENDANT</span><h3>{d.name}</h3><p>Age {d.age} · {d.currentFocus}</p><small>{money.format(distribution)} cash estate distribution recorded for this heir.</small></div><button className="primary" onClick={()=>onChange(continueAsDescendant(world,d.id))}>Continue as {d.name.split(' ')[0]}</button></article>;})}{!descendants.length&&<article className="continuation-card"><h3>No eligible descendant</h3><p>This family line has no living biological or adopted child with a simulatable identity available for continuation. You can preserve this finished world or start a new one from the reset control.</p></article>}</div></div></section>;
}
