import { useState } from 'react';
import { Car, ChefHat, Gamepad2, Home, Laptop, PawPrint, Plane, Shirt, Sparkles, UtensilsCrossed, Wrench } from 'lucide-react';
import type { WorldState } from '../types/game';
import type { FoodStrategy, HobbyKind, HomeUpgradeKind, ServiceKind, StyleIdentity } from '../types/lifestyle';
import { activeHouseholdForPerson } from '../simulation/householdEngine';
import { adoptPet, buyDevice, cancelHouseholdService, dineOut, improveHome, planTravel, practiceHobby, serviceVehicle, setFoodStrategy, setStyleIdentity, startHobby, subscribeHouseholdService } from '../simulation/lifestyleEngine';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function label(v:string){return v.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());}

export function LifestylePanel({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  const p=world.lifestyleProfiles.find(x=>x.personId===world.character.id),household=activeHouseholdForPerson(world,world.character.id),home=household?world.homeLifestyles.find(h=>h.householdId===household.id):undefined,hobbies=world.hobbies.filter(h=>h.personId===world.character.id&&h.active),pets=household?world.pets.filter(p=>p.householdId===household.id&&p.status==='alive'):[],services=household?world.householdServices.filter(s=>s.householdId===household.id&&s.active):[],devices=world.deviceAssets.filter(d=>d.ownerId===world.character.id&&d.status==='active'),vehicles=world.vehicles.filter(v=>v.ownerIds.includes(world.character.id)&&v.status==='owned'),upcoming=world.travelPlans.filter(t=>['planned','active'].includes(t.status)).slice(0,3);
  const[petName,setPetName]=useState('Milo');
  if(!p)return null;
  const friend=world.npcs.find(n=>n.id==='npc-friend');
  return <section className="section lifestyle-panel"><header><h2>Everyday life</h2><p>Your home, food, time, hobbies, travel and possessions shape the life between major events.</p></header><div className="section-body">
    <div className="lifestyle-summary">
      <article><Home size={20}/><span><b>{home?`${Math.round(home.comfort)} comfort`:'Home not established'}</b><small>{home?`${Math.round(home.spacePressure)} space pressure · ${home.bedrooms} bed / ${home.bathrooms} bath`:'Housing state is still settling.'}</small></span></article>
      <article><ChefHat size={20}/><span><b>{label(p.foodStrategy)} food strategy</b><small>Cooking skill {Math.round(p.cookingSkill)} · family meals {Math.round(p.familyMealFrequency)}</small></span></article>
      <article><Shirt size={20}/><span><b>{label(p.styleIdentity)} style</b><small>Wardrobe {Math.round(p.wardrobeQuality)} · grooming {Math.round(p.grooming)}</small></span></article>
      <article><Sparkles size={20}/><span><b>{Math.round(p.timePressure)} time pressure</b><small>Convenience preference {Math.round(p.conveniencePreference)}</small></span></article>
    </div>

    <div className="lifestyle-block"><div className="lifestyle-block-head"><UtensilsCrossed size={19}/><div><h3>Food & social life</h3><p>Food strategy changes recurring grocery cost, health/time tradeoffs and family routines.</p></div></div><div className="chip-row">{(['budget','standard','healthy','premium','convenience'] as FoodStrategy[]).map(s=><button key={s} className={p.foodStrategy===s?'chip active':'chip'} onClick={()=>onChange(setFoodStrategy(world,s))}>{label(s)}</button>)}</div><div className="action-row"><button className="secondary-btn" onClick={()=>onChange(dineOut(world,friend?[friend.id]:[]))}>Dinner with {friend?.name.split(' ')[0]??'a friend'}</button><button className="secondary-btn" onClick={()=>onChange(dineOut(world,friend?[friend.id]:[],'entertainment'))}>Go out together</button></div></div>

    {home&&<div className="lifestyle-block"><div className="lifestyle-block-head"><Home size={19}/><div><h3>Home & space</h3><p>Comfort, maintenance and crowding affect stress, autonomy and household life.</p></div></div><div className="lifestyle-meters"><span><b>{Math.round(home.comfort)}</b><small>Comfort</small></span><span><b>{Math.round(home.maintenance)}</b><small>Maintenance</small></span><span><b>{Math.round(home.organization)}</b><small>Organization</small></span><span><b>{Math.round(home.privacy)}</b><small>Privacy</small></span></div><div className="chip-row">{(['furniture','decor','office','fitness','entertainment','appliance','child_space'] as HomeUpgradeKind[]).map(k=><button key={k} className="chip" onClick={()=>onChange(improveHome(world,k))}>{label(k)}</button>)}</div></div>}

    <div className="lifestyle-block"><div className="lifestyle-block-head"><Gamepad2 size={19}/><div><h3>Hobbies</h3><p>Repeated hobbies build skill, recreation and sometimes social opportunity.</p></div></div>{hobbies.map(h=><div className="lifestyle-row" key={h.id}><span><b>{h.name}</b><small>Skill {Math.round(h.skill)} · enjoyment {Math.round(h.enjoyment)} · {money.format(h.monthlyCost)}/mo</small></span><button className="secondary-btn mini" onClick={()=>onChange(practiceHobby(world,h.id))}>Practice</button></div>)}<div className="chip-row">{(['gaming','music','art','cooking','outdoors','community','sports'] as HobbyKind[]).filter(k=>!hobbies.some(h=>h.kind===k)).slice(0,5).map(k=><button className="chip" key={k} onClick={()=>onChange(startHobby(world,k))}>Start {label(k)}</button>)}</div></div>

    <div className="lifestyle-block"><div className="lifestyle-block-head"><PawPrint size={19}/><div><h3>Pets</h3><p>Pets cost time and money, form individual attachments and age with the household.</p></div></div>{pets.length?pets.map(pet=><div className="lifestyle-row" key={pet.id}><span><b>{pet.name} · {label(pet.species)}</b><small>Health {Math.round(pet.health)} · {money.format(pet.monthlyCost)}/mo</small></span></div>):<p className="muted">No pets currently live in this household.</p>}<div className="pet-adopt"><input value={petName} onChange={e=>setPetName(e.target.value)} aria-label="Pet name"/><button className="secondary-btn" onClick={()=>onChange(adoptPet(world,'dog',petName))}>Adopt dog</button><button className="secondary-btn" onClick={()=>onChange(adoptPet(world,'cat',petName))}>Adopt cat</button></div></div>

    <div className="lifestyle-block"><div className="lifestyle-block-head"><Plane size={19}/><div><h3>Travel</h3><p>Trips reserve time, spend real money at departure and can strengthen or strain relationships.</p></div></div>{upcoming.map(t=><div className="lifestyle-row" key={t.id}><span><b>{t.destination}</b><small>{label(t.status)} · {t.startDate} → {t.endDate} · {money.format(t.budget)}</small></span></div>)}<div className="chip-row"><button className="chip" onClick={()=>onChange(planTravel(world,'San Diego, California',addDays(world.date,7),3,friend?[friend.id]:[],'standard','vacation'))}>Plan San Diego</button><button className="chip" onClick={()=>onChange(planTravel(world,'New York, New York',addDays(world.date,14),4,friend?[friend.id]:[],'premium','vacation'))}>Plan New York</button><button className="chip" onClick={()=>onChange(planTravel(world,'London, United Kingdom',addDays(world.date,21),6,friend?[friend.id]:[],'standard','vacation'))}>Plan London</button></div></div>

    <div className="lifestyle-block"><div className="lifestyle-block-head"><Sparkles size={19}/><div><h3>Buy back time</h3><p>Services trade money for hours and reduce pressure only if the household can keep paying.</p></div></div>{services.map(s=><div className="lifestyle-row" key={s.id}><span><b>{label(s.kind)}</b><small>{money.format(s.monthlyCost)}/mo · about {s.timeSavedHours} hours saved</small></span><button className="secondary-btn mini" onClick={()=>onChange(cancelHouseholdService(world,s.id))}>Cancel</button></div>)}<div className="chip-row">{(['cleaning','childcare','meal_service','landscaping','assistant','pet_care'] as ServiceKind[]).filter(k=>!services.some(s=>s.kind===k)).map(k=><button className="chip" key={k} onClick={()=>onChange(subscribeHouseholdService(world,k))}>{label(k)}</button>)}</div></div>

    <div className="lifestyle-block"><div className="lifestyle-block-head"><Laptop size={19}/><div><h3>Technology & style</h3><p>Devices wear out and presentation evolves without requiring daily outfit micromanagement.</p></div></div>{devices.map(d=><div className="lifestyle-row" key={d.id}><span><b>{d.name}</b><small>{label(d.kind)} · condition {Math.round(d.condition)} · capability {Math.round(d.capability)}</small></span></div>)}<div className="chip-row"><button className="chip" onClick={()=>onChange(buyDevice(world,'phone'))}>Replace phone</button><button className="chip" onClick={()=>onChange(buyDevice(world,'computer'))}>Replace computer</button>{(['practical','classic','sporty','fashion_forward','luxury'] as StyleIdentity[]).map(s=><button key={s} className={p.styleIdentity===s?'chip active':'chip'} onClick={()=>onChange(setStyleIdentity(world,s))}>{label(s)}</button>)}</div></div>

    {vehicles.length>0&&<div className="lifestyle-block"><div className="lifestyle-block-head"><Car size={19}/><div><h3>Vehicles in daily life</h3><p>Mileage, reliability and maintenance now matter beyond the loan payment.</p></div></div>{vehicles.map(v=>{const use=world.vehicleUseProfiles.find(p=>p.vehicleId===v.id);return <div className="lifestyle-row" key={v.id}><span><b>{v.description}</b><small>{Math.round(v.mileage).toLocaleString()} mi · condition {Math.round(v.condition)}{use?` · reliability ${Math.round(use.reliability)}`:''}</small></span><button className="secondary-btn mini" onClick={()=>onChange(serviceVehicle(world,v.id))}><Wrench size={14}/>Service</button></div>;})}</div>}
  </div></section>;
}
