import { Building2, Globe2, Hospital, MapPin, Newspaper, Plane, TrainFront, TrendingUp } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { WorldState } from '../types/game';
import { currentCity, currentCountry, currentNeighborhood, moveToCity } from '../simulation/livingWorldEngine';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const fmt=(n:number)=>Math.round(n);

export function LivingWorldPanel({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  const city=currentCity(world),country=currentCountry(world),hood=currentNeighborhood(world),[target,setTarget]=useState(world.currentCityId),[hoodId,setHoodId]=useState(world.currentNeighborhoodId??'');
  const targetCity=world.cities.find(c=>c.id===target),targetNeighborhoods=useMemo(()=>world.neighborhoods.filter(n=>n.cityId===target),[world.neighborhoods,target]);
  const localIndustries=world.industries.filter(i=>city?.industryIds.includes(i.id)).sort((a,b)=>b.demandIndex-a.demandIndex),institutions=world.worldInstitutions.filter(i=>i.cityId===city?.id),shocks=world.regionalShocks.filter(s=>s.status!=='resolved'&&(s.locationType==='global'||s.locationId===city?.id||s.locationId===country?.id)),news=world.worldNews.filter(n=>n.scope==='global'||n.locationId===city?.id||n.locationId===country?.id).slice(0,8);
  const household=world.households.find(h=>!h.endedDate&&h.memberIds.includes(world.character.id)),moveEstimate=targetCity?Math.round((targetCity.countryId===city?.countryId?1800:4200)*(world.neighborhoods.find(n=>n.id===hoodId)?.housingCostIndex??targetCity.housingIndex)):0;
  return <>
    <section className="section"><header><h2>Where you live matters</h2><p>Location changes wages, housing, schools, healthcare, transit, industries, immigration status and the kinds of shocks that reach your life.</p></header><div className="section-body">
      <article className="world-location-hero"><div><span className="eyebrow">CURRENT HOME</span><h3>{city?.name??world.character.location}</h3><p>{hood?.name??'Local area'} · {country?.name??'Country'}</p></div><MapPin size={28}/></article>
      <div className="world-metric-grid"><Metric label="Wages" value={`${city?.wageIndex.toFixed(2)??'1.00'}×`}/><Metric label="Housing" value={`${(hood?.housingCostIndex??city?.housingIndex??1).toFixed(2)}×`}/><Metric label="Unemployment" value={`${city?.unemploymentRate.toFixed(1)??world.economy.unemploymentRate.toFixed(1)}%`}/><Metric label="Transit" value={`${fmt(city?.transit??50)}/100`}/><Metric label="Safety" value={`${fmt(hood?.safety??city?.safety??50)}/100`}/><Metric label="Schools" value={`${fmt(hood?.schoolQuality??city?.schoolQuality??50)}/100`}/></div>
      {country&&<div className="country-strip"><Globe2 size={18}/><span><b>{country.name}</b><small>{country.healthcareModel.replaceAll('_',' ')} healthcare · tax environment {country.taxRate}% · retirement age {country.retirementAge}</small></span></div>}
      {household&&<small className="world-note">Current household housing cost: {money.format(household.monthlyHousingCost)}/mo.</small>}
    </div></section>

    <section className="section"><header><h2>Local economy & institutions</h2><p>These entities continue changing even when your character is focused elsewhere.</p></header><div className="section-body"><div className="world-two-col">
      <div><h3 className="subhead"><TrendingUp size={17}/>Industries</h3>{localIndustries.map(i=><article className="world-row" key={i.id}><span><b>{i.name}</b><small>Demand {fmt(i.demandIndex)}/100 · automation pressure {fmt(i.automationPressure)}/100</small></span><strong className={i.growth>=0?'positive':'negative'}>{i.growth>=0?'+':''}{i.growth.toFixed(1)}%</strong></article>)}</div>
      <div><h3 className="subhead"><Building2 size={17}/>Institutions</h3>{institutions.slice(0,6).map(i=><article className="world-row" key={i.id}>{i.kind==='hospital'?<Hospital size={17}/>:i.kind==='transit'?<TrainFront size={17}/>:<Building2 size={17}/>}<span><b>{i.name}</b><small>{i.kind} · quality {fmt(i.quality)} · {i.status}</small></span></article>)}</div>
    </div>{shocks.length>0&&<div className="shock-list">{shocks.map(s=><article className="shock-card" key={s.id}><span className="eyebrow">{s.status.toUpperCase()}</span><h3>{s.kind.replaceAll('_',' ')}</h3><p>Severity {fmt(s.severity)}/100. Employment, housing or infrastructure effects remain active in the simulation.</p></article>)}</div>}</div></section>

    <section className="section"><header><h2>Move somewhere new</h2><p>Moving is a real life change. It costs money, changes housing and local conditions, and an onsite job may not follow you.</p></header><div className="section-body"><div className="move-grid"><label><span>City</span><select value={target} onChange={e=>{setTarget(e.target.value);const next=world.neighborhoods.find(n=>n.cityId===e.target.value);setHoodId(next?.id??'');}}>{world.countries.map(country=><optgroup key={country.id} label={country.name}>{world.cities.filter(c=>c.countryId===country.id).map(c=><option key={c.id} value={c.id}>{c.name}, {c.region}</option>)}</optgroup>)}</select></label><label><span>Neighborhood</span><select value={hoodId} onChange={e=>setHoodId(e.target.value)}>{targetNeighborhoods.map(n=><option key={n.id} value={n.id}>{n.name} · housing {n.housingCostIndex.toFixed(2)}×</option>)}</select></label></div><div className="move-summary"><Plane size={20}/><span><b>{targetCity?.name??'Destination'}</b><small>Estimated moving cost: {money.format(moveEstimate)} · housing index {(world.neighborhoods.find(n=>n.id===hoodId)?.housingCostIndex??targetCity?.housingIndex??1).toFixed(2)}×</small></span><button className="primary" disabled={target===world.currentCityId} onClick={()=>onChange(moveToCity(world,target,hoodId))}>Move</button></div></div></section>

    <section className="section"><header><h2>World news</h2><p>News comes from stored simulation facts, not random flavor text.</p></header><div className="section-body">{news.length?<div className="world-news-list">{news.map(n=><article className="world-news" key={n.id}><Newspaper size={18}/><div><span className="eyebrow">{n.scope.toUpperCase()} · IMPORTANCE {fmt(n.importance)}</span><h3>{n.title}</h3><p>{n.summary}</p></div></article>)}</div>:<div className="world-empty">The world is moving, but nothing locally significant has reached the news yet.</div>}</div></section>
  </>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="world-metric"><small>{label}</small><strong>{value}</strong></div>;}
