import { Download, Settings2, Upload } from 'lucide-react';
import { useRef, useState } from 'react';
import type { WorldState } from '../types/game';
import type { AccessibilitySettings, SeriousContentSettings } from '../types/gameplay';
import { applyAccessibilityPreferences, updateAccessibilitySettings, updateSeriousContentSettings } from '../simulation/gameConfig';
import { parsePortableWorld, portableSaveFilename, serializePortableWorld } from '../persistence/portableSave';

function modeLabel(mode:WorldState['gameConfiguration']['mode']){return mode==='hard'?'Hard Life':mode==='sandbox'?'Sandbox':mode==='legacy'?'Legacy':mode==='scenario'?'Scenario':'Life Mode';}

export function PreferencesRecoveryPanel({world,onChange}:{world:WorldState;onChange:(world:WorldState)=>void}){
  const inputRef=useRef<HTMLInputElement|null>(null),[status,setStatus]=useState(''),[pending,setPending]=useState<WorldState|null>(null);
  const accessibility=world.gameConfiguration.accessibility,serious=world.gameConfiguration.seriousContent;
  const setAccess=<K extends keyof AccessibilitySettings>(key:K,value:AccessibilitySettings[K])=>{const next=updateAccessibilitySettings(world,{[key]:value} as Partial<AccessibilitySettings>);applyAccessibilityPreferences(next.gameConfiguration);onChange(next);};
  const setSerious=<K extends keyof SeriousContentSettings>(key:K,value:SeriousContentSettings[K])=>onChange(updateSeriousContentSettings(world,{[key]:value} as Partial<SeriousContentSettings>));
  const exportSave=()=>{const blob=new Blob([serializePortableWorld(world)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=portableSaveFilename(world);document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setStatus('Portable backup created.');};
  const chooseFile=async(file:File|null)=>{setPending(null);if(!file)return;const parsed=parsePortableWorld(await file.text());if(!parsed){setStatus('That file is not a valid EVERA save. Your current life was not changed.');return;}setPending(parsed);setStatus(`Ready to restore ${parsed.character.firstName} ${parsed.character.lastName}, dated ${parsed.date}. Review before replacing this life.`);};
  const restore=()=>{if(!pending)return;applyAccessibilityPreferences(pending.gameConfiguration);onChange(pending);setPending(null);setStatus('Portable save restored.');if(inputRef.current)inputRef.current.value='';};
  return <section className="section"><header><h2>Preferences & recovery</h2><p>Comfort settings can change. Your selected game mode stays part of this life.</p></header><div className="section-body preferences-stack">
    <article className="settings-card"><div className="settings-title"><Settings2 size={20}/><div><b>{modeLabel(world.gameConfiguration.mode)}</b><small>{world.gameConfiguration.mode==='scenario'&&world.gameConfiguration.scenarioId!=='none'?world.gameConfiguration.scenarioId.replaceAll('_',' '):'Mode rules are locked for this save.'}</small></div></div>
      <div className="settings-grid"><label>Text size<select value={accessibility.textScale} onChange={e=>setAccess('textScale',e.target.value as AccessibilitySettings['textScale'])}><option value="standard">Standard</option><option value="large">Large</option><option value="extra_large">Extra large</option></select></label><Toggle label="High contrast" checked={accessibility.highContrast} onChange={v=>setAccess('highContrast',v)}/><Toggle label="Reduced motion" checked={accessibility.reducedMotion} onChange={v=>setAccess('reducedMotion',v)}/><Toggle label="Stronger focus outlines" checked={accessibility.strongerFocus} onChange={v=>setAccess('strongerFocus',v)}/></div>
    </article>
    <article className="settings-card"><div><span className="eyebrow">SERIOUS CONTENT</span><h3>Future generated events</h3><p>Turning a category off does not erase events that already happened.</p></div><div className="settings-grid serious-grid"><Toggle label="Premature death" checked={serious.allowPrematureDeath} onChange={v=>setSerious('allowPrematureDeath',v)}/><Toggle label="Pregnancy loss" checked={serious.allowPregnancyLoss} onChange={v=>setSerious('allowPregnancyLoss',v)}/><Toggle label="Violent crime" checked={serious.allowViolentCrime} onChange={v=>setSerious('allowViolentCrime',v)}/><Toggle label="Severe illness" checked={serious.allowSevereIllness} onChange={v=>setSerious('allowSevereIllness',v)}/><Toggle label="Addiction content" checked={serious.allowAddiction} onChange={v=>setSerious('allowAddiction',v)}/></div><small className="settings-note">Addiction preference is preserved for future addiction systems; the current simulation does not yet generate addiction conditions.</small></article>
    <article className="settings-card"><div><span className="eyebrow">PORTABLE SAVE</span><h3>Back up or restore this world</h3><p>Exports include the canonical world state and can migrate older supported schemas when restored.</p></div><div className="recovery-actions"><button className="secondary-btn" onClick={exportSave}><Download size={16}/> Export JSON backup</button><button className="secondary-btn" onClick={()=>inputRef.current?.click()}><Upload size={16}/> Choose backup to restore</button><input ref={inputRef} className="sr-only" type="file" accept="application/json,.json" onChange={e=>void chooseFile(e.target.files?.[0]??null)}/></div>{status&&<p className="recovery-status" role="status">{status}</p>}{pending&&<div className="restore-confirm"><div><b>Replace the current life?</b><small>This will make the selected backup the active local save. Export the current life first if you want to preserve both.</small></div><button className="primary mini" onClick={restore}>Restore selected save</button><button className="secondary-btn" onClick={()=>{setPending(null);setStatus('Restore cancelled. Your current life was not changed.');}}>Cancel</button></div>}</article>
  </div></section>;
}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;}
