import type { WorldState } from '../types/game';
import type { AnnualLifeChapter, NarrationRequest } from '../types/narration';
import { haveConversation } from '../simulation/relationshipEngine';
import { compileAnnualChapterContext, compileSceneContext } from './contextCompiler';
import { generateOfflineNarration } from './offlineProvider';

function hash(text:string,seed:number){let h=seed>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
export function initializeNarration(world:WorldState){world.narrationSettings??={mode:'offline',preferredProvider:'evera-offline',allowRemoteNarration:false};world.annualLifeChapters??=[];return world;}
export function annualChapterForYear(world:WorldState,year:number){return world.annualLifeChapters.find(c=>c.year===year);}
export function buildAnnualLifeChapter(world:WorldState,year:number):AnnualLifeChapter{const context=compileAnnualChapterContext(world,year),request:NarrationRequest={id:`narration-annual-${year}`,purpose:'annual_chapter',context,deterministicSeed:hash(`annual:${year}`,world.seed)},result=generateOfflineNarration(request),canonical=context.facts.filter(f=>f.certainty==='canonical'&&f.allowedToStateAsFact),title=canonical.some(f=>f.category==='family'||f.category==='relationship')?`${year}: Life in motion`:canonical.some(f=>f.category==='career'||f.category==='business')?`${year}: Work and change`:canonical.some(f=>f.category==='sports')?`${year}: A season of competition`:`${year}: The year in your life`;return{id:`chapter-${year}`,year,generatedDate:world.date,providerId:result.providerId,title,text:result.text,sourceEventIds:context.recentEventIds,sourceMemoryIds:context.memoryIds,sourceFactIds:result.usedFactIds,enhanced:false};}
export function ensureAnnualLifeChapter(world:WorldState,year:number){initializeNarration(world);if(world.annualLifeChapters.some(c=>c.year===year))return world;world.annualLifeChapters.push(buildAnnualLifeChapter(world,year));world.annualLifeChapters.sort((a,b)=>b.year-a.year);return world;}
export function createDialogueNarrationRequest(world:WorldState,npcId:string,playerText:string):NarrationRequest{const context=compileSceneContext(world,'dialogue',npcId,world.character.id);return{id:`narration-dialogue-${npcId}-${world.date}`,purpose:'dialogue',context,playerText,deterministicSeed:hash(`${npcId}:${world.date}:${playerText}`,world.seed)};}
export function generateOfflineDialogue(world:WorldState,npcId:string,playerText:string){return generateOfflineNarration(createDialogueNarrationRequest(world,npcId,playerText));}
export function haveNarratedConversation(input:WorldState,npcId:string,playerText:string):WorldState{const world=haveConversation(input,npcId,playerText),record=world.conversations.find(c=>c.personIds.includes(npcId)&&c.personIds.includes(world.character.id)&&c.date===world.date&&c.playerText===playerText);if(!record)return world;record.response=generateOfflineDialogue(world,npcId,playerText).text;return world;}
export function setNarrationMode(input:WorldState,mode:WorldState['narrationSettings']['mode']):WorldState{const world=structuredClone(input);initializeNarration(world);world.narrationSettings.mode=mode;world.narrationSettings.allowRemoteNarration=mode==='enhanced_when_available';world.narrationSettings.preferredProvider=mode==='enhanced_when_available'?'evera-netlify':'evera-offline';return world;}
