import type { NarrativeFact, NarrationRequest, NarrationResponse, VoiceProfile } from '../types/narration';
import type { NarrationProvider } from './provider';

function hash(text:string,seed:number){let h=seed>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function pick<T>(items:T[],key:string,seed:number){return items[hash(key,seed)%items.length]!;}
function safeFacts(request:NarrationRequest){return request.context.facts.filter(f=>f.allowedToStateAsFact||f.certainty!=='canonical');}
function sentence(fact:NarrativeFact){if(fact.certainty==='canonical')return fact.text;if(fact.certainty==='rumor')return `There is some uncertainty around this: ${fact.text}`;return `From this perspective, ${fact.text.charAt(0).toLowerCase()}${fact.text.slice(1)}`;}
function voiceLead(voice:VoiceProfile|null,seed:number){if(!voice)return'';if(voice.warmth==='warm')return pick(['I want to be clear with you.','I care about how this lands.','I have been thinking about this.'],'warm',seed);if(voice.directness==='direct')return pick(['Here is where I am at.','I will say it plainly.','This is what I think.'],'direct',seed);if(voice.directness==='soft')return pick(['I am trying to say this carefully.','I do not want this to come out wrong.','Can I be open about something?'],'soft',seed);return pick(['I have been thinking.','There is something on my mind.','I want to talk about this.'],'balanced',seed);}
function dialogue(request:NarrationRequest){const facts=safeFacts(request).slice(0,4),lead=voiceLead(request.context.voice,request.deterministicSeed),topic=facts[0]?sentence(facts[0]):'I am still figuring out what I want to say.';const player=request.playerText?.trim();if(!player)return`${lead} ${topic}`.trim();const acknowledgment=request.context.voice?.warmth==='warm'?'I hear what you are saying.':request.context.voice?.directness==='direct'?'I understand the point you are making.':'I get what you mean.';return`${acknowledgment} ${lead} ${topic}`.replace(/\s+/g,' ').trim();}
function chapter(request:NarrationRequest){const facts=request.context.facts.filter(f=>f.certainty==='canonical'&&f.allowedToStateAsFact);if(facts.length===0)return'This year passed without many major moments being recorded. The ordinary routines still moved life forward, even when they did not become headline events.';const grouped=new Map<string,NarrativeFact[]>();for(const fact of facts){const list=grouped.get(fact.category)??[];list.push(fact);grouped.set(fact.category,list);}const order=['relationship','family','career','education','finance','sports','business','health','world','identity','memory'];const selected: NarrativeFact[]=[];for(const category of order){const list=grouped.get(category);if(list?.length)selected.push(list[0]!);}for(const fact of facts)if(selected.length<7&&!selected.includes(fact))selected.push(fact);const opening=pick(['This was a year shaped by several parts of life moving at once.','The year unfolded through a mix of responsibilities, changes and consequences.','Looking back, this year was less about one single moment than the way several parts of life developed together.'],'chapter-open',request.deterministicSeed);const body=selected.slice(0,7).map(sentence).join(' ');const ending=pick(['None of it existed in isolation; each part of life became context for what came next.','Those changes became part of the history carried into the next year.','By year’s end, the consequences of these moments were already becoming the starting conditions for what followed.'],'chapter-end',request.deterministicSeed);return`${opening} ${body} ${ending}`;}
function recap(request:NarrationRequest){const facts=safeFacts(request).slice(0,6);return facts.length?facts.map(sentence).join(' '):'There is not enough recorded information to produce a grounded recap yet.';}
export function generateOfflineNarration(request:NarrationRequest):NarrationResponse{const text=request.purpose==='dialogue'?dialogue(request):request.purpose==='annual_chapter'?chapter(request):recap(request);return{requestId:request.id,providerId:'evera-offline',providerKind:'offline',text,usedFactIds:safeFacts(request).slice(0,7).map(f=>f.id),generatedAt:request.context.date};}
export const offlineNarrationProvider:NarrationProvider={id:'evera-offline',kind:'offline',isAvailable:()=>true,generate:async request=>generateOfflineNarration(request)};
