import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles/global.css';
import './styles/phase3.css';
import './styles/phase4.css';
import './styles/phase5.css';
import './styles/phase6.css';
import './styles/phase7.css';
import './styles/phase8.css';
import './styles/phase9.css';
import './styles/phase10.css';
import './styles/phase11.css';
import './styles/phase12.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
if('serviceWorker'in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(console.error));